// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

import type { ClientContext } from "../../client/index.ts";
import type {
  CustomFieldValueUpdateDetails,
  MultipleCustomFieldValuesUpdateDetails,
} from "../types/index.ts";

/**
 * Update custom fields
 *
 * Updates the value of one or more custom fields on one or more issues. Combinations of custom field and issue should be unique within the request.
 *
 * Apps can only perform this operation on [custom fields](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field/) and [custom field types](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field-type/) declared in their own manifests.
 *
 * **[Permissions](#permissions) required:** Only the app that owns the custom field or custom field type can update its values with this operation.
 *
 * The new `write:app-data:jira` OAuth scope is 100% optional now, and not using it won't break your app. However, we recommend adding it to your app's scope list because we will eventually make it mandatory.
 *
 * @param params.generateChangelog - Whether to generate a changelog for this update.
 * @param params.generateAppEvents - Whether to generate app events for this update. Suppresses Forge, Connect, OAuth 2.0, and admin-configured webhooks (registered via the Jira admin UI). Note: Suppressing events means that "issue updated" events will not be emitted for your app or any other apps installed in Jira. This may cause other apps to retain stale data for the updated field, resulting in potentially confusing behaviour. We do not recommend using this flag in a Marketplace app as it may result in incompatibilities with other apps that depend on up-to-date issue data.
 * @returns Returned if the request is successful.
 */
export function updateMultipleCustomFieldValues(
  ctx: ClientContext,
  params: MultipleCustomFieldValuesUpdateDetails & {
    /**
     * Whether to generate a changelog for this update.
     *
     * @default true
     */
    generateChangelog?: boolean;
    /**
     * Whether to generate app events for this update. Suppresses Forge, Connect, OAuth 2.0, and admin-configured webhooks (registered via the Jira admin UI). Note: Suppressing events means that "issue updated" events will not be emitted for your app or any other apps installed in Jira. This may cause other apps to retain stale data for the updated field, resulting in potentially confusing behaviour. We do not recommend using this flag in a Marketplace app as it may result in incompatibilities with other apps that depend on up-to-date issue data.
     *
     * @default true
     */
    generateAppEvents?: boolean;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { generateChangelog, generateAppEvents, ...body } = params;
  return ctx.request({
    method: "post",
    path: "/rest/api/3/app/field/value",
    query: { generateChangelog, generateAppEvents },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Update custom field value
 *
 * Updates the value of a custom field on one or more issues.
 *
 * Apps can only perform this operation on [custom fields](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field/) and [custom field types](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field-type/) declared in their own manifests.
 *
 * **[Permissions](#permissions) required:** Only the app that owns the custom field or custom field type can update its values with this operation.
 *
 * The new `write:app-data:jira` OAuth scope is 100% optional now, and not using it won't break your app. However, we recommend adding it to your app's scope list because we will eventually make it mandatory.
 *
 * @param params.fieldIdOrKey - The ID or key of the custom field. For example, `customfield_10010`.
 * @param params.generateChangelog - Whether to generate a changelog for this update.
 * @param params.generateAppEvents - Whether to generate app events for this update. Suppresses Forge, Connect, OAuth 2.0, and admin-configured webhooks (registered via the Jira admin UI). Note: Suppressing events means that "issue updated" events will not be emitted for your app or any other apps installed in Jira. This may cause other apps to retain stale data for the updated field, resulting in potentially confusing behaviour. We do not recommend using this flag in a Marketplace app as it may result in incompatibilities with other apps that depend on up-to-date issue data.
 * @returns Returned if the request is successful.
 */
export function updateCustomFieldValue(
  ctx: ClientContext,
  params: CustomFieldValueUpdateDetails & {
    /** The ID or key of the custom field. For example, `customfield_10010`. */
    fieldIdOrKey: string;
    /**
     * Whether to generate a changelog for this update.
     *
     * @default true
     */
    generateChangelog?: boolean;
    /**
     * Whether to generate app events for this update. Suppresses Forge, Connect, OAuth 2.0, and admin-configured webhooks (registered via the Jira admin UI). Note: Suppressing events means that "issue updated" events will not be emitted for your app or any other apps installed in Jira. This may cause other apps to retain stale data for the updated field, resulting in potentially confusing behaviour. We do not recommend using this flag in a Marketplace app as it may result in incompatibilities with other apps that depend on up-to-date issue data.
     *
     * @default true
     */
    generateAppEvents?: boolean;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { fieldIdOrKey, generateChangelog, generateAppEvents, ...body } = params;
  return ctx.request({
    method: "put",
    path: "/rest/api/3/app/field/{fieldIdOrKey}/value",
    pathParams: { fieldIdOrKey },
    query: { generateChangelog, generateAppEvents },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/** This resource represents the values of custom fields added by [Forge apps](https://developer.atlassian.com/platform/forge/). Use it to update the value of a custom field on issues. */
export function createIssueCustomFieldValuesAppsService(ctx: ClientContext) {
  return {
    /**
     * Update custom fields
     *
     * Updates the value of one or more custom fields on one or more issues. Combinations of custom field and issue should be unique within the request.
     *
     * Apps can only perform this operation on [custom fields](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field/) and [custom field types](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field-type/) declared in their own manifests.
     *
     * **[Permissions](#permissions) required:** Only the app that owns the custom field or custom field type can update its values with this operation.
     *
     * The new `write:app-data:jira` OAuth scope is 100% optional now, and not using it won't break your app. However, we recommend adding it to your app's scope list because we will eventually make it mandatory.
     *
     * @param params.generateChangelog - Whether to generate a changelog for this update.
     * @param params.generateAppEvents - Whether to generate app events for this update. Suppresses Forge, Connect, OAuth 2.0, and admin-configured webhooks (registered via the Jira admin UI). Note: Suppressing events means that "issue updated" events will not be emitted for your app or any other apps installed in Jira. This may cause other apps to retain stale data for the updated field, resulting in potentially confusing behaviour. We do not recommend using this flag in a Marketplace app as it may result in incompatibilities with other apps that depend on up-to-date issue data.
     * @returns Returned if the request is successful.
     */
    updateMultipleCustomFieldValues(
      params: MultipleCustomFieldValuesUpdateDetails & {
        /**
         * Whether to generate a changelog for this update.
         *
         * @default true
         */
        generateChangelog?: boolean;
        /**
         * Whether to generate app events for this update. Suppresses Forge, Connect, OAuth 2.0, and admin-configured webhooks (registered via the Jira admin UI). Note: Suppressing events means that "issue updated" events will not be emitted for your app or any other apps installed in Jira. This may cause other apps to retain stale data for the updated field, resulting in potentially confusing behaviour. We do not recommend using this flag in a Marketplace app as it may result in incompatibilities with other apps that depend on up-to-date issue data.
         *
         * @default true
         */
        generateAppEvents?: boolean;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return updateMultipleCustomFieldValues(ctx, params, options);
    },

    /**
     * Update custom field value
     *
     * Updates the value of a custom field on one or more issues.
     *
     * Apps can only perform this operation on [custom fields](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field/) and [custom field types](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field-type/) declared in their own manifests.
     *
     * **[Permissions](#permissions) required:** Only the app that owns the custom field or custom field type can update its values with this operation.
     *
     * The new `write:app-data:jira` OAuth scope is 100% optional now, and not using it won't break your app. However, we recommend adding it to your app's scope list because we will eventually make it mandatory.
     *
     * @param params.fieldIdOrKey - The ID or key of the custom field. For example, `customfield_10010`.
     * @param params.generateChangelog - Whether to generate a changelog for this update.
     * @param params.generateAppEvents - Whether to generate app events for this update. Suppresses Forge, Connect, OAuth 2.0, and admin-configured webhooks (registered via the Jira admin UI). Note: Suppressing events means that "issue updated" events will not be emitted for your app or any other apps installed in Jira. This may cause other apps to retain stale data for the updated field, resulting in potentially confusing behaviour. We do not recommend using this flag in a Marketplace app as it may result in incompatibilities with other apps that depend on up-to-date issue data.
     * @returns Returned if the request is successful.
     */
    updateCustomFieldValue(
      params: CustomFieldValueUpdateDetails & {
        /** The ID or key of the custom field. For example, `customfield_10010`. */
        fieldIdOrKey: string;
        /**
         * Whether to generate a changelog for this update.
         *
         * @default true
         */
        generateChangelog?: boolean;
        /**
         * Whether to generate app events for this update. Suppresses Forge, Connect, OAuth 2.0, and admin-configured webhooks (registered via the Jira admin UI). Note: Suppressing events means that "issue updated" events will not be emitted for your app or any other apps installed in Jira. This may cause other apps to retain stale data for the updated field, resulting in potentially confusing behaviour. We do not recommend using this flag in a Marketplace app as it may result in incompatibilities with other apps that depend on up-to-date issue data.
         *
         * @default true
         */
        generateAppEvents?: boolean;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return updateCustomFieldValue(ctx, params, options);
    },
  };
}
