// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

import type { ClientContext } from "../../client/index.ts";
import type {
  Attachment,
  AttachmentArchiveImpl,
  AttachmentArchiveMetadataReadable,
  AttachmentMetadata,
  AttachmentSettings,
  MultipartFile,
} from "../types/index.ts";

/**
 * Get attachment content
 *
 * Returns the contents of an attachment. A `Range` header can be set to define a range of bytes within the attachment to download. See the [HTTP Range header standard](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) for details.
 *
 * To return a thumbnail of the attachment, use [Get attachment thumbnail](#api-rest-api-3-attachment-thumbnail-id-get).
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** For the issue containing the attachment:
 *
 *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *  *  If attachments are added in private comments, the comment-level restriction will be applied.
 *
 * @param params.id - The ID of the attachment.
 * @param params.redirect - Whether a redirect is provided for the attachment download. Clients that do not automatically follow redirects can set this to `false` to avoid making multiple requests to download the attachment.
 * @returns Returned if the request is successful when `redirect` is set to `false`.
 */
export function getAttachmentContent(
  ctx: ClientContext,
  params: {
    /** The ID of the attachment. */
    id: string;
    /**
     * Whether a redirect is provided for the attachment download. Clients that do not automatically follow redirects can set this to `false` to avoid making multiple requests to download the attachment.
     *
     * @default true
     */
    redirect?: boolean;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<void> {
  const { id, redirect } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/3/attachment/content/{id}",
    pathParams: { id },
    query: { redirect },
    headers: options?.headers,
    responseType: "void",
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get Jira attachment settings
 *
 * Returns the attachment settings, that is, whether attachments are enabled and the maximum attachment size allowed.
 *
 * Note that there are also [project permissions](https://confluence.atlassian.com/x/yodKLg) that restrict whether users can create and delete attachments.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** None.
 *
 * @returns Returned if the request is successful.
 */
export function getAttachmentMeta(
  ctx: ClientContext,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<AttachmentSettings> {
  return ctx.request({
    method: "get",
    path: "/rest/api/3/attachment/meta",
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get attachment thumbnail
 *
 * Returns the thumbnail of an attachment.
 *
 * To return the attachment contents, use [Get attachment content](#api-rest-api-3-attachment-content-id-get).
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** For the issue containing the attachment:
 *
 *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *  *  If attachments are added in private comments, the comment-level restriction will be applied.
 *
 * @param params.id - The ID of the attachment.
 * @param params.redirect - Whether a redirect is provided for the attachment download. Clients that do not automatically follow redirects can set this to `false` to avoid making multiple requests to download the attachment.
 * @param params.fallbackToDefault - Whether a default thumbnail is returned when the requested thumbnail is not found.
 * @param params.width - The maximum width to scale the thumbnail to.
 * @param params.height - The maximum height to scale the thumbnail to.
 * @returns Returned if the request is successful when `redirect` is set to `false`.
 */
export function getAttachmentThumbnail(
  ctx: ClientContext,
  params: {
    /** The ID of the attachment. */
    id: string;
    /**
     * Whether a redirect is provided for the attachment download. Clients that do not automatically follow redirects can set this to `false` to avoid making multiple requests to download the attachment.
     *
     * @default true
     */
    redirect?: boolean;
    /**
     * Whether a default thumbnail is returned when the requested thumbnail is not found.
     *
     * @default true
     */
    fallbackToDefault?: boolean;
    /**
     * The maximum width to scale the thumbnail to.
     *
     * @format int32
     */
    width?: number;
    /**
     * The maximum height to scale the thumbnail to.
     *
     * @format int32
     */
    height?: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<void> {
  const { id, redirect, fallbackToDefault, width, height } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/3/attachment/thumbnail/{id}",
    pathParams: { id },
    query: { redirect, fallbackToDefault, width, height },
    headers: options?.headers,
    responseType: "void",
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get attachment metadata
 *
 * Returns the metadata for an attachment. Note that the attachment itself is not returned.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *  *  If attachments are added in private comments, the comment-level restriction will be applied.
 *
 * @param params.id - The ID of the attachment.
 * @returns Returned if the request is successful.
 */
export function getAttachment(
  ctx: ClientContext,
  params: {
    /** The ID of the attachment. */
    id: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<AttachmentMetadata> {
  const { id } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/3/attachment/{id}",
    pathParams: { id },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Delete attachment
 *
 * Deletes an attachment from an issue.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** For the project holding the issue containing the attachment:
 *
 *  *  *Delete own attachments* [project permission](https://confluence.atlassian.com/x/yodKLg) to delete an attachment created by the calling user.
 *  *  *Delete all attachments* [project permission](https://confluence.atlassian.com/x/yodKLg) to delete an attachment created by any user.
 *
 * @param params.id - The ID of the attachment.
 * @returns Returned if the request is successful.
 */
export function removeAttachment(
  ctx: ClientContext,
  params: {
    /** The ID of the attachment. */
    id: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<void> {
  const { id } = params;
  return ctx.request({
    method: "delete",
    path: "/rest/api/3/attachment/{id}",
    pathParams: { id },
    headers: options?.headers,
    responseType: "void",
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get all metadata for an expanded attachment
 *
 * Returns the metadata for the contents of an attachment, if it is an archive, and metadata for the attachment itself. For example, if the attachment is a ZIP archive, then information about the files in the archive is returned and metadata for the ZIP archive. Currently, only the ZIP archive format is supported.
 *
 * Use this operation to retrieve data that is presented to the user, as this operation returns the metadata for the attachment itself, such as the attachment's ID and name. Otherwise, use [ Get contents metadata for an expanded attachment](#api-rest-api-3-attachment-id-expand-raw-get), which only returns the metadata for the attachment's contents.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** For the issue containing the attachment:
 *
 *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *  *  If attachments are added in private comments, the comment-level restriction will be applied.
 *
 * @param params.id - The ID of the attachment.
 * @returns Returned if the request is successful. If an empty list is returned in the response, the attachment is empty, corrupt, or not an archive.
 */
export function expandAttachmentForHumans(
  ctx: ClientContext,
  params: {
    /** The ID of the attachment. */
    id: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<AttachmentArchiveMetadataReadable> {
  const { id } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/3/attachment/{id}/expand/human",
    pathParams: { id },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get contents metadata for an expanded attachment
 *
 * Returns the metadata for the contents of an attachment, if it is an archive. For example, if the attachment is a ZIP archive, then information about the files in the archive is returned. Currently, only the ZIP archive format is supported.
 *
 * Use this operation if you are processing the data without presenting it to the user, as this operation only returns the metadata for the contents of the attachment. Otherwise, to retrieve data to present to the user, use [ Get all metadata for an expanded attachment](#api-rest-api-3-attachment-id-expand-human-get) which also returns the metadata for the attachment itself, such as the attachment's ID and name.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** For the issue containing the attachment:
 *
 *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *  *  If attachments are added in private comments, the comment-level restriction will be applied.
 *
 * @param params.id - The ID of the attachment.
 * @returns Returned if the request is successful. If an empty list is returned in the response, the attachment is empty, corrupt, or not an archive.
 */
export function expandAttachmentForMachines(
  ctx: ClientContext,
  params: {
    /** The ID of the attachment. */
    id: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<AttachmentArchiveImpl> {
  const { id } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/3/attachment/{id}/expand/raw",
    pathParams: { id },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Add attachment
 *
 * Adds one or more attachments to an issue. Attachments are posted as multipart/form-data ([RFC 1867](https://www.ietf.org/rfc/rfc1867.txt)).
 *
 * Note that:
 *
 *  *  The request must have a `X-Atlassian-Token: no-check` header, if not it is blocked. See [Special headers](#special-request-headers) for more information.
 *  *  The name of the multipart/form-data parameter that contains the attachments must be `file`.
 *
 * The following examples upload a file called *myfile.txt* to the issue *TEST-123*:
 *
 * #### curl ####
 *
 *     curl --location --request POST 'https://your-domain.atlassian.net/rest/api/3/issue/TEST-123/attachments'
 *      -u 'email@example.com:<api_token>'
 *      -H 'X-Atlassian-Token: no-check'
 *      --form 'file=@"myfile.txt"'
 *
 * #### Node.js ####
 *
 *     // This code sample uses the 'node-fetch' and 'form-data' libraries:
 *      // https://www.npmjs.com/package/node-fetch
 *      // https://www.npmjs.com/package/form-data
 *      const fetch = require('node-fetch');
 *      const FormData = require('form-data');
 *      const fs = require('fs');
 *
 *      const filePath = 'myfile.txt';
 *      const form = new FormData();
 *      const stats = fs.statSync(filePath);
 *      const fileSizeInBytes = stats.size;
 *      const fileStream = fs.createReadStream(filePath);
 *
 *      form.append('file', fileStream, {knownLength: fileSizeInBytes});
 *
 *      fetch('https://your-domain.atlassian.net/rest/api/3/issue/TEST-123/attachments', {
 *          method: 'POST',
 *          body: form,
 *          headers: {
 *              'Authorization': `Basic ${Buffer.from(
 *                  'email@example.com:'
 *              ).toString('base64')}`,
 *              'Accept': 'application/json',
 *              'X-Atlassian-Token': 'no-check'
 *          }
 *      })
 *          .then(response => {
 *              console.log(
 *                  `Response: ${response.status} ${response.statusText}`
 *              );
 *              return response.text();
 *          })
 *          .then(text => console.log(text))
 *          .catch(err => console.error(err));
 *
 * #### Java ####
 *
 *     // This code sample uses the  'Unirest' library:
 *      // http://unirest.io/java.html
 *      HttpResponse response = Unirest.post("https://your-domain.atlassian.net/rest/api/2/issue/{issueIdOrKey}/attachments")
 *              .basicAuth("email@example.com", "")
 *              .header("Accept", "application/json")
 *              .header("X-Atlassian-Token", "no-check")
 *              .field("file", new File("myfile.txt"))
 *              .asJson();
 *
 *              System.out.println(response.getBody());
 *
 * #### Python ####
 *
 *     # This code sample uses the 'requests' library:
 *      # http://docs.python-requests.org
 *      import requests
 *      from requests.auth import HTTPBasicAuth
 *      import json
 *
 *      url = "https://your-domain.atlassian.net/rest/api/2/issue/{issueIdOrKey}/attachments"
 *
 *      auth = HTTPBasicAuth("email@example.com", "")
 *
 *      headers = {
 *         "Accept": "application/json",
 *         "X-Atlassian-Token": "no-check"
 *      }
 *
 *      response = requests.request(
 *         "POST",
 *         url,
 *         headers = headers,
 *         auth = auth,
 *         files = {
 *              "file": ("myfile.txt", open("myfile.txt","rb"), "application-type")
 *         }
 *      )
 *
 *      print(json.dumps(json.loads(response.text), sort_keys=True, indent=4, separators=(",", ": ")))
 *
 * #### PHP ####
 *
 *     // This code sample uses the 'Unirest' library:
 *      // http://unirest.io/php.html
 *      Unirest\Request::auth('email@example.com', '');
 *
 *      $headers = array(
 *        'Accept' => 'application/json',
 *        'X-Atlassian-Token' => 'no-check'
 *      );
 *
 *      $parameters = array(
 *        'file' => File::add('myfile.txt')
 *      );
 *
 *      $response = Unirest\Request::post(
 *        'https://your-domain.atlassian.net/rest/api/2/issue/{issueIdOrKey}/attachments',
 *        $headers,
 *        $parameters
 *      );
 *
 *      var_dump($response)
 *
 * #### Forge ####
 *
 *     // This sample uses Atlassian Forge and the `form-data` library.
 *      // https://developer.atlassian.com/platform/forge/
 *      // https://www.npmjs.com/package/form-data
 *      import api from "@forge/api";
 *      import FormData from "form-data";
 *
 *      const form = new FormData();
 *      form.append('file', fileStream, {knownLength: fileSizeInBytes});
 *
 *      const response = await api.asApp().requestJira('/rest/api/2/issue/{issueIdOrKey}/attachments', {
 *          method: 'POST',
 *          body: form,
 *          headers: {
 *              'Accept': 'application/json',
 *              'X-Atlassian-Token': 'no-check'
 *          }
 *      });
 *
 *      console.log(`Response: ${response.status} ${response.statusText}`);
 *      console.log(await response.json());
 *
 * Tip: Use a client library. Many client libraries have classes for handling multipart POST operations. For example, in Java, the Apache HTTP Components library provides a [MultiPartEntity](http://hc.apache.org/httpcomponents-client-ga/httpmime/apidocs/org/apache/http/entity/mime/MultipartEntity.html) class for multipart POST operations.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  *Browse Projects* and *Create attachments* [ project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *
 * @param params.issueIdOrKey - The ID or key of the issue that attachments are added to.
 * @returns Returned if the request is successful.
 */
export function addAttachment(
  ctx: ClientContext,
  params: {
    /** The ID or key of the issue that attachments are added to. */
    issueIdOrKey: string;
    body: MultipartFile[];
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<Attachment[]> {
  const { issueIdOrKey, body } = params;
  return ctx.request({
    method: "post",
    path: "/rest/api/3/issue/{issueIdOrKey}/attachments",
    pathParams: { issueIdOrKey },
    headers: options?.headers,
    body: body,
    bodyType: "form-data",
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/** This resource represents issue attachments and the attachment settings for Jira. Use it to get the metadata for an attachment, delete an attachment, and view the metadata for the contents of an attachment. Also, use it to get the attachment settings for Jira. */
export function createIssueAttachmentsService(ctx: ClientContext) {
  return {
    /**
     * Get attachment content
     *
     * Returns the contents of an attachment. A `Range` header can be set to define a range of bytes within the attachment to download. See the [HTTP Range header standard](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) for details.
     *
     * To return a thumbnail of the attachment, use [Get attachment thumbnail](#api-rest-api-3-attachment-thumbnail-id-get).
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** For the issue containing the attachment:
     *
     *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *  *  If attachments are added in private comments, the comment-level restriction will be applied.
     *
     * @param params.id - The ID of the attachment.
     * @param params.redirect - Whether a redirect is provided for the attachment download. Clients that do not automatically follow redirects can set this to `false` to avoid making multiple requests to download the attachment.
     * @returns Returned if the request is successful when `redirect` is set to `false`.
     */
    getAttachmentContent(
      params: {
        /** The ID of the attachment. */
        id: string;
        /**
         * Whether a redirect is provided for the attachment download. Clients that do not automatically follow redirects can set this to `false` to avoid making multiple requests to download the attachment.
         *
         * @default true
         */
        redirect?: boolean;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<void> {
      return getAttachmentContent(ctx, params, options);
    },

    /**
     * Get Jira attachment settings
     *
     * Returns the attachment settings, that is, whether attachments are enabled and the maximum attachment size allowed.
     *
     * Note that there are also [project permissions](https://confluence.atlassian.com/x/yodKLg) that restrict whether users can create and delete attachments.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** None.
     *
     * @returns Returned if the request is successful.
     */
    getAttachmentMeta(options?: {
      headers?: Record<string, string | number | boolean>;
      signal?: AbortSignal;
      extensions?: Record<string, unknown>;
    }): Promise<AttachmentSettings> {
      return getAttachmentMeta(ctx, options);
    },

    /**
     * Get attachment thumbnail
     *
     * Returns the thumbnail of an attachment.
     *
     * To return the attachment contents, use [Get attachment content](#api-rest-api-3-attachment-content-id-get).
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** For the issue containing the attachment:
     *
     *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *  *  If attachments are added in private comments, the comment-level restriction will be applied.
     *
     * @param params.id - The ID of the attachment.
     * @param params.redirect - Whether a redirect is provided for the attachment download. Clients that do not automatically follow redirects can set this to `false` to avoid making multiple requests to download the attachment.
     * @param params.fallbackToDefault - Whether a default thumbnail is returned when the requested thumbnail is not found.
     * @param params.width - The maximum width to scale the thumbnail to.
     * @param params.height - The maximum height to scale the thumbnail to.
     * @returns Returned if the request is successful when `redirect` is set to `false`.
     */
    getAttachmentThumbnail(
      params: {
        /** The ID of the attachment. */
        id: string;
        /**
         * Whether a redirect is provided for the attachment download. Clients that do not automatically follow redirects can set this to `false` to avoid making multiple requests to download the attachment.
         *
         * @default true
         */
        redirect?: boolean;
        /**
         * Whether a default thumbnail is returned when the requested thumbnail is not found.
         *
         * @default true
         */
        fallbackToDefault?: boolean;
        /**
         * The maximum width to scale the thumbnail to.
         *
         * @format int32
         */
        width?: number;
        /**
         * The maximum height to scale the thumbnail to.
         *
         * @format int32
         */
        height?: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<void> {
      return getAttachmentThumbnail(ctx, params, options);
    },

    /**
     * Get attachment metadata
     *
     * Returns the metadata for an attachment. Note that the attachment itself is not returned.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *  *  If attachments are added in private comments, the comment-level restriction will be applied.
     *
     * @param params.id - The ID of the attachment.
     * @returns Returned if the request is successful.
     */
    getAttachment(
      params: {
        /** The ID of the attachment. */
        id: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<AttachmentMetadata> {
      return getAttachment(ctx, params, options);
    },

    /**
     * Delete attachment
     *
     * Deletes an attachment from an issue.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** For the project holding the issue containing the attachment:
     *
     *  *  *Delete own attachments* [project permission](https://confluence.atlassian.com/x/yodKLg) to delete an attachment created by the calling user.
     *  *  *Delete all attachments* [project permission](https://confluence.atlassian.com/x/yodKLg) to delete an attachment created by any user.
     *
     * @param params.id - The ID of the attachment.
     * @returns Returned if the request is successful.
     */
    removeAttachment(
      params: {
        /** The ID of the attachment. */
        id: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<void> {
      return removeAttachment(ctx, params, options);
    },

    /**
     * Get all metadata for an expanded attachment
     *
     * Returns the metadata for the contents of an attachment, if it is an archive, and metadata for the attachment itself. For example, if the attachment is a ZIP archive, then information about the files in the archive is returned and metadata for the ZIP archive. Currently, only the ZIP archive format is supported.
     *
     * Use this operation to retrieve data that is presented to the user, as this operation returns the metadata for the attachment itself, such as the attachment's ID and name. Otherwise, use [ Get contents metadata for an expanded attachment](#api-rest-api-3-attachment-id-expand-raw-get), which only returns the metadata for the attachment's contents.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** For the issue containing the attachment:
     *
     *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *  *  If attachments are added in private comments, the comment-level restriction will be applied.
     *
     * @param params.id - The ID of the attachment.
     * @returns Returned if the request is successful. If an empty list is returned in the response, the attachment is empty, corrupt, or not an archive.
     */
    expandAttachmentForHumans(
      params: {
        /** The ID of the attachment. */
        id: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<AttachmentArchiveMetadataReadable> {
      return expandAttachmentForHumans(ctx, params, options);
    },

    /**
     * Get contents metadata for an expanded attachment
     *
     * Returns the metadata for the contents of an attachment, if it is an archive. For example, if the attachment is a ZIP archive, then information about the files in the archive is returned. Currently, only the ZIP archive format is supported.
     *
     * Use this operation if you are processing the data without presenting it to the user, as this operation only returns the metadata for the contents of the attachment. Otherwise, to retrieve data to present to the user, use [ Get all metadata for an expanded attachment](#api-rest-api-3-attachment-id-expand-human-get) which also returns the metadata for the attachment itself, such as the attachment's ID and name.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** For the issue containing the attachment:
     *
     *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *  *  If attachments are added in private comments, the comment-level restriction will be applied.
     *
     * @param params.id - The ID of the attachment.
     * @returns Returned if the request is successful. If an empty list is returned in the response, the attachment is empty, corrupt, or not an archive.
     */
    expandAttachmentForMachines(
      params: {
        /** The ID of the attachment. */
        id: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<AttachmentArchiveImpl> {
      return expandAttachmentForMachines(ctx, params, options);
    },

    /**
     * Add attachment
     *
     * Adds one or more attachments to an issue. Attachments are posted as multipart/form-data ([RFC 1867](https://www.ietf.org/rfc/rfc1867.txt)).
     *
     * Note that:
     *
     *  *  The request must have a `X-Atlassian-Token: no-check` header, if not it is blocked. See [Special headers](#special-request-headers) for more information.
     *  *  The name of the multipart/form-data parameter that contains the attachments must be `file`.
     *
     * The following examples upload a file called *myfile.txt* to the issue *TEST-123*:
     *
     * #### curl ####
     *
     *     curl --location --request POST 'https://your-domain.atlassian.net/rest/api/3/issue/TEST-123/attachments'
     *      -u 'email@example.com:<api_token>'
     *      -H 'X-Atlassian-Token: no-check'
     *      --form 'file=@"myfile.txt"'
     *
     * #### Node.js ####
     *
     *     // This code sample uses the 'node-fetch' and 'form-data' libraries:
     *      // https://www.npmjs.com/package/node-fetch
     *      // https://www.npmjs.com/package/form-data
     *      const fetch = require('node-fetch');
     *      const FormData = require('form-data');
     *      const fs = require('fs');
     *
     *      const filePath = 'myfile.txt';
     *      const form = new FormData();
     *      const stats = fs.statSync(filePath);
     *      const fileSizeInBytes = stats.size;
     *      const fileStream = fs.createReadStream(filePath);
     *
     *      form.append('file', fileStream, {knownLength: fileSizeInBytes});
     *
     *      fetch('https://your-domain.atlassian.net/rest/api/3/issue/TEST-123/attachments', {
     *          method: 'POST',
     *          body: form,
     *          headers: {
     *              'Authorization': `Basic ${Buffer.from(
     *                  'email@example.com:'
     *              ).toString('base64')}`,
     *              'Accept': 'application/json',
     *              'X-Atlassian-Token': 'no-check'
     *          }
     *      })
     *          .then(response => {
     *              console.log(
     *                  `Response: ${response.status} ${response.statusText}`
     *              );
     *              return response.text();
     *          })
     *          .then(text => console.log(text))
     *          .catch(err => console.error(err));
     *
     * #### Java ####
     *
     *     // This code sample uses the  'Unirest' library:
     *      // http://unirest.io/java.html
     *      HttpResponse response = Unirest.post("https://your-domain.atlassian.net/rest/api/2/issue/{issueIdOrKey}/attachments")
     *              .basicAuth("email@example.com", "")
     *              .header("Accept", "application/json")
     *              .header("X-Atlassian-Token", "no-check")
     *              .field("file", new File("myfile.txt"))
     *              .asJson();
     *
     *              System.out.println(response.getBody());
     *
     * #### Python ####
     *
     *     # This code sample uses the 'requests' library:
     *      # http://docs.python-requests.org
     *      import requests
     *      from requests.auth import HTTPBasicAuth
     *      import json
     *
     *      url = "https://your-domain.atlassian.net/rest/api/2/issue/{issueIdOrKey}/attachments"
     *
     *      auth = HTTPBasicAuth("email@example.com", "")
     *
     *      headers = {
     *         "Accept": "application/json",
     *         "X-Atlassian-Token": "no-check"
     *      }
     *
     *      response = requests.request(
     *         "POST",
     *         url,
     *         headers = headers,
     *         auth = auth,
     *         files = {
     *              "file": ("myfile.txt", open("myfile.txt","rb"), "application-type")
     *         }
     *      )
     *
     *      print(json.dumps(json.loads(response.text), sort_keys=True, indent=4, separators=(",", ": ")))
     *
     * #### PHP ####
     *
     *     // This code sample uses the 'Unirest' library:
     *      // http://unirest.io/php.html
     *      Unirest\Request::auth('email@example.com', '');
     *
     *      $headers = array(
     *        'Accept' => 'application/json',
     *        'X-Atlassian-Token' => 'no-check'
     *      );
     *
     *      $parameters = array(
     *        'file' => File::add('myfile.txt')
     *      );
     *
     *      $response = Unirest\Request::post(
     *        'https://your-domain.atlassian.net/rest/api/2/issue/{issueIdOrKey}/attachments',
     *        $headers,
     *        $parameters
     *      );
     *
     *      var_dump($response)
     *
     * #### Forge ####
     *
     *     // This sample uses Atlassian Forge and the `form-data` library.
     *      // https://developer.atlassian.com/platform/forge/
     *      // https://www.npmjs.com/package/form-data
     *      import api from "@forge/api";
     *      import FormData from "form-data";
     *
     *      const form = new FormData();
     *      form.append('file', fileStream, {knownLength: fileSizeInBytes});
     *
     *      const response = await api.asApp().requestJira('/rest/api/2/issue/{issueIdOrKey}/attachments', {
     *          method: 'POST',
     *          body: form,
     *          headers: {
     *              'Accept': 'application/json',
     *              'X-Atlassian-Token': 'no-check'
     *          }
     *      });
     *
     *      console.log(`Response: ${response.status} ${response.statusText}`);
     *      console.log(await response.json());
     *
     * Tip: Use a client library. Many client libraries have classes for handling multipart POST operations. For example, in Java, the Apache HTTP Components library provides a [MultiPartEntity](http://hc.apache.org/httpcomponents-client-ga/httpmime/apidocs/org/apache/http/entity/mime/MultipartEntity.html) class for multipart POST operations.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  *Browse Projects* and *Create attachments* [ project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *
     * @param params.issueIdOrKey - The ID or key of the issue that attachments are added to.
     * @returns Returned if the request is successful.
     */
    addAttachment(
      params: {
        /** The ID or key of the issue that attachments are added to. */
        issueIdOrKey: string;
        body: MultipartFile[];
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<Attachment[]> {
      return addAttachment(ctx, params, options);
    },
  };
}
