// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

import type { ClientContext } from "../../client/index.ts";
import type { EntityProperty, PropertyKeys } from "../types/index.ts";

/**
 * Get worklog property keys
 *
 * Returns the keys of all properties for a worklog.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *  *  If the worklog has visibility restrictions, belongs to the group or has the role visibility is restricted to.
 *
 * @param params.issueIdOrKey - The ID or key of the issue.
 * @param params.worklogId - The ID of the worklog.
 * @returns Returned if the request is successful.
 */
export function getWorklogPropertyKeys(
  ctx: ClientContext,
  params: {
    /** The ID or key of the issue. */
    issueIdOrKey: string;
    /** The ID of the worklog. */
    worklogId: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PropertyKeys> {
  const { issueIdOrKey, worklogId } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/3/issue/{issueIdOrKey}/worklog/{worklogId}/properties",
    pathParams: { issueIdOrKey, worklogId },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get worklog property
 *
 * Returns the value of a worklog property.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *  *  If the worklog has visibility restrictions, belongs to the group or has the role visibility is restricted to.
 *
 * @param params.issueIdOrKey - The ID or key of the issue.
 * @param params.worklogId - The ID of the worklog.
 * @param params.propertyKey - The key of the property.
 * @returns Returned if the request is successful.
 */
export function getWorklogProperty(
  ctx: ClientContext,
  params: {
    /** The ID or key of the issue. */
    issueIdOrKey: string;
    /** The ID of the worklog. */
    worklogId: string;
    /** The key of the property. */
    propertyKey: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<EntityProperty> {
  const { issueIdOrKey, worklogId, propertyKey } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/3/issue/{issueIdOrKey}/worklog/{worklogId}/properties/{propertyKey}",
    pathParams: { issueIdOrKey, worklogId, propertyKey },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Set worklog property
 *
 * Sets the value of a worklog property. Use this operation to store custom data against the worklog.
 *
 * The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *  *  *Edit all worklogs*[ project permission](https://confluence.atlassian.com/x/yodKLg) to update any worklog or *Edit own worklogs* to update worklogs created by the user.
 *  *  If the worklog has visibility restrictions, belongs to the group or has the role visibility is restricted to.
 *
 * @param params.issueIdOrKey - The ID or key of the issue.
 * @param params.worklogId - The ID of the worklog.
 * @param params.propertyKey - The key of the issue property. The maximum length is 255 characters.
 * @param params.body - The value of the property. The value has to be a valid, non-empty [JSON](https://tools.ietf.org/html/rfc4627) value. The maximum length of the property value is 32768 bytes.
 * @returns Returned if the worklog property is updated.
 */
export function setWorklogProperty(
  ctx: ClientContext,
  params: {
    /** The ID or key of the issue. */
    issueIdOrKey: string;
    /** The ID of the worklog. */
    worklogId: string;
    /** The key of the issue property. The maximum length is 255 characters. */
    propertyKey: string;
    body: unknown;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { issueIdOrKey, worklogId, propertyKey, body } = params;
  return ctx.request({
    method: "put",
    path: "/rest/api/3/issue/{issueIdOrKey}/worklog/{worklogId}/properties/{propertyKey}",
    pathParams: { issueIdOrKey, worklogId, propertyKey },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Delete worklog property
 *
 * Deletes a worklog property.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *  *  If the worklog has visibility restrictions, belongs to the group or has the role visibility is restricted to.
 *
 * @param params.issueIdOrKey - The ID or key of the issue.
 * @param params.worklogId - The ID of the worklog.
 * @param params.propertyKey - The key of the property.
 * @returns Returned if the worklog property is removed.
 */
export function deleteWorklogProperty(
  ctx: ClientContext,
  params: {
    /** The ID or key of the issue. */
    issueIdOrKey: string;
    /** The ID of the worklog. */
    worklogId: string;
    /** The key of the property. */
    propertyKey: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<void> {
  const { issueIdOrKey, worklogId, propertyKey } = params;
  return ctx.request({
    method: "delete",
    path: "/rest/api/3/issue/{issueIdOrKey}/worklog/{worklogId}/properties/{propertyKey}",
    pathParams: { issueIdOrKey, worklogId, propertyKey },
    headers: options?.headers,
    responseType: "void",
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/** This resource represents [issue worklog](#api-group-Issue-worklogs) properties, which provides for storing custom data against an issue worklog. Use it to get, create, and delete issue worklog properties as well as obtain the keys of all properties on a issue worklog. Issue worklog properties are a type of [entity property](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/). */
export function createIssueWorklogPropertiesService(ctx: ClientContext) {
  return {
    /**
     * Get worklog property keys
     *
     * Returns the keys of all properties for a worklog.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *  *  If the worklog has visibility restrictions, belongs to the group or has the role visibility is restricted to.
     *
     * @param params.issueIdOrKey - The ID or key of the issue.
     * @param params.worklogId - The ID of the worklog.
     * @returns Returned if the request is successful.
     */
    getWorklogPropertyKeys(
      params: {
        /** The ID or key of the issue. */
        issueIdOrKey: string;
        /** The ID of the worklog. */
        worklogId: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PropertyKeys> {
      return getWorklogPropertyKeys(ctx, params, options);
    },

    /**
     * Get worklog property
     *
     * Returns the value of a worklog property.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *  *  If the worklog has visibility restrictions, belongs to the group or has the role visibility is restricted to.
     *
     * @param params.issueIdOrKey - The ID or key of the issue.
     * @param params.worklogId - The ID of the worklog.
     * @param params.propertyKey - The key of the property.
     * @returns Returned if the request is successful.
     */
    getWorklogProperty(
      params: {
        /** The ID or key of the issue. */
        issueIdOrKey: string;
        /** The ID of the worklog. */
        worklogId: string;
        /** The key of the property. */
        propertyKey: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<EntityProperty> {
      return getWorklogProperty(ctx, params, options);
    },

    /**
     * Set worklog property
     *
     * Sets the value of a worklog property. Use this operation to store custom data against the worklog.
     *
     * The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *  *  *Edit all worklogs*[ project permission](https://confluence.atlassian.com/x/yodKLg) to update any worklog or *Edit own worklogs* to update worklogs created by the user.
     *  *  If the worklog has visibility restrictions, belongs to the group or has the role visibility is restricted to.
     *
     * @param params.issueIdOrKey - The ID or key of the issue.
     * @param params.worklogId - The ID of the worklog.
     * @param params.propertyKey - The key of the issue property. The maximum length is 255 characters.
     * @param params.body - The value of the property. The value has to be a valid, non-empty [JSON](https://tools.ietf.org/html/rfc4627) value. The maximum length of the property value is 32768 bytes.
     * @returns Returned if the worklog property is updated.
     */
    setWorklogProperty(
      params: {
        /** The ID or key of the issue. */
        issueIdOrKey: string;
        /** The ID of the worklog. */
        worklogId: string;
        /** The key of the issue property. The maximum length is 255 characters. */
        propertyKey: string;
        body: unknown;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return setWorklogProperty(ctx, params, options);
    },

    /**
     * Delete worklog property
     *
     * Deletes a worklog property.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *  *  If the worklog has visibility restrictions, belongs to the group or has the role visibility is restricted to.
     *
     * @param params.issueIdOrKey - The ID or key of the issue.
     * @param params.worklogId - The ID of the worklog.
     * @param params.propertyKey - The key of the property.
     * @returns Returned if the worklog property is removed.
     */
    deleteWorklogProperty(
      params: {
        /** The ID or key of the issue. */
        issueIdOrKey: string;
        /** The ID of the worklog. */
        worklogId: string;
        /** The key of the property. */
        propertyKey: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<void> {
      return deleteWorklogProperty(ctx, params, options);
    },
  };
}
