// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

import type { ClientContext } from "../../client/index.ts";
import type {
  BulkEditGetFields,
  BulkOperationProgress,
  BulkTransitionGetAvailableTransitions,
  IssueBulkDeletePayload,
  IssueBulkEditPayload,
  IssueBulkMovePayload,
  IssueBulkTransitionPayload,
  IssueBulkWatchOrUnwatchPayload,
  SubmittedBulkOperation,
} from "../types/index.ts";

/**
 * Bulk delete issues
 *
 * Use this API to submit a bulk delete request. You can delete up to 1,000 issues in a single operation.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
 *  *  Delete [issues permission](https://support.atlassian.com/jira-cloud-administration/docs/permissions-for-company-managed-projects/#Delete-issues/) in all projects that contain the selected issues.
 *  *  Browse [project permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in all projects that contain the selected issues.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *
 * @returns Returned if the request is successful.
 */
export function submitBulkDelete(
  ctx: ClientContext,
  params: IssueBulkDeletePayload,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<SubmittedBulkOperation> {
  return ctx.request({
    method: "post",
    path: "/rest/api/3/bulk/issues/delete",
    headers: options?.headers,
    body: params,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get bulk editable fields
 *
 * Use this API to get a list of fields visible to the user to perform bulk edit operations. You can pass single or multiple issues in the query to get eligible editable fields. This API uses pagination to return responses, delivering 50 fields at a time.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
 *  *  Browse [project permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in all projects that contain the selected issues.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *  *  Depending on the field, any field-specific permissions required to edit it.
 *
 * @param params.issueIdsOrKeys - The IDs or keys of the issues to get editable fields from.
 * @param params.searchText - (Optional)The text to search for in the editable fields.
 * @param params.endingBefore - (Optional)The end cursor for use in pagination.
 * @param params.startingAfter - (Optional)The start cursor for use in pagination.
 * @returns Returned if the request is successful.
 */
export function getBulkEditableFields(
  ctx: ClientContext,
  params: {
    /** The IDs or keys of the issues to get editable fields from. */
    issueIdsOrKeys: string;
    /** (Optional)The text to search for in the editable fields. */
    searchText?: string;
    /** (Optional)The end cursor for use in pagination. */
    endingBefore?: string;
    /** (Optional)The start cursor for use in pagination. */
    startingAfter?: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<BulkEditGetFields> {
  const { issueIdsOrKeys, searchText, endingBefore, startingAfter } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/3/bulk/issues/fields",
    query: { issueIdsOrKeys, searchText, endingBefore, startingAfter },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Bulk edit issues
 *
 * Use this API to submit a bulk edit request and simultaneously edit multiple issues. There are limits applied to the number of issues and fields that can be edited. A single request can accommodate a maximum of 1000 issues (including subtasks) and 200 fields.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
 *  *  Browse [project permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in all projects that contain the selected issues.
 *  *  Edit [issues permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in all projects that contain the selected issues.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *
 * @returns Returned if the request is successful.
 */
export function submitBulkEdit(
  ctx: ClientContext,
  params: IssueBulkEditPayload,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<SubmittedBulkOperation> {
  return ctx.request({
    method: "post",
    path: "/rest/api/3/bulk/issues/fields",
    headers: options?.headers,
    body: params,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Bulk move issues
 *
 * Use this API to submit a bulk issue move request. You can move multiple issues from multiple projects in a single request, but they must all be moved to a single project, issue type, and parent. You can't move more than 1000 issues (including subtasks) at once.
 *
 * #### Scenarios: ####
 *
 * This is an early version of the API and it doesn't have full feature parity with the Bulk Move UI experience.
 *
 *  *  Moving issue of type A to issue of type B in the same project or a different project: `SUPPORTED`
 *  *  Moving multiple issues of type A in one or more projects to multiple issues of type B in one of the source projects or a different project: `SUPPORTED`
 *  *  Moving issues of multiple issue types in one or more projects to issues of a single issue type in one of the source project or a different project: **`SUPPORTED`**
 *     E.g. Moving issues of story and task issue types in project 1 and project 2 to issues of task issue type in project 3
 *  *  Moving a standard parent issue of type A with its multiple subtask issue types in one project to standard issue of type B and multiple subtask issue types in the same project or a different project: `SUPPORTED`
 *  *  Moving standard issues with their subtasks to a parent issue in the same project or a different project without losing their relation: `SUPPORTED`
 *  *  Moving an epic issue with its child issues to a different project without losing their relation: `SUPPORTED`
 *     This usecase is **supported using multiple requests**. Move the epic in one request and then move the children in a separate request with target parent set to the epic issue id
 *
 *     (Alternatively, move them individually and stitch the relationship back with the Bulk Edit API)
 *
 * #### Limits applied to bulk issue moves: ####
 *
 * When using the bulk move, keep in mind that there are limits on the number of issues and fields you can include.
 *
 *  *  You can move up to 1,000 issues in a single operation, including any subtasks.
 *  *  The total combined number of fields across all issues must not exceed 1,500,000. For example, if each issue includes 15,000 fields, then the maximum number of issues that can be moved is 100.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
 *  *  Move [issues permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in source projects.
 *  *  Create [issues permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in destination projects.
 *  *  Browse [project permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in destination projects, if moving subtasks only.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *
 * @returns Returned if the request is successful.
 */
export function submitBulkMove(
  ctx: ClientContext,
  params: IssueBulkMovePayload,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<SubmittedBulkOperation> {
  return ctx.request({
    method: "post",
    path: "/rest/api/3/bulk/issues/move",
    headers: options?.headers,
    body: params,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get available transitions
 *
 * Use this API to retrieve a list of transitions available for the specified issues that can be used or bulk transition operations. You can submit either single or multiple issues in the query to obtain the available transitions.
 *
 * The response will provide the available transitions for issues, organized by their respective workflows. **Only the transitions that are common among the issues within that workflow and do not involve any additional field updates will be included.** For bulk transitions that require additional field updates, please utilise the Jira Cloud UI.
 *
 * You can request available transitions for up to 1,000 issues in a single operation. This API uses pagination to return responses, delivering 50 workflows at a time.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
 *  *  Transition [issues permission](https://support.atlassian.com/jira-cloud-administration/docs/permissions-for-company-managed-projects/#Transition-issues/) in all projects that contain the selected issues.
 *  *  Browse [project permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in all projects that contain the selected issues.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *
 * @param params.issueIdsOrKeys - Comma (,) separated Ids or keys of the issues to get transitions available for them.
 * @param params.endingBefore - (Optional)The end cursor for use in pagination.
 * @param params.startingAfter - (Optional)The start cursor for use in pagination.
 * @returns Returned if the request is successful.
 */
export function getAvailableTransitions(
  ctx: ClientContext,
  params: {
    /** Comma (,) separated Ids or keys of the issues to get transitions available for them. */
    issueIdsOrKeys: string;
    /** (Optional)The end cursor for use in pagination. */
    endingBefore?: string;
    /** (Optional)The start cursor for use in pagination. */
    startingAfter?: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<BulkTransitionGetAvailableTransitions> {
  const { issueIdsOrKeys, endingBefore, startingAfter } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/3/bulk/issues/transition",
    query: { issueIdsOrKeys, endingBefore, startingAfter },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Bulk transition issue statuses
 *
 * Use this API to submit a bulk issue status transition request. You can transition multiple issues, alongside with their valid transition Ids. You can transition up to 1,000 issues in a single operation.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
 *  *  Transition [issues permission](https://support.atlassian.com/jira-cloud-administration/docs/permissions-for-company-managed-projects/#Transition-issues/) in all projects that contain the selected issues.
 *  *  Browse [project permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in all projects that contain the selected issues.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *
 * @returns Returned if the request is successful.
 */
export function submitBulkTransition(
  ctx: ClientContext,
  params: IssueBulkTransitionPayload,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<SubmittedBulkOperation> {
  return ctx.request({
    method: "post",
    path: "/rest/api/3/bulk/issues/transition",
    headers: options?.headers,
    body: params,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Bulk unwatch issues
 *
 * Use this API to submit a bulk unwatch request. You can unwatch up to 1,000 issues in a single operation.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
 *  *  Browse [project permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in all projects that contain the selected issues.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *
 * @returns Returned if the request is successful.
 */
export function submitBulkUnwatch(
  ctx: ClientContext,
  params: IssueBulkWatchOrUnwatchPayload,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<SubmittedBulkOperation> {
  return ctx.request({
    method: "post",
    path: "/rest/api/3/bulk/issues/unwatch",
    headers: options?.headers,
    body: params,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Bulk watch issues
 *
 * Use this API to submit a bulk watch request. You can watch up to 1,000 issues in a single operation.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
 *  *  Browse [project permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in all projects that contain the selected issues.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *
 * @returns Returned if the request is successful.
 */
export function submitBulkWatch(
  ctx: ClientContext,
  params: IssueBulkWatchOrUnwatchPayload,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<SubmittedBulkOperation> {
  return ctx.request({
    method: "post",
    path: "/rest/api/3/bulk/issues/watch",
    headers: options?.headers,
    body: params,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get bulk issue operation progress
 *
 * Use this to get the progress state for the specified bulk operation `taskId`.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
 *
 * If the task is running, this resource will return:
 *
 *     {"taskId":"10779","status":"RUNNING","progressPercent":65,"submittedBy":{"accountId":"5b10a2844c20165700ede21g"},"created":1690180055963,"started":1690180056206,"updated":169018005829}
 *
 * If the task has completed, then this resource will return:
 *
 *     {"processedAccessibleIssues":[10001,10002],"created":1709189449954,"progressPercent":100,"started":1709189450154,"status":"COMPLETE","submittedBy":{"accountId":"5b10a2844c20165700ede21g"},"invalidOrInaccessibleIssueCount":0,"taskId":"10000","totalIssueCount":2,"updated":1709189450354}
 *
 * **Note:** You can view task progress for up to 14 days from creation.
 *
 * @param params.taskId - The ID of the task.
 * @returns Returned if the request is successful.
 */
export function getBulkOperationProgress(
  ctx: ClientContext,
  params: {
    /** The ID of the task. */
    taskId: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<BulkOperationProgress> {
  const { taskId } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/3/bulk/queue/{taskId}",
    pathParams: { taskId },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * This resource represents the issue bulk operations. Use it to move multiple issues from one project to another project or edit fields of multiple issues in one go.
 *
 *
 * For additional clarity, we have created a page with further examples and answers to frequently asked questions related to these APIs. You can access it here: [Bulk operation APIs: additional examples and FAQ](https://developer.atlassian.com/cloud/jira/platform/bulk-operation-additional-examples-and-faqs/).
 *
 * ### Authentication ###
 *
 * Access to the issue bulk operations requires authentication. For information on how to authenticate API requests, refer to the [Basic auth for REST APIs documentation](https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/).
 *
 * ### Rate limiting ###
 *
 * The bulk edit and move APIs are subject to the usual rate limiting infrastructure in Jira. For more information, refer to [Rate limiting](https://developer.atlassian.com/cloud/jira/platform/rate-limiting/). Additionally, at any given time, only 5 concurrent requests can be sent across all users.
 */
export function createIssueBulkOperationsService(ctx: ClientContext) {
  return {
    /**
     * Bulk delete issues
     *
     * Use this API to submit a bulk delete request. You can delete up to 1,000 issues in a single operation.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
     *  *  Delete [issues permission](https://support.atlassian.com/jira-cloud-administration/docs/permissions-for-company-managed-projects/#Delete-issues/) in all projects that contain the selected issues.
     *  *  Browse [project permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in all projects that contain the selected issues.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *
     * @returns Returned if the request is successful.
     */
    submitBulkDelete(
      params: IssueBulkDeletePayload,
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<SubmittedBulkOperation> {
      return submitBulkDelete(ctx, params, options);
    },

    /**
     * Get bulk editable fields
     *
     * Use this API to get a list of fields visible to the user to perform bulk edit operations. You can pass single or multiple issues in the query to get eligible editable fields. This API uses pagination to return responses, delivering 50 fields at a time.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
     *  *  Browse [project permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in all projects that contain the selected issues.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *  *  Depending on the field, any field-specific permissions required to edit it.
     *
     * @param params.issueIdsOrKeys - The IDs or keys of the issues to get editable fields from.
     * @param params.searchText - (Optional)The text to search for in the editable fields.
     * @param params.endingBefore - (Optional)The end cursor for use in pagination.
     * @param params.startingAfter - (Optional)The start cursor for use in pagination.
     * @returns Returned if the request is successful.
     */
    getBulkEditableFields(
      params: {
        /** The IDs or keys of the issues to get editable fields from. */
        issueIdsOrKeys: string;
        /** (Optional)The text to search for in the editable fields. */
        searchText?: string;
        /** (Optional)The end cursor for use in pagination. */
        endingBefore?: string;
        /** (Optional)The start cursor for use in pagination. */
        startingAfter?: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<BulkEditGetFields> {
      return getBulkEditableFields(ctx, params, options);
    },

    /**
     * Bulk edit issues
     *
     * Use this API to submit a bulk edit request and simultaneously edit multiple issues. There are limits applied to the number of issues and fields that can be edited. A single request can accommodate a maximum of 1000 issues (including subtasks) and 200 fields.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
     *  *  Browse [project permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in all projects that contain the selected issues.
     *  *  Edit [issues permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in all projects that contain the selected issues.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *
     * @returns Returned if the request is successful.
     */
    submitBulkEdit(
      params: IssueBulkEditPayload,
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<SubmittedBulkOperation> {
      return submitBulkEdit(ctx, params, options);
    },

    /**
     * Bulk move issues
     *
     * Use this API to submit a bulk issue move request. You can move multiple issues from multiple projects in a single request, but they must all be moved to a single project, issue type, and parent. You can't move more than 1000 issues (including subtasks) at once.
     *
     * #### Scenarios: ####
     *
     * This is an early version of the API and it doesn't have full feature parity with the Bulk Move UI experience.
     *
     *  *  Moving issue of type A to issue of type B in the same project or a different project: `SUPPORTED`
     *  *  Moving multiple issues of type A in one or more projects to multiple issues of type B in one of the source projects or a different project: `SUPPORTED`
     *  *  Moving issues of multiple issue types in one or more projects to issues of a single issue type in one of the source project or a different project: **`SUPPORTED`**
     *     E.g. Moving issues of story and task issue types in project 1 and project 2 to issues of task issue type in project 3
     *  *  Moving a standard parent issue of type A with its multiple subtask issue types in one project to standard issue of type B and multiple subtask issue types in the same project or a different project: `SUPPORTED`
     *  *  Moving standard issues with their subtasks to a parent issue in the same project or a different project without losing their relation: `SUPPORTED`
     *  *  Moving an epic issue with its child issues to a different project without losing their relation: `SUPPORTED`
     *     This usecase is **supported using multiple requests**. Move the epic in one request and then move the children in a separate request with target parent set to the epic issue id
     *
     *     (Alternatively, move them individually and stitch the relationship back with the Bulk Edit API)
     *
     * #### Limits applied to bulk issue moves: ####
     *
     * When using the bulk move, keep in mind that there are limits on the number of issues and fields you can include.
     *
     *  *  You can move up to 1,000 issues in a single operation, including any subtasks.
     *  *  The total combined number of fields across all issues must not exceed 1,500,000. For example, if each issue includes 15,000 fields, then the maximum number of issues that can be moved is 100.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
     *  *  Move [issues permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in source projects.
     *  *  Create [issues permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in destination projects.
     *  *  Browse [project permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in destination projects, if moving subtasks only.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *
     * @returns Returned if the request is successful.
     */
    submitBulkMove(
      params: IssueBulkMovePayload,
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<SubmittedBulkOperation> {
      return submitBulkMove(ctx, params, options);
    },

    /**
     * Get available transitions
     *
     * Use this API to retrieve a list of transitions available for the specified issues that can be used or bulk transition operations. You can submit either single or multiple issues in the query to obtain the available transitions.
     *
     * The response will provide the available transitions for issues, organized by their respective workflows. **Only the transitions that are common among the issues within that workflow and do not involve any additional field updates will be included.** For bulk transitions that require additional field updates, please utilise the Jira Cloud UI.
     *
     * You can request available transitions for up to 1,000 issues in a single operation. This API uses pagination to return responses, delivering 50 workflows at a time.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
     *  *  Transition [issues permission](https://support.atlassian.com/jira-cloud-administration/docs/permissions-for-company-managed-projects/#Transition-issues/) in all projects that contain the selected issues.
     *  *  Browse [project permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in all projects that contain the selected issues.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *
     * @param params.issueIdsOrKeys - Comma (,) separated Ids or keys of the issues to get transitions available for them.
     * @param params.endingBefore - (Optional)The end cursor for use in pagination.
     * @param params.startingAfter - (Optional)The start cursor for use in pagination.
     * @returns Returned if the request is successful.
     */
    getAvailableTransitions(
      params: {
        /** Comma (,) separated Ids or keys of the issues to get transitions available for them. */
        issueIdsOrKeys: string;
        /** (Optional)The end cursor for use in pagination. */
        endingBefore?: string;
        /** (Optional)The start cursor for use in pagination. */
        startingAfter?: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<BulkTransitionGetAvailableTransitions> {
      return getAvailableTransitions(ctx, params, options);
    },

    /**
     * Bulk transition issue statuses
     *
     * Use this API to submit a bulk issue status transition request. You can transition multiple issues, alongside with their valid transition Ids. You can transition up to 1,000 issues in a single operation.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
     *  *  Transition [issues permission](https://support.atlassian.com/jira-cloud-administration/docs/permissions-for-company-managed-projects/#Transition-issues/) in all projects that contain the selected issues.
     *  *  Browse [project permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in all projects that contain the selected issues.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *
     * @returns Returned if the request is successful.
     */
    submitBulkTransition(
      params: IssueBulkTransitionPayload,
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<SubmittedBulkOperation> {
      return submitBulkTransition(ctx, params, options);
    },

    /**
     * Bulk unwatch issues
     *
     * Use this API to submit a bulk unwatch request. You can unwatch up to 1,000 issues in a single operation.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
     *  *  Browse [project permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in all projects that contain the selected issues.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *
     * @returns Returned if the request is successful.
     */
    submitBulkUnwatch(
      params: IssueBulkWatchOrUnwatchPayload,
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<SubmittedBulkOperation> {
      return submitBulkUnwatch(ctx, params, options);
    },

    /**
     * Bulk watch issues
     *
     * Use this API to submit a bulk watch request. You can watch up to 1,000 issues in a single operation.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
     *  *  Browse [project permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/) in all projects that contain the selected issues.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *
     * @returns Returned if the request is successful.
     */
    submitBulkWatch(
      params: IssueBulkWatchOrUnwatchPayload,
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<SubmittedBulkOperation> {
      return submitBulkWatch(ctx, params, options);
    },

    /**
     * Get bulk issue operation progress
     *
     * Use this to get the progress state for the specified bulk operation `taskId`.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  Global bulk change [permission](https://support.atlassian.com/jira-cloud-administration/docs/manage-global-permissions/).
     *
     * If the task is running, this resource will return:
     *
     *     {"taskId":"10779","status":"RUNNING","progressPercent":65,"submittedBy":{"accountId":"5b10a2844c20165700ede21g"},"created":1690180055963,"started":1690180056206,"updated":169018005829}
     *
     * If the task has completed, then this resource will return:
     *
     *     {"processedAccessibleIssues":[10001,10002],"created":1709189449954,"progressPercent":100,"started":1709189450154,"status":"COMPLETE","submittedBy":{"accountId":"5b10a2844c20165700ede21g"},"invalidOrInaccessibleIssueCount":0,"taskId":"10000","totalIssueCount":2,"updated":1709189450354}
     *
     * **Note:** You can view task progress for up to 14 days from creation.
     *
     * @param params.taskId - The ID of the task.
     * @returns Returned if the request is successful.
     */
    getBulkOperationProgress(
      params: {
        /** The ID of the task. */
        taskId: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<BulkOperationProgress> {
      return getBulkOperationProgress(ctx, params, options);
    },
  };
}
