// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

import type { ClientContext } from "../../client/index.ts";
import type { ProjectEmailAddress } from "../types/index.ts";

/**
 * Get project's sender email
 *
 * Returns the [project's sender email address](https://confluence.atlassian.com/x/dolKLg).
 *
 * **[Permissions](#permissions) required:** *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
 *
 * @param params.projectId - The project ID.
 * @returns Returned if the request is successful.
 */
export function getProjectEmail(
  ctx: ClientContext,
  params: {
    /**
     * The project ID.
     *
     * @format int64
     */
    projectId: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<ProjectEmailAddress> {
  const { projectId } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/3/project/{projectId}/email",
    pathParams: { projectId },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Set project's sender email
 *
 * Sets the [project's sender email address](https://confluence.atlassian.com/x/dolKLg).
 *
 * If `emailAddress` is an empty string, the default email address is restored.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) or *Administer Projects* [project permission.](https://confluence.atlassian.com/x/yodKLg)
 *
 * @param params.projectId - The project ID.
 * @returns Returned if the project's sender email address is successfully set.
 */
export function updateProjectEmail(
  ctx: ClientContext,
  params: ProjectEmailAddress & {
    /**
     * The project ID.
     *
     * @format int64
     */
    projectId: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { projectId, ...body } = params;
  return ctx.request({
    method: "put",
    path: "/rest/api/3/project/{projectId}/email",
    pathParams: { projectId },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/** This resource represents the email address used to send a project's notifications. Use it to get and set the [project's sender email address](https://confluence.atlassian.com/x/dolKLg). */
export function createProjectEmailService(ctx: ClientContext) {
  return {
    /**
     * Get project's sender email
     *
     * Returns the [project's sender email address](https://confluence.atlassian.com/x/dolKLg).
     *
     * **[Permissions](#permissions) required:** *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
     *
     * @param params.projectId - The project ID.
     * @returns Returned if the request is successful.
     */
    getProjectEmail(
      params: {
        /**
         * The project ID.
         *
         * @format int64
         */
        projectId: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<ProjectEmailAddress> {
      return getProjectEmail(ctx, params, options);
    },

    /**
     * Set project's sender email
     *
     * Sets the [project's sender email address](https://confluence.atlassian.com/x/dolKLg).
     *
     * If `emailAddress` is an empty string, the default email address is restored.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) or *Administer Projects* [project permission.](https://confluence.atlassian.com/x/yodKLg)
     *
     * @param params.projectId - The project ID.
     * @returns Returned if the project's sender email address is successfully set.
     */
    updateProjectEmail(
      params: ProjectEmailAddress & {
        /**
         * The project ID.
         *
         * @format int64
         */
        projectId: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return updateProjectEmail(ctx, params, options);
    },
  };
}
