// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

import type { ClientContext } from "../../client/index.ts";
import type {
  PageBeanScreen,
  PageBeanScreenWithTab,
  Screen,
  ScreenDetails,
  ScreenableField,
  UpdateScreenDetails,
} from "../types/index.ts";

/**
 * Get screens for a field
 *
 * Returns a [paginated](#pagination) list of the screens a field is used in.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the field to return screens for.
 * @param params.startAt - The index of the first item to return in a page of results (page offset).
 * @param params.maxResults - The maximum number of items to return per page.
 * @param params.expand - Use [expand](#expansion) to include additional information about screens in the response. This parameter accepts `tab` which returns details about the screen tabs the field is used in.
 * @returns Returned if the request is successful.
 */
export function getScreensForField(
  ctx: ClientContext,
  params: {
    /** The ID of the field to return screens for. */
    fieldId: string;
    /**
     * The index of the first item to return in a page of results (page offset).
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of items to return per page.
     *
     * @default 100
     * @format int32
     */
    maxResults?: number;
    /** Use [expand](#expansion) to include additional information about screens in the response. This parameter accepts `tab` which returns details about the screen tabs the field is used in. */
    expand?: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBeanScreenWithTab> {
  const { fieldId, startAt, maxResults, expand } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/3/field/{fieldId}/screens",
    pathParams: { fieldId },
    query: { startAt, maxResults, expand },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get screens
 *
 * Returns a [paginated](#pagination) list of all screens or those specified by one or more screen IDs.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.startAt - The index of the first item to return in a page of results (page offset).
 * @param params.maxResults - The maximum number of items to return per page.
 * @param params.id - The list of screen IDs. To include multiple IDs, provide an ampersand-separated list. For example, `id=10000&id=10001`.
 * @param params.queryString - String used to perform a case-insensitive partial match with screen name.
 * @param params.scope - The scope filter string. To filter by multiple scope, provide an ampersand-separated list. For example, `scope=GLOBAL&scope=PROJECT`.
 * @param params.orderBy - [Order](#ordering) the results by a field: *  `id` Sorts by screen ID. *  `name` Sorts by screen name.
 * @returns Returned if the request is successful.
 */
export function getScreens(
  ctx: ClientContext,
  params?: {
    /**
     * The index of the first item to return in a page of results (page offset).
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of items to return per page.
     *
     * @default 100
     * @format int32
     */
    maxResults?: number;
    /** The list of screen IDs. To include multiple IDs, provide an ampersand-separated list. For example, `id=10000&id=10001`. */
    id?: number[];
    /**
     * String used to perform a case-insensitive partial match with screen name.
     *
     * @default ""
     */
    queryString?: string;
    /** The scope filter string. To filter by multiple scope, provide an ampersand-separated list. For example, `scope=GLOBAL&scope=PROJECT`. */
    scope?: ("GLOBAL" | "TEMPLATE" | "PROJECT")[];
    /**
     * [Order](#ordering) the results by a field:
     *
     *  *  `id` Sorts by screen ID.
     *  *  `name` Sorts by screen name.
     */
    orderBy?: "name" | "-name" | "+name" | "id" | "-id" | "+id";
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBeanScreen> {
  const { startAt, maxResults, id, queryString, scope, orderBy } = params ?? {};
  return ctx.request({
    method: "get",
    path: "/rest/api/3/screens",
    query: { startAt, maxResults, id, queryString, scope, orderBy },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Create screen
 *
 * Creates a screen with a default field tab.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @returns Returned if the request is successful.
 */
export function createScreen(
  ctx: ClientContext,
  params: ScreenDetails,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<Screen> {
  return ctx.request({
    method: "post",
    path: "/rest/api/3/screens",
    headers: options?.headers,
    body: params,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Add field to default screen
 *
 * Adds a field to the default tab of the default screen.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the field.
 * @returns Returned if the request is successful.
 */
export function addFieldToDefaultScreen(
  ctx: ClientContext,
  params: {
    /** The ID of the field. */
    fieldId: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { fieldId } = params;
  return ctx.request({
    method: "post",
    path: "/rest/api/3/screens/addToDefault/{fieldId}",
    pathParams: { fieldId },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Update screen
 *
 * Updates a screen. Only screens used in classic projects can be updated.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.screenId - The ID of the screen.
 * @returns Returned if the request is successful.
 */
export function updateScreen(
  ctx: ClientContext,
  params: UpdateScreenDetails & {
    /**
     * The ID of the screen.
     *
     * @format int64
     */
    screenId: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<Screen> {
  const { screenId, ...body } = params;
  return ctx.request({
    method: "put",
    path: "/rest/api/3/screens/{screenId}",
    pathParams: { screenId },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Delete screen
 *
 * Deletes a screen. A screen cannot be deleted if it is used in a screen scheme, workflow, or workflow draft.
 *
 * Only screens used in classic projects can be deleted.
 *
 * @param params.screenId - The ID of the screen.
 * @returns Returned if the request is successful.
 */
export function deleteScreen(
  ctx: ClientContext,
  params: {
    /**
     * The ID of the screen.
     *
     * @format int64
     */
    screenId: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<void> {
  const { screenId } = params;
  return ctx.request({
    method: "delete",
    path: "/rest/api/3/screens/{screenId}",
    pathParams: { screenId },
    headers: options?.headers,
    responseType: "void",
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get available screen fields
 *
 * Returns the fields that can be added to a tab on a screen.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.screenId - The ID of the screen.
 * @returns Returned if the request is successful.
 */
export function getAvailableScreenFields(
  ctx: ClientContext,
  params: {
    /**
     * The ID of the screen.
     *
     * @format int64
     */
    screenId: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<ScreenableField[]> {
  const { screenId } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/3/screens/{screenId}/availableFields",
    pathParams: { screenId },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * This resource represents the screens used to record issue details. Use it to:
 *
 *  *  get details of all screens.
 *  *  get details of all the fields available for use on screens.
 *  *  create screens.
 *  *  delete screens.
 *  *  update screens.
 *  *  add a field to the default screen.
 */
export function createScreensService(ctx: ClientContext) {
  return {
    /**
     * Get screens for a field
     *
     * Returns a [paginated](#pagination) list of the screens a field is used in.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the field to return screens for.
     * @param params.startAt - The index of the first item to return in a page of results (page offset).
     * @param params.maxResults - The maximum number of items to return per page.
     * @param params.expand - Use [expand](#expansion) to include additional information about screens in the response. This parameter accepts `tab` which returns details about the screen tabs the field is used in.
     * @returns Returned if the request is successful.
     */
    getScreensForField(
      params: {
        /** The ID of the field to return screens for. */
        fieldId: string;
        /**
         * The index of the first item to return in a page of results (page offset).
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of items to return per page.
         *
         * @default 100
         * @format int32
         */
        maxResults?: number;
        /** Use [expand](#expansion) to include additional information about screens in the response. This parameter accepts `tab` which returns details about the screen tabs the field is used in. */
        expand?: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBeanScreenWithTab> {
      return getScreensForField(ctx, params, options);
    },

    /**
     * Get screens
     *
     * Returns a [paginated](#pagination) list of all screens or those specified by one or more screen IDs.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.startAt - The index of the first item to return in a page of results (page offset).
     * @param params.maxResults - The maximum number of items to return per page.
     * @param params.id - The list of screen IDs. To include multiple IDs, provide an ampersand-separated list. For example, `id=10000&id=10001`.
     * @param params.queryString - String used to perform a case-insensitive partial match with screen name.
     * @param params.scope - The scope filter string. To filter by multiple scope, provide an ampersand-separated list. For example, `scope=GLOBAL&scope=PROJECT`.
     * @param params.orderBy - [Order](#ordering) the results by a field: *  `id` Sorts by screen ID. *  `name` Sorts by screen name.
     * @returns Returned if the request is successful.
     */
    getScreens(
      params?: {
        /**
         * The index of the first item to return in a page of results (page offset).
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of items to return per page.
         *
         * @default 100
         * @format int32
         */
        maxResults?: number;
        /** The list of screen IDs. To include multiple IDs, provide an ampersand-separated list. For example, `id=10000&id=10001`. */
        id?: number[];
        /**
         * String used to perform a case-insensitive partial match with screen name.
         *
         * @default ""
         */
        queryString?: string;
        /** The scope filter string. To filter by multiple scope, provide an ampersand-separated list. For example, `scope=GLOBAL&scope=PROJECT`. */
        scope?: ("GLOBAL" | "TEMPLATE" | "PROJECT")[];
        /**
         * [Order](#ordering) the results by a field:
         *
         *  *  `id` Sorts by screen ID.
         *  *  `name` Sorts by screen name.
         */
        orderBy?: "name" | "-name" | "+name" | "id" | "-id" | "+id";
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBeanScreen> {
      return getScreens(ctx, params, options);
    },

    /**
     * Create screen
     *
     * Creates a screen with a default field tab.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @returns Returned if the request is successful.
     */
    createScreen(
      params: ScreenDetails,
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<Screen> {
      return createScreen(ctx, params, options);
    },

    /**
     * Add field to default screen
     *
     * Adds a field to the default tab of the default screen.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the field.
     * @returns Returned if the request is successful.
     */
    addFieldToDefaultScreen(
      params: {
        /** The ID of the field. */
        fieldId: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return addFieldToDefaultScreen(ctx, params, options);
    },

    /**
     * Update screen
     *
     * Updates a screen. Only screens used in classic projects can be updated.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.screenId - The ID of the screen.
     * @returns Returned if the request is successful.
     */
    updateScreen(
      params: UpdateScreenDetails & {
        /**
         * The ID of the screen.
         *
         * @format int64
         */
        screenId: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<Screen> {
      return updateScreen(ctx, params, options);
    },

    /**
     * Delete screen
     *
     * Deletes a screen. A screen cannot be deleted if it is used in a screen scheme, workflow, or workflow draft.
     *
     * Only screens used in classic projects can be deleted.
     *
     * @param params.screenId - The ID of the screen.
     * @returns Returned if the request is successful.
     */
    deleteScreen(
      params: {
        /**
         * The ID of the screen.
         *
         * @format int64
         */
        screenId: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<void> {
      return deleteScreen(ctx, params, options);
    },

    /**
     * Get available screen fields
     *
     * Returns the fields that can be added to a tab on a screen.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.screenId - The ID of the screen.
     * @returns Returned if the request is successful.
     */
    getAvailableScreenFields(
      params: {
        /**
         * The ID of the screen.
         *
         * @format int64
         */
        screenId: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<ScreenableField[]> {
      return getAvailableScreenFields(ctx, params, options);
    },
  };
}
