// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

import type { ClientContext } from "../../client/index.ts";
import type {
  AvailableDashboardGadgetsResponse,
  BulkEditShareableEntityRequest,
  BulkEditShareableEntityResponse,
  Dashboard,
  DashboardDetails,
  DashboardGadget,
  DashboardGadgetResponse,
  DashboardGadgetSettings,
  DashboardGadgetUpdateRequest,
  EntityProperty,
  PageBeanDashboard,
  PageOfDashboards,
  PropertyKeys,
} from "../types/index.ts";

/**
 * Get all dashboards
 *
 * Returns a list of dashboards owned by or shared with the user. The list may be filtered to include only favorite or owned dashboards.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** None.
 *
 * @param params.filter - The filter applied to the list of dashboards. Valid values are: *  `favourite` Returns dashboards the user has marked as favorite. *  `my` Returns dashboards owned by the user.
 * @param params.startAt - The index of the first item to return in a page of results (page offset).
 * @param params.maxResults - The maximum number of items to return per page.
 * @returns Returned if the request is successful.
 */
export function getAllDashboards(
  ctx: ClientContext,
  params?: {
    /**
     * The filter applied to the list of dashboards. Valid values are:
     *
     *  *  `favourite` Returns dashboards the user has marked as favorite.
     *  *  `my` Returns dashboards owned by the user.
     */
    filter?: "my" | "favourite";
    /**
     * The index of the first item to return in a page of results (page offset).
     *
     * @default 0
     * @format int32
     */
    startAt?: number;
    /**
     * The maximum number of items to return per page.
     *
     * @default 20
     * @format int32
     */
    maxResults?: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageOfDashboards> {
  const { filter, startAt, maxResults } = params ?? {};
  return ctx.request({
    method: "get",
    path: "/rest/api/2/dashboard",
    query: { filter, startAt, maxResults },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Create dashboard
 *
 * Creates a dashboard.
 *
 * **[Permissions](#permissions) required:** None.
 *
 * @param params.extendAdminPermissions - Whether admin level permissions are used. It should only be true if the user has *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg)
 * @returns Returned if the request is successful.
 */
export function createDashboard(
  ctx: ClientContext,
  params: DashboardDetails & {
    /**
     * Whether admin level permissions are used. It should only be true if the user has *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg)
     *
     * @default false
     */
    extendAdminPermissions?: boolean;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<Dashboard> {
  const { extendAdminPermissions, ...body } = params;
  return ctx.request({
    method: "post",
    path: "/rest/api/2/dashboard",
    query: { extendAdminPermissions },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Bulk edit dashboards
 *
 * Bulk edit dashboards. Maximum number of dashboards to be edited at the same time is 100.
 *
 * **[Permissions](#permissions) required:** None
 *
 * The dashboards to be updated must be owned by the user, or the user must be an administrator.
 *
 * @returns Returned if the request is successful.
 */
export function bulkEditDashboards(
  ctx: ClientContext,
  params: BulkEditShareableEntityRequest,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<BulkEditShareableEntityResponse> {
  return ctx.request({
    method: "put",
    path: "/rest/api/2/dashboard/bulk/edit",
    headers: options?.headers,
    body: params,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get available gadgets
 *
 * Gets a list of all available gadgets that can be added to all dashboards.
 *
 * **[Permissions](#permissions) required:** None.
 *
 * @returns Returned if the request is successful.
 */
export function getAllAvailableDashboardGadgets(
  ctx: ClientContext,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<AvailableDashboardGadgetsResponse> {
  return ctx.request({
    method: "get",
    path: "/rest/api/2/dashboard/gadgets",
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Search for dashboards
 *
 * Returns a [paginated](#pagination) list of dashboards. This operation is similar to [Get dashboards](#api-rest-api-2-dashboard-get) except that the results can be refined to include dashboards that have specific attributes. For example, dashboards with a particular name. When multiple attributes are specified only filters matching all attributes are returned.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** The following dashboards that match the query parameters are returned:
 *
 *  *  Dashboards owned by the user. Not returned for anonymous users.
 *  *  Dashboards shared with a group that the user is a member of. Not returned for anonymous users.
 *  *  Dashboards shared with a private project that the user can browse. Not returned for anonymous users.
 *  *  Dashboards shared with a public project.
 *  *  Dashboards shared with the public.
 *
 * @param params.dashboardName - String used to perform a case-insensitive partial match with `name`.
 * @param params.accountId - User account ID used to return dashboards with the matching `owner.accountId`. This parameter cannot be used with the `owner` parameter.
 * @param params.owner - This parameter is deprecated because of privacy changes. Use `accountId` instead. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. User name used to return dashboards with the matching `owner.name`. This parameter cannot be used with the `accountId` parameter.
 * @param params.groupname - As a group's name can change, use of `groupId` is recommended. Group name used to return dashboards that are shared with a group that matches `sharePermissions.group.name`. This parameter cannot be used with the `groupId` parameter.
 * @param params.groupId - Group ID used to return dashboards that are shared with a group that matches `sharePermissions.group.groupId`. This parameter cannot be used with the `groupname` parameter.
 * @param params.projectId - Project ID used to returns dashboards that are shared with a project that matches `sharePermissions.project.id`.
 * @param params.orderBy - [Order](#ordering) the results by a field: *  `description` Sorts by dashboard description. Note that this sort works independently of whether the expand to display the description field is in use. *  `favourite_count` Sorts by dashboard popularity. *  `id` Sorts by dashboard ID. *  `is_favourite` Sorts by whether the dashboard is marked as a favorite. *  `name` Sorts by dashboard name. *  `owner` Sorts by dashboard owner name.
 * @param params.startAt - The index of the first item to return in a page of results (page offset).
 * @param params.maxResults - The maximum number of items to return per page.
 * @param params.status - The status to filter by. It may be active, archived or deleted.
 * @param params.expand - Use [expand](#expansion) to include additional information about dashboard in the response. This parameter accepts a comma-separated list. Expand options include: *  `description` Returns the description of the dashboard. *  `owner` Returns the owner of the dashboard. *  `viewUrl` Returns the URL that is used to view the dashboard. *  `favourite` Returns `isFavourite`, an indicator of whether the user has set the dashboard as a favorite. *  `favouritedCount` Returns `popularity`, a count of how many users have set this dashboard as a favorite. *  `sharePermissions` Returns details of the share permissions defined for the dashboard. *  `editPermissions` Returns details of the edit permissions defined for the dashboard. *  `isWritable` Returns whether the current user has permission to edit the dashboard.
 * @returns Returned if the request is successful.
 */
export function getDashboardsPaginated(
  ctx: ClientContext,
  params?: {
    /** String used to perform a case-insensitive partial match with `name`. */
    dashboardName?: string;
    /** User account ID used to return dashboards with the matching `owner.accountId`. This parameter cannot be used with the `owner` parameter. */
    accountId?: string;
    /** This parameter is deprecated because of privacy changes. Use `accountId` instead. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. User name used to return dashboards with the matching `owner.name`. This parameter cannot be used with the `accountId` parameter. */
    owner?: string;
    /** As a group's name can change, use of `groupId` is recommended. Group name used to return dashboards that are shared with a group that matches `sharePermissions.group.name`. This parameter cannot be used with the `groupId` parameter. */
    groupname?: string;
    /** Group ID used to return dashboards that are shared with a group that matches `sharePermissions.group.groupId`. This parameter cannot be used with the `groupname` parameter. */
    groupId?: string;
    /**
     * Project ID used to returns dashboards that are shared with a project that matches `sharePermissions.project.id`.
     *
     * @format int64
     */
    projectId?: number;
    /**
     * [Order](#ordering) the results by a field:
     *
     *  *  `description` Sorts by dashboard description. Note that this sort works independently of whether the expand to display the description field is in use.
     *  *  `favourite_count` Sorts by dashboard popularity.
     *  *  `id` Sorts by dashboard ID.
     *  *  `is_favourite` Sorts by whether the dashboard is marked as a favorite.
     *  *  `name` Sorts by dashboard name.
     *  *  `owner` Sorts by dashboard owner name.
     *
     * @default "name"
     */
    orderBy?:
      | "description"
      | "-description"
      | "+description"
      | "favorite_count"
      | "-favorite_count"
      | "+favorite_count"
      | "id"
      | "-id"
      | "+id"
      | "is_favorite"
      | "-is_favorite"
      | "+is_favorite"
      | "name"
      | "-name"
      | "+name"
      | "owner"
      | "-owner"
      | "+owner";
    /**
     * The index of the first item to return in a page of results (page offset).
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of items to return per page.
     *
     * @default 50
     * @format int32
     */
    maxResults?: number;
    /**
     * The status to filter by. It may be active, archived or deleted.
     *
     * @default "active"
     */
    status?: "active" | "archived" | "deleted";
    /**
     * Use [expand](#expansion) to include additional information about dashboard in the response. This parameter accepts a comma-separated list. Expand options include:
     *
     *  *  `description` Returns the description of the dashboard.
     *  *  `owner` Returns the owner of the dashboard.
     *  *  `viewUrl` Returns the URL that is used to view the dashboard.
     *  *  `favourite` Returns `isFavourite`, an indicator of whether the user has set the dashboard as a favorite.
     *  *  `favouritedCount` Returns `popularity`, a count of how many users have set this dashboard as a favorite.
     *  *  `sharePermissions` Returns details of the share permissions defined for the dashboard.
     *  *  `editPermissions` Returns details of the edit permissions defined for the dashboard.
     *  *  `isWritable` Returns whether the current user has permission to edit the dashboard.
     */
    expand?: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBeanDashboard> {
  const {
    dashboardName,
    accountId,
    owner,
    groupname,
    groupId,
    projectId,
    orderBy,
    startAt,
    maxResults,
    status,
    expand,
  } = params ?? {};
  return ctx.request({
    method: "get",
    path: "/rest/api/2/dashboard/search",
    query: {
      dashboardName,
      accountId,
      owner,
      groupname,
      groupId,
      projectId,
      orderBy,
      startAt,
      maxResults,
      status,
      expand,
    },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get gadgets
 *
 * Returns a list of dashboard gadgets on a dashboard.
 *
 * This operation returns:
 *
 *  *  Gadgets from a list of IDs, when `id` is set.
 *  *  Gadgets with a module key, when `moduleKey` is set.
 *  *  Gadgets from a list of URIs, when `uri` is set.
 *  *  All gadgets, when no other parameters are set.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** None.
 *
 * @param params.dashboardId - The ID of the dashboard.
 * @param params.moduleKey - The list of gadgets module keys. To include multiple module keys, separate module keys with ampersand: `moduleKey=key:one&moduleKey=key:two`.
 * @param params.uri - The list of gadgets URIs. To include multiple URIs, separate URIs with ampersand: `uri=/rest/example/uri/1&uri=/rest/example/uri/2`.
 * @param params.gadgetId - The list of gadgets IDs. To include multiple IDs, separate IDs with ampersand: `gadgetId=10000&gadgetId=10001`.
 * @returns Returned if the request is successful.
 */
export function getAllGadgets(
  ctx: ClientContext,
  params: {
    /**
     * The ID of the dashboard.
     *
     * @format int64
     */
    dashboardId: number;
    /** The list of gadgets module keys. To include multiple module keys, separate module keys with ampersand: `moduleKey=key:one&moduleKey=key:two`. */
    moduleKey?: string[];
    /** The list of gadgets URIs. To include multiple URIs, separate URIs with ampersand: `uri=/rest/example/uri/1&uri=/rest/example/uri/2`. */
    uri?: string[];
    /** The list of gadgets IDs. To include multiple IDs, separate IDs with ampersand: `gadgetId=10000&gadgetId=10001`. */
    gadgetId?: number[];
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<DashboardGadgetResponse> {
  const { dashboardId, moduleKey, uri, gadgetId } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/dashboard/{dashboardId}/gadget",
    pathParams: { dashboardId },
    query: { moduleKey, uri, gadgetId },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Add gadget to dashboard
 *
 * Adds a gadget to a dashboard.
 *
 * **[Permissions](#permissions) required:** None.
 *
 * @param params.dashboardId - The ID of the dashboard.
 * @returns Returned if the request is successful.
 */
export function addGadget(
  ctx: ClientContext,
  params: DashboardGadgetSettings & {
    /**
     * The ID of the dashboard.
     *
     * @format int64
     */
    dashboardId: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<DashboardGadget> {
  const { dashboardId, ...body } = params;
  return ctx.request({
    method: "post",
    path: "/rest/api/2/dashboard/{dashboardId}/gadget",
    pathParams: { dashboardId },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Update gadget on dashboard
 *
 * Changes the title, position, and color of the gadget on a dashboard.
 *
 * **[Permissions](#permissions) required:** None.
 *
 * @param params.dashboardId - The ID of the dashboard.
 * @param params.gadgetId - The ID of the gadget.
 * @returns Returned if the request is successful.
 */
export function updateGadget(
  ctx: ClientContext,
  params: DashboardGadgetUpdateRequest & {
    /**
     * The ID of the dashboard.
     *
     * @format int64
     */
    dashboardId: number;
    /**
     * The ID of the gadget.
     *
     * @format int64
     */
    gadgetId: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { dashboardId, gadgetId, ...body } = params;
  return ctx.request({
    method: "put",
    path: "/rest/api/2/dashboard/{dashboardId}/gadget/{gadgetId}",
    pathParams: { dashboardId, gadgetId },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Remove gadget from dashboard
 *
 * Removes a dashboard gadget from a dashboard.
 *
 * When a gadget is removed from a dashboard, other gadgets in the same column are moved up to fill the emptied position.
 *
 * **[Permissions](#permissions) required:** None.
 *
 * @param params.dashboardId - The ID of the dashboard.
 * @param params.gadgetId - The ID of the gadget.
 * @returns Returned if the request is successful.
 */
export function removeGadget(
  ctx: ClientContext,
  params: {
    /**
     * The ID of the dashboard.
     *
     * @format int64
     */
    dashboardId: number;
    /**
     * The ID of the gadget.
     *
     * @format int64
     */
    gadgetId: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { dashboardId, gadgetId } = params;
  return ctx.request({
    method: "delete",
    path: "/rest/api/2/dashboard/{dashboardId}/gadget/{gadgetId}",
    pathParams: { dashboardId, gadgetId },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get dashboard item property keys
 *
 * Returns the keys of all properties for a dashboard item.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** The user must have read permission of the dashboard or have the dashboard shared with them.
 *
 * @param params.dashboardId - The ID of the dashboard.
 * @param params.itemId - The ID of the dashboard item.
 * @returns Returned if the request is successful.
 */
export function getDashboardItemPropertyKeys(
  ctx: ClientContext,
  params: {
    /** The ID of the dashboard. */
    dashboardId: string;
    /** The ID of the dashboard item. */
    itemId: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PropertyKeys> {
  const { dashboardId, itemId } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/dashboard/{dashboardId}/items/{itemId}/properties",
    pathParams: { dashboardId, itemId },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get dashboard item property
 *
 * Returns the key and value of a dashboard item property.
 *
 * A dashboard item enables an app to add user-specific information to a user dashboard. Dashboard items are exposed to users as gadgets that users can add to their dashboards. For more information on how users do this, see [Adding and customizing gadgets](https://confluence.atlassian.com/x/7AeiLQ).
 *
 * When an app creates a dashboard item it registers a callback to receive the dashboard item ID. The callback fires whenever the item is rendered or, where the item is configurable, the user edits the item. The app then uses this resource to store the item's content or configuration details. For more information on working with dashboard items, see [ Building a dashboard item for a JIRA Connect add-on](https://developer.atlassian.com/server/jira/platform/guide-building-a-dashboard-item-for-a-jira-connect-add-on-33746254/) and the [Dashboard Item](https://developer.atlassian.com/cloud/jira/platform/modules/dashboard-item/) documentation.
 *
 * There is no resource to set or get dashboard items.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** The user must have read permission of the dashboard or have the dashboard shared with them.
 *
 * @param params.dashboardId - The ID of the dashboard.
 * @param params.itemId - The ID of the dashboard item.
 * @param params.propertyKey - The key of the dashboard item property.
 * @returns Returned if the request is successful.
 */
export function getDashboardItemProperty(
  ctx: ClientContext,
  params: {
    /** The ID of the dashboard. */
    dashboardId: string;
    /** The ID of the dashboard item. */
    itemId: string;
    /** The key of the dashboard item property. */
    propertyKey: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<EntityProperty> {
  const { dashboardId, itemId, propertyKey } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}",
    pathParams: { dashboardId, itemId, propertyKey },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Set dashboard item property
 *
 * Sets the value of a dashboard item property. Use this resource in apps to store custom data against a dashboard item.
 *
 * A dashboard item enables an app to add user-specific information to a user dashboard. Dashboard items are exposed to users as gadgets that users can add to their dashboards. For more information on how users do this, see [Adding and customizing gadgets](https://confluence.atlassian.com/x/7AeiLQ).
 *
 * When an app creates a dashboard item it registers a callback to receive the dashboard item ID. The callback fires whenever the item is rendered or, where the item is configurable, the user edits the item. The app then uses this resource to store the item's content or configuration details. For more information on working with dashboard items, see [ Building a dashboard item for a JIRA Connect add-on](https://developer.atlassian.com/server/jira/platform/guide-building-a-dashboard-item-for-a-jira-connect-add-on-33746254/) and the [Dashboard Item](https://developer.atlassian.com/cloud/jira/platform/modules/dashboard-item/) documentation.
 *
 * There is no resource to set or get dashboard items.
 *
 * The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** The user must have edit permisson of the dashboard.
 *
 * @param params.dashboardId - The ID of the dashboard.
 * @param params.itemId - The ID of the dashboard item.
 * @param params.propertyKey - The key of the dashboard item property. The maximum length is 255 characters. For dashboard items with a spec URI and no complete module key, if the provided propertyKey is equal to "config", the request body's JSON must be an object with all keys and values as strings.
 * @param params.body - The value of the property. The value has to be a valid, non-empty [JSON](https://tools.ietf.org/html/rfc4627) value. The maximum length of the property value is 32768 bytes.
 * @returns Returned if the dashboard item property is updated.
 */
export function setDashboardItemProperty(
  ctx: ClientContext,
  params: {
    /** The ID of the dashboard. */
    dashboardId: string;
    /** The ID of the dashboard item. */
    itemId: string;
    /** The key of the dashboard item property. The maximum length is 255 characters. For dashboard items with a spec URI and no complete module key, if the provided propertyKey is equal to "config", the request body's JSON must be an object with all keys and values as strings. */
    propertyKey: string;
    body: unknown;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { dashboardId, itemId, propertyKey, body } = params;
  return ctx.request({
    method: "put",
    path: "/rest/api/2/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}",
    pathParams: { dashboardId, itemId, propertyKey },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Delete dashboard item property
 *
 * Deletes a dashboard item property.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** The user must have edit permission of the dashboard.
 *
 * @param params.dashboardId - The ID of the dashboard.
 * @param params.itemId - The ID of the dashboard item.
 * @param params.propertyKey - The key of the dashboard item property.
 * @returns Returned if the dashboard item property is deleted.
 */
export function deleteDashboardItemProperty(
  ctx: ClientContext,
  params: {
    /** The ID of the dashboard. */
    dashboardId: string;
    /** The ID of the dashboard item. */
    itemId: string;
    /** The key of the dashboard item property. */
    propertyKey: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { dashboardId, itemId, propertyKey } = params;
  return ctx.request({
    method: "delete",
    path: "/rest/api/2/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}",
    pathParams: { dashboardId, itemId, propertyKey },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get dashboard
 *
 * Returns a dashboard.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** None.
 *
 * However, to get a dashboard, the dashboard must be shared with the user or the user must own it. Note, users with the *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) are considered owners of the System dashboard. The System dashboard is considered to be shared with all other users.
 *
 * @param params.id - The ID of the dashboard.
 * @returns Returned if the request is successful.
 */
export function getDashboard(
  ctx: ClientContext,
  params: {
    /** The ID of the dashboard. */
    id: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<Dashboard> {
  const { id } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/dashboard/{id}",
    pathParams: { id },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Update dashboard
 *
 * Updates a dashboard, replacing all the dashboard details with those provided.
 *
 * **[Permissions](#permissions) required:** None
 *
 * The dashboard to be updated must be owned by the user.
 *
 * @param params.id - The ID of the dashboard to update.
 * @param params.extendAdminPermissions - Whether admin level permissions are used. It should only be true if the user has *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg)
 * @returns Returned if the request is successful.
 */
export function updateDashboard(
  ctx: ClientContext,
  params: DashboardDetails & {
    /** The ID of the dashboard to update. */
    id: string;
    /**
     * Whether admin level permissions are used. It should only be true if the user has *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg)
     *
     * @default false
     */
    extendAdminPermissions?: boolean;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<Dashboard> {
  const { id, extendAdminPermissions, ...body } = params;
  return ctx.request({
    method: "put",
    path: "/rest/api/2/dashboard/{id}",
    pathParams: { id },
    query: { extendAdminPermissions },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Delete dashboard
 *
 * Deletes a dashboard.
 *
 * **[Permissions](#permissions) required:** None
 *
 * The dashboard to be deleted must be owned by the user.
 *
 * @param params.id - The ID of the dashboard.
 * @returns Returned if the dashboard is deleted.
 */
export function deleteDashboard(
  ctx: ClientContext,
  params: {
    /** The ID of the dashboard. */
    id: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<void> {
  const { id } = params;
  return ctx.request({
    method: "delete",
    path: "/rest/api/2/dashboard/{id}",
    pathParams: { id },
    headers: options?.headers,
    responseType: "void",
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Copy dashboard
 *
 * Copies a dashboard. Any values provided in the `dashboard` parameter replace those in the copied dashboard.
 *
 * **[Permissions](#permissions) required:** None
 *
 * The dashboard to be copied must be owned by or shared with the user.
 *
 * @param params.extendAdminPermissions - Whether admin level permissions are used. It should only be true if the user has *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg)
 * @returns Returned if the request is successful.
 */
export function copyDashboard(
  ctx: ClientContext,
  params: DashboardDetails & {
    id: string;
    /**
     * Whether admin level permissions are used. It should only be true if the user has *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg)
     *
     * @default false
     */
    extendAdminPermissions?: boolean;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<Dashboard> {
  const { id, extendAdminPermissions, ...body } = params;
  return ctx.request({
    method: "post",
    path: "/rest/api/2/dashboard/{id}/copy",
    pathParams: { id },
    query: { extendAdminPermissions },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/** This resource represents dashboards. Use it to obtain the details of dashboards as well as get, create, update, or remove item properties and gadgets from dashboards. */
export function createDashboardsService(ctx: ClientContext) {
  return {
    /**
     * Get all dashboards
     *
     * Returns a list of dashboards owned by or shared with the user. The list may be filtered to include only favorite or owned dashboards.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** None.
     *
     * @param params.filter - The filter applied to the list of dashboards. Valid values are: *  `favourite` Returns dashboards the user has marked as favorite. *  `my` Returns dashboards owned by the user.
     * @param params.startAt - The index of the first item to return in a page of results (page offset).
     * @param params.maxResults - The maximum number of items to return per page.
     * @returns Returned if the request is successful.
     */
    getAllDashboards(
      params?: {
        /**
         * The filter applied to the list of dashboards. Valid values are:
         *
         *  *  `favourite` Returns dashboards the user has marked as favorite.
         *  *  `my` Returns dashboards owned by the user.
         */
        filter?: "my" | "favourite";
        /**
         * The index of the first item to return in a page of results (page offset).
         *
         * @default 0
         * @format int32
         */
        startAt?: number;
        /**
         * The maximum number of items to return per page.
         *
         * @default 20
         * @format int32
         */
        maxResults?: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageOfDashboards> {
      return getAllDashboards(ctx, params, options);
    },

    /**
     * Create dashboard
     *
     * Creates a dashboard.
     *
     * **[Permissions](#permissions) required:** None.
     *
     * @param params.extendAdminPermissions - Whether admin level permissions are used. It should only be true if the user has *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg)
     * @returns Returned if the request is successful.
     */
    createDashboard(
      params: DashboardDetails & {
        /**
         * Whether admin level permissions are used. It should only be true if the user has *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg)
         *
         * @default false
         */
        extendAdminPermissions?: boolean;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<Dashboard> {
      return createDashboard(ctx, params, options);
    },

    /**
     * Bulk edit dashboards
     *
     * Bulk edit dashboards. Maximum number of dashboards to be edited at the same time is 100.
     *
     * **[Permissions](#permissions) required:** None
     *
     * The dashboards to be updated must be owned by the user, or the user must be an administrator.
     *
     * @returns Returned if the request is successful.
     */
    bulkEditDashboards(
      params: BulkEditShareableEntityRequest,
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<BulkEditShareableEntityResponse> {
      return bulkEditDashboards(ctx, params, options);
    },

    /**
     * Get available gadgets
     *
     * Gets a list of all available gadgets that can be added to all dashboards.
     *
     * **[Permissions](#permissions) required:** None.
     *
     * @returns Returned if the request is successful.
     */
    getAllAvailableDashboardGadgets(options?: {
      headers?: Record<string, string | number | boolean>;
      signal?: AbortSignal;
      extensions?: Record<string, unknown>;
    }): Promise<AvailableDashboardGadgetsResponse> {
      return getAllAvailableDashboardGadgets(ctx, options);
    },

    /**
     * Search for dashboards
     *
     * Returns a [paginated](#pagination) list of dashboards. This operation is similar to [Get dashboards](#api-rest-api-2-dashboard-get) except that the results can be refined to include dashboards that have specific attributes. For example, dashboards with a particular name. When multiple attributes are specified only filters matching all attributes are returned.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** The following dashboards that match the query parameters are returned:
     *
     *  *  Dashboards owned by the user. Not returned for anonymous users.
     *  *  Dashboards shared with a group that the user is a member of. Not returned for anonymous users.
     *  *  Dashboards shared with a private project that the user can browse. Not returned for anonymous users.
     *  *  Dashboards shared with a public project.
     *  *  Dashboards shared with the public.
     *
     * @param params.dashboardName - String used to perform a case-insensitive partial match with `name`.
     * @param params.accountId - User account ID used to return dashboards with the matching `owner.accountId`. This parameter cannot be used with the `owner` parameter.
     * @param params.owner - This parameter is deprecated because of privacy changes. Use `accountId` instead. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. User name used to return dashboards with the matching `owner.name`. This parameter cannot be used with the `accountId` parameter.
     * @param params.groupname - As a group's name can change, use of `groupId` is recommended. Group name used to return dashboards that are shared with a group that matches `sharePermissions.group.name`. This parameter cannot be used with the `groupId` parameter.
     * @param params.groupId - Group ID used to return dashboards that are shared with a group that matches `sharePermissions.group.groupId`. This parameter cannot be used with the `groupname` parameter.
     * @param params.projectId - Project ID used to returns dashboards that are shared with a project that matches `sharePermissions.project.id`.
     * @param params.orderBy - [Order](#ordering) the results by a field: *  `description` Sorts by dashboard description. Note that this sort works independently of whether the expand to display the description field is in use. *  `favourite_count` Sorts by dashboard popularity. *  `id` Sorts by dashboard ID. *  `is_favourite` Sorts by whether the dashboard is marked as a favorite. *  `name` Sorts by dashboard name. *  `owner` Sorts by dashboard owner name.
     * @param params.startAt - The index of the first item to return in a page of results (page offset).
     * @param params.maxResults - The maximum number of items to return per page.
     * @param params.status - The status to filter by. It may be active, archived or deleted.
     * @param params.expand - Use [expand](#expansion) to include additional information about dashboard in the response. This parameter accepts a comma-separated list. Expand options include: *  `description` Returns the description of the dashboard. *  `owner` Returns the owner of the dashboard. *  `viewUrl` Returns the URL that is used to view the dashboard. *  `favourite` Returns `isFavourite`, an indicator of whether the user has set the dashboard as a favorite. *  `favouritedCount` Returns `popularity`, a count of how many users have set this dashboard as a favorite. *  `sharePermissions` Returns details of the share permissions defined for the dashboard. *  `editPermissions` Returns details of the edit permissions defined for the dashboard. *  `isWritable` Returns whether the current user has permission to edit the dashboard.
     * @returns Returned if the request is successful.
     */
    getDashboardsPaginated(
      params?: {
        /** String used to perform a case-insensitive partial match with `name`. */
        dashboardName?: string;
        /** User account ID used to return dashboards with the matching `owner.accountId`. This parameter cannot be used with the `owner` parameter. */
        accountId?: string;
        /** This parameter is deprecated because of privacy changes. Use `accountId` instead. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. User name used to return dashboards with the matching `owner.name`. This parameter cannot be used with the `accountId` parameter. */
        owner?: string;
        /** As a group's name can change, use of `groupId` is recommended. Group name used to return dashboards that are shared with a group that matches `sharePermissions.group.name`. This parameter cannot be used with the `groupId` parameter. */
        groupname?: string;
        /** Group ID used to return dashboards that are shared with a group that matches `sharePermissions.group.groupId`. This parameter cannot be used with the `groupname` parameter. */
        groupId?: string;
        /**
         * Project ID used to returns dashboards that are shared with a project that matches `sharePermissions.project.id`.
         *
         * @format int64
         */
        projectId?: number;
        /**
         * [Order](#ordering) the results by a field:
         *
         *  *  `description` Sorts by dashboard description. Note that this sort works independently of whether the expand to display the description field is in use.
         *  *  `favourite_count` Sorts by dashboard popularity.
         *  *  `id` Sorts by dashboard ID.
         *  *  `is_favourite` Sorts by whether the dashboard is marked as a favorite.
         *  *  `name` Sorts by dashboard name.
         *  *  `owner` Sorts by dashboard owner name.
         *
         * @default "name"
         */
        orderBy?:
          | "description"
          | "-description"
          | "+description"
          | "favorite_count"
          | "-favorite_count"
          | "+favorite_count"
          | "id"
          | "-id"
          | "+id"
          | "is_favorite"
          | "-is_favorite"
          | "+is_favorite"
          | "name"
          | "-name"
          | "+name"
          | "owner"
          | "-owner"
          | "+owner";
        /**
         * The index of the first item to return in a page of results (page offset).
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of items to return per page.
         *
         * @default 50
         * @format int32
         */
        maxResults?: number;
        /**
         * The status to filter by. It may be active, archived or deleted.
         *
         * @default "active"
         */
        status?: "active" | "archived" | "deleted";
        /**
         * Use [expand](#expansion) to include additional information about dashboard in the response. This parameter accepts a comma-separated list. Expand options include:
         *
         *  *  `description` Returns the description of the dashboard.
         *  *  `owner` Returns the owner of the dashboard.
         *  *  `viewUrl` Returns the URL that is used to view the dashboard.
         *  *  `favourite` Returns `isFavourite`, an indicator of whether the user has set the dashboard as a favorite.
         *  *  `favouritedCount` Returns `popularity`, a count of how many users have set this dashboard as a favorite.
         *  *  `sharePermissions` Returns details of the share permissions defined for the dashboard.
         *  *  `editPermissions` Returns details of the edit permissions defined for the dashboard.
         *  *  `isWritable` Returns whether the current user has permission to edit the dashboard.
         */
        expand?: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBeanDashboard> {
      return getDashboardsPaginated(ctx, params, options);
    },

    /**
     * Get gadgets
     *
     * Returns a list of dashboard gadgets on a dashboard.
     *
     * This operation returns:
     *
     *  *  Gadgets from a list of IDs, when `id` is set.
     *  *  Gadgets with a module key, when `moduleKey` is set.
     *  *  Gadgets from a list of URIs, when `uri` is set.
     *  *  All gadgets, when no other parameters are set.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** None.
     *
     * @param params.dashboardId - The ID of the dashboard.
     * @param params.moduleKey - The list of gadgets module keys. To include multiple module keys, separate module keys with ampersand: `moduleKey=key:one&moduleKey=key:two`.
     * @param params.uri - The list of gadgets URIs. To include multiple URIs, separate URIs with ampersand: `uri=/rest/example/uri/1&uri=/rest/example/uri/2`.
     * @param params.gadgetId - The list of gadgets IDs. To include multiple IDs, separate IDs with ampersand: `gadgetId=10000&gadgetId=10001`.
     * @returns Returned if the request is successful.
     */
    getAllGadgets(
      params: {
        /**
         * The ID of the dashboard.
         *
         * @format int64
         */
        dashboardId: number;
        /** The list of gadgets module keys. To include multiple module keys, separate module keys with ampersand: `moduleKey=key:one&moduleKey=key:two`. */
        moduleKey?: string[];
        /** The list of gadgets URIs. To include multiple URIs, separate URIs with ampersand: `uri=/rest/example/uri/1&uri=/rest/example/uri/2`. */
        uri?: string[];
        /** The list of gadgets IDs. To include multiple IDs, separate IDs with ampersand: `gadgetId=10000&gadgetId=10001`. */
        gadgetId?: number[];
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<DashboardGadgetResponse> {
      return getAllGadgets(ctx, params, options);
    },

    /**
     * Add gadget to dashboard
     *
     * Adds a gadget to a dashboard.
     *
     * **[Permissions](#permissions) required:** None.
     *
     * @param params.dashboardId - The ID of the dashboard.
     * @returns Returned if the request is successful.
     */
    addGadget(
      params: DashboardGadgetSettings & {
        /**
         * The ID of the dashboard.
         *
         * @format int64
         */
        dashboardId: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<DashboardGadget> {
      return addGadget(ctx, params, options);
    },

    /**
     * Update gadget on dashboard
     *
     * Changes the title, position, and color of the gadget on a dashboard.
     *
     * **[Permissions](#permissions) required:** None.
     *
     * @param params.dashboardId - The ID of the dashboard.
     * @param params.gadgetId - The ID of the gadget.
     * @returns Returned if the request is successful.
     */
    updateGadget(
      params: DashboardGadgetUpdateRequest & {
        /**
         * The ID of the dashboard.
         *
         * @format int64
         */
        dashboardId: number;
        /**
         * The ID of the gadget.
         *
         * @format int64
         */
        gadgetId: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return updateGadget(ctx, params, options);
    },

    /**
     * Remove gadget from dashboard
     *
     * Removes a dashboard gadget from a dashboard.
     *
     * When a gadget is removed from a dashboard, other gadgets in the same column are moved up to fill the emptied position.
     *
     * **[Permissions](#permissions) required:** None.
     *
     * @param params.dashboardId - The ID of the dashboard.
     * @param params.gadgetId - The ID of the gadget.
     * @returns Returned if the request is successful.
     */
    removeGadget(
      params: {
        /**
         * The ID of the dashboard.
         *
         * @format int64
         */
        dashboardId: number;
        /**
         * The ID of the gadget.
         *
         * @format int64
         */
        gadgetId: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return removeGadget(ctx, params, options);
    },

    /**
     * Get dashboard item property keys
     *
     * Returns the keys of all properties for a dashboard item.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** The user must have read permission of the dashboard or have the dashboard shared with them.
     *
     * @param params.dashboardId - The ID of the dashboard.
     * @param params.itemId - The ID of the dashboard item.
     * @returns Returned if the request is successful.
     */
    getDashboardItemPropertyKeys(
      params: {
        /** The ID of the dashboard. */
        dashboardId: string;
        /** The ID of the dashboard item. */
        itemId: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PropertyKeys> {
      return getDashboardItemPropertyKeys(ctx, params, options);
    },

    /**
     * Get dashboard item property
     *
     * Returns the key and value of a dashboard item property.
     *
     * A dashboard item enables an app to add user-specific information to a user dashboard. Dashboard items are exposed to users as gadgets that users can add to their dashboards. For more information on how users do this, see [Adding and customizing gadgets](https://confluence.atlassian.com/x/7AeiLQ).
     *
     * When an app creates a dashboard item it registers a callback to receive the dashboard item ID. The callback fires whenever the item is rendered or, where the item is configurable, the user edits the item. The app then uses this resource to store the item's content or configuration details. For more information on working with dashboard items, see [ Building a dashboard item for a JIRA Connect add-on](https://developer.atlassian.com/server/jira/platform/guide-building-a-dashboard-item-for-a-jira-connect-add-on-33746254/) and the [Dashboard Item](https://developer.atlassian.com/cloud/jira/platform/modules/dashboard-item/) documentation.
     *
     * There is no resource to set or get dashboard items.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** The user must have read permission of the dashboard or have the dashboard shared with them.
     *
     * @param params.dashboardId - The ID of the dashboard.
     * @param params.itemId - The ID of the dashboard item.
     * @param params.propertyKey - The key of the dashboard item property.
     * @returns Returned if the request is successful.
     */
    getDashboardItemProperty(
      params: {
        /** The ID of the dashboard. */
        dashboardId: string;
        /** The ID of the dashboard item. */
        itemId: string;
        /** The key of the dashboard item property. */
        propertyKey: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<EntityProperty> {
      return getDashboardItemProperty(ctx, params, options);
    },

    /**
     * Set dashboard item property
     *
     * Sets the value of a dashboard item property. Use this resource in apps to store custom data against a dashboard item.
     *
     * A dashboard item enables an app to add user-specific information to a user dashboard. Dashboard items are exposed to users as gadgets that users can add to their dashboards. For more information on how users do this, see [Adding and customizing gadgets](https://confluence.atlassian.com/x/7AeiLQ).
     *
     * When an app creates a dashboard item it registers a callback to receive the dashboard item ID. The callback fires whenever the item is rendered or, where the item is configurable, the user edits the item. The app then uses this resource to store the item's content or configuration details. For more information on working with dashboard items, see [ Building a dashboard item for a JIRA Connect add-on](https://developer.atlassian.com/server/jira/platform/guide-building-a-dashboard-item-for-a-jira-connect-add-on-33746254/) and the [Dashboard Item](https://developer.atlassian.com/cloud/jira/platform/modules/dashboard-item/) documentation.
     *
     * There is no resource to set or get dashboard items.
     *
     * The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** The user must have edit permisson of the dashboard.
     *
     * @param params.dashboardId - The ID of the dashboard.
     * @param params.itemId - The ID of the dashboard item.
     * @param params.propertyKey - The key of the dashboard item property. The maximum length is 255 characters. For dashboard items with a spec URI and no complete module key, if the provided propertyKey is equal to "config", the request body's JSON must be an object with all keys and values as strings.
     * @param params.body - The value of the property. The value has to be a valid, non-empty [JSON](https://tools.ietf.org/html/rfc4627) value. The maximum length of the property value is 32768 bytes.
     * @returns Returned if the dashboard item property is updated.
     */
    setDashboardItemProperty(
      params: {
        /** The ID of the dashboard. */
        dashboardId: string;
        /** The ID of the dashboard item. */
        itemId: string;
        /** The key of the dashboard item property. The maximum length is 255 characters. For dashboard items with a spec URI and no complete module key, if the provided propertyKey is equal to "config", the request body's JSON must be an object with all keys and values as strings. */
        propertyKey: string;
        body: unknown;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return setDashboardItemProperty(ctx, params, options);
    },

    /**
     * Delete dashboard item property
     *
     * Deletes a dashboard item property.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** The user must have edit permission of the dashboard.
     *
     * @param params.dashboardId - The ID of the dashboard.
     * @param params.itemId - The ID of the dashboard item.
     * @param params.propertyKey - The key of the dashboard item property.
     * @returns Returned if the dashboard item property is deleted.
     */
    deleteDashboardItemProperty(
      params: {
        /** The ID of the dashboard. */
        dashboardId: string;
        /** The ID of the dashboard item. */
        itemId: string;
        /** The key of the dashboard item property. */
        propertyKey: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return deleteDashboardItemProperty(ctx, params, options);
    },

    /**
     * Get dashboard
     *
     * Returns a dashboard.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** None.
     *
     * However, to get a dashboard, the dashboard must be shared with the user or the user must own it. Note, users with the *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) are considered owners of the System dashboard. The System dashboard is considered to be shared with all other users.
     *
     * @param params.id - The ID of the dashboard.
     * @returns Returned if the request is successful.
     */
    getDashboard(
      params: {
        /** The ID of the dashboard. */
        id: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<Dashboard> {
      return getDashboard(ctx, params, options);
    },

    /**
     * Update dashboard
     *
     * Updates a dashboard, replacing all the dashboard details with those provided.
     *
     * **[Permissions](#permissions) required:** None
     *
     * The dashboard to be updated must be owned by the user.
     *
     * @param params.id - The ID of the dashboard to update.
     * @param params.extendAdminPermissions - Whether admin level permissions are used. It should only be true if the user has *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg)
     * @returns Returned if the request is successful.
     */
    updateDashboard(
      params: DashboardDetails & {
        /** The ID of the dashboard to update. */
        id: string;
        /**
         * Whether admin level permissions are used. It should only be true if the user has *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg)
         *
         * @default false
         */
        extendAdminPermissions?: boolean;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<Dashboard> {
      return updateDashboard(ctx, params, options);
    },

    /**
     * Delete dashboard
     *
     * Deletes a dashboard.
     *
     * **[Permissions](#permissions) required:** None
     *
     * The dashboard to be deleted must be owned by the user.
     *
     * @param params.id - The ID of the dashboard.
     * @returns Returned if the dashboard is deleted.
     */
    deleteDashboard(
      params: {
        /** The ID of the dashboard. */
        id: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<void> {
      return deleteDashboard(ctx, params, options);
    },

    /**
     * Copy dashboard
     *
     * Copies a dashboard. Any values provided in the `dashboard` parameter replace those in the copied dashboard.
     *
     * **[Permissions](#permissions) required:** None
     *
     * The dashboard to be copied must be owned by or shared with the user.
     *
     * @param params.extendAdminPermissions - Whether admin level permissions are used. It should only be true if the user has *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg)
     * @returns Returned if the request is successful.
     */
    copyDashboard(
      params: DashboardDetails & {
        id: string;
        /**
         * Whether admin level permissions are used. It should only be true if the user has *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg)
         *
         * @default false
         */
        extendAdminPermissions?: boolean;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<Dashboard> {
      return copyDashboard(ctx, params, options);
    },
  };
}
