// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

import type { ClientContext } from "../../client/index.ts";
import type {
  CreateFieldAssociationSchemeRequest,
  CreateFieldAssociationSchemeResponse,
  DeleteFieldAssociationSchemeResponse,
  FieldSchemeToFieldsResponse,
  FieldSchemeToProjectsRequest,
  FieldSchemeToProjectsResponse,
  GetFieldAssociationParametersResponse,
  GetFieldAssociationSchemeByIdResponse,
  MinimalFieldSchemeToFieldsResponse,
  PageBean2FieldAssociationSchemeFieldSearchResult,
  PageBean2FieldAssociationSchemeProjectSearchResult,
  PageBean2GetFieldAssociationSchemeResponse,
  PageBean2GetProjectsWithFieldSchemesResponse,
  ParameterRemovalDetails,
  RemoveFieldAssociationsRequestItem,
  RemoveFieldParametersResult,
  UpdateFieldAssociationSchemeRequest,
  UpdateFieldAssociationSchemeResponse,
  UpdateFieldAssociationsRequestItem,
  UpdateFieldSchemeParametersRequest,
  UpdateFieldSchemeParametersResponse,
} from "../types/index.ts";

/**
 * Get field schemes
 *
 * REST endpoint for retrieving a paginated list of field association schemes with optional filtering.
 *
 * This endpoint allows clients to fetch field association schemes with optional filtering by project IDs and text queries. The response includes scheme details with navigation links and filter metadata when applicable.
 *
 * Filtering Behavior:
 *
 *  *  When projectId or query parameters are provided, the response includes matchedFilters metadata showing which filters were applied.
 *  *  When no filters are applied, matchedFilters is omitted from individual scheme objects
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.projectId - (optional) List of project IDs to filter schemes by. If not provided, schemes from all projects are returned.
 * @param params.query - (optional) Text filter for scheme name or description matching (case-insensitive). If not provided, no text filtering is applied.
 * @param params.startAt - Zero-based index of the first item to return (default: 0)
 * @param params.maxResults - Maximum number of items to return per page (default: 50, max: 100)
 * @returns Pagianted list of field association schemes
 */
export function getFieldAssociationSchemes(
  ctx: ClientContext,
  params?: {
    /** (optional) List of project IDs to filter schemes by. If not provided, schemes from all projects are returned. */
    projectId?: number[];
    /** (optional) Text filter for scheme name or description matching (case-insensitive). If not provided, no text filtering is applied. */
    query?: string;
    /**
     * Zero-based index of the first item to return (default: 0)
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * Maximum number of items to return per page (default: 50, max: 100)
     *
     * @default 50
     * @format int32
     */
    maxResults?: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBean2GetFieldAssociationSchemeResponse> {
  const { projectId, query, startAt, maxResults } = params ?? {};
  return ctx.request({
    method: "get",
    path: "/rest/api/2/config/fieldschemes",
    query: { projectId, query, startAt, maxResults },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Create field scheme
 *
 * Endpoint for creating a new field association scheme.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @returns Returned if the creation was successful.
 */
export function createFieldAssociationScheme(
  ctx: ClientContext,
  params: CreateFieldAssociationSchemeRequest,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<CreateFieldAssociationSchemeResponse> {
  return ctx.request({
    method: "post",
    path: "/rest/api/2/config/fieldschemes",
    headers: options?.headers,
    body: params,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Update fields associated with field schemes
 *
 * Update fields associated with field association schemes.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @returns Returned if the field association update was successful.
 */
export function updateFieldsAssociatedWithSchemes(
  ctx: ClientContext,
  params: Record<string, UpdateFieldAssociationsRequestItem[]>,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<FieldSchemeToFieldsResponse> {
  return ctx.request({
    method: "put",
    path: "/rest/api/2/config/fieldschemes/fields",
    headers: options?.headers,
    body: params,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Remove fields associated with field schemes
 *
 * Remove fields associated with field association schemes.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @returns Returned if the field association update was successful.
 */
export function removeFieldsAssociatedWithSchemes(
  ctx: ClientContext,
  params: Record<string, RemoveFieldAssociationsRequestItem>,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<MinimalFieldSchemeToFieldsResponse> {
  return ctx.request({
    method: "delete",
    path: "/rest/api/2/config/fieldschemes/fields",
    headers: options?.headers,
    body: params,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Update field parameters
 *
 * Update field association item parameters in field association schemes.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @returns Returned if the field parameter update was successful.
 */
export function updateFieldAssociationSchemeItemParameters(
  ctx: ClientContext,
  params: Record<string, UpdateFieldSchemeParametersRequest[]>,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<UpdateFieldSchemeParametersResponse> {
  return ctx.request({
    method: "put",
    path: "/rest/api/2/config/fieldschemes/fields/parameters",
    headers: options?.headers,
    body: params,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Remove field parameters
 *
 * Remove field association parameters overrides for work types.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @returns Returned if the removal was successful.
 */
export function removeFieldAssociationSchemeItemParameters(
  ctx: ClientContext,
  params: Record<string, ParameterRemovalDetails[]>,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<RemoveFieldParametersResult> {
  return ctx.request({
    method: "delete",
    path: "/rest/api/2/config/fieldschemes/fields/parameters",
    headers: options?.headers,
    body: params,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get projects with field schemes
 *
 * Get projects with field association schemes. This will be a temporary API but useful when transitioning from the legacy field configuration APIs to the new ones.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.startAt - The starting index of the returned projects. Base index: 0.
 * @param params.maxResults - The maximum number of projects to return per page, maximum allowed value is 100.
 * @param params.projectId - List of project ids to filter the results by.
 * @returns Returns the list of project with field association schemes.
 */
export function getProjectsWithFieldSchemes(
  ctx: ClientContext,
  params: {
    /**
     * The starting index of the returned projects. Base index: 0.
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of projects to return per page, maximum allowed value is 100.
     *
     * @default 50
     * @format int32
     */
    maxResults?: number;
    /** List of project ids to filter the results by. */
    projectId: number[];
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBean2GetProjectsWithFieldSchemesResponse> {
  const { startAt, maxResults, projectId } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/config/fieldschemes/projects",
    query: { startAt, maxResults, projectId },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Associate projects to field schemes
 *
 * Associate projects to field association schemes.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @returns Returned if the association was successful.
 */
export function associateProjectsToFieldAssociationSchemes(
  ctx: ClientContext,
  params: Record<string, FieldSchemeToProjectsRequest>,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<FieldSchemeToProjectsResponse> {
  return ctx.request({
    method: "put",
    path: "/rest/api/2/config/fieldschemes/projects",
    headers: options?.headers,
    body: params,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get field scheme
 *
 * Endpoint for fetching a field association scheme by its ID
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.id - The scheme id to fetch
 * @returns Returned if a field association scheme matches the given scheme ID
 */
export function getFieldAssociationSchemeById(
  ctx: ClientContext,
  params: {
    /**
     * The scheme id to fetch
     *
     * @format int64
     */
    id: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<GetFieldAssociationSchemeByIdResponse> {
  const { id } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/config/fieldschemes/{id}",
    pathParams: { id },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Update field scheme
 *
 * Endpoint for updating an existing field association scheme.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @returns Returned if the update was successful.
 */
export function updateFieldAssociationScheme(
  ctx: ClientContext,
  params: UpdateFieldAssociationSchemeRequest & {
    /** @format int64 */
    id: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<UpdateFieldAssociationSchemeResponse> {
  const { id, ...body } = params;
  return ctx.request({
    method: "put",
    path: "/rest/api/2/config/fieldschemes/{id}",
    pathParams: { id },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Delete a field scheme
 *
 * Delete a specified field association scheme
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.id - The ID of the field association scheme to delete.
 * @returns Returned if the field association scheme deletion was successful.
 */
export function deleteFieldAssociationScheme(
  ctx: ClientContext,
  params: {
    /**
     * The ID of the field association scheme to delete.
     *
     * @format int64
     */
    id: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<DeleteFieldAssociationSchemeResponse> {
  const { id } = params;
  return ctx.request({
    method: "delete",
    path: "/rest/api/2/config/fieldschemes/{id}",
    pathParams: { id },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Clone field scheme
 *
 * Endpoint for cloning an existing field association scheme into a new one.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.id - The ID of the source field association scheme to clone from
 * @returns Returned if the clone was successful.
 */
export function cloneFieldAssociationScheme(
  ctx: ClientContext,
  params: CreateFieldAssociationSchemeRequest & {
    /**
     * The ID of the source field association scheme to clone from
     *
     * @format int64
     */
    id: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<CreateFieldAssociationSchemeResponse> {
  const { id, ...body } = params;
  return ctx.request({
    method: "post",
    path: "/rest/api/2/config/fieldschemes/{id}/clone",
    pathParams: { id },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Search field scheme fields
 *
 * Search for fields belonging to a given field association scheme.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.id - The scheme ID to search for child fields
 * @param params.startAt - The starting index of the returned fields. Base index: 0.
 * @param params.maxResults - The maximum number of fields to return per page, maximum allowed value is 100.
 * @param params.fieldId - The field IDs to filter by, if empty then all fields belonging to a field association scheme will be returned
 * @returns Returns the matching fields, at the specified page of the results.
 */
export function searchFieldAssociationSchemeFields(
  ctx: ClientContext,
  params: {
    /**
     * The scheme ID to search for child fields
     *
     * @format int64
     */
    id: number;
    /**
     * The starting index of the returned fields. Base index: 0.
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of fields to return per page, maximum allowed value is 100.
     *
     * @default 50
     * @format int32
     */
    maxResults?: number;
    /** The field IDs to filter by, if empty then all fields belonging to a field association scheme will be returned */
    fieldId?: string[];
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBean2FieldAssociationSchemeFieldSearchResult> {
  const { id, startAt, maxResults, fieldId } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/config/fieldschemes/{id}/fields",
    pathParams: { id },
    query: { startAt, maxResults, fieldId },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get field parameters
 *
 * Retrieve field association parameters on a field association scheme
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.id - the ID of the field association scheme to retrieve parameters for
 * @param params.fieldId - the ID of the field
 * @returns Returned if the parameters fetched were successful.
 */
export function getFieldAssociationSchemeItemParameters(
  ctx: ClientContext,
  params: {
    /**
     * the ID of the field association scheme to retrieve parameters for
     *
     * @format int64
     */
    id: number;
    /** the ID of the field */
    fieldId: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<GetFieldAssociationParametersResponse> {
  const { id, fieldId } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/config/fieldschemes/{id}/fields/{fieldId}/parameters",
    pathParams: { id, fieldId },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Search field scheme projects
 *
 * REST Endpoint for searching for projects belonging to a given field association scheme
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.id - The scheme id to search for associated projects
 * @param params.startAt - The starting index of the returned projects. Base index: 0.
 * @param params.maxResults - The maximum number of projects to return per page, maximum allowed value is 100.
 * @param params.projectId - The project Ids to filter by, if empty then all projects belonging to a field association scheme will be returned
 * @returns Returns a paginated list of projects associated with the field association scheme, matching the specified filter criteria.
 */
export function searchFieldAssociationSchemeProjects(
  ctx: ClientContext,
  params: {
    /**
     * The scheme id to search for associated projects
     *
     * @format int64
     */
    id: number;
    /**
     * The starting index of the returned projects. Base index: 0.
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of projects to return per page, maximum allowed value is 100.
     *
     * @default 50
     * @format int32
     */
    maxResults?: number;
    /** The project Ids to filter by, if empty then all projects belonging to a field association scheme will be returned */
    projectId?: number[];
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBean2FieldAssociationSchemeProjectSearchResult> {
  const { id, startAt, maxResults, projectId } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/config/fieldschemes/{id}/projects",
    pathParams: { id },
    query: { startAt, maxResults, projectId },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/** This resource represents field schemes which are replacing field configuration schemes to control field associations. They are currently in beta and only available to customers who have opted-in to the beta program. For more information see [RFC-103: Jira Field Configuration Overhaul: Admin Experience and API Changes](https://community.developer.atlassian.com/t/rfc-103-jira-field-configuration-overhaul-admin-experience-and-api-changes/94205) */
export function createFieldSchemesService(ctx: ClientContext) {
  return {
    /**
     * Get field schemes
     *
     * REST endpoint for retrieving a paginated list of field association schemes with optional filtering.
     *
     * This endpoint allows clients to fetch field association schemes with optional filtering by project IDs and text queries. The response includes scheme details with navigation links and filter metadata when applicable.
     *
     * Filtering Behavior:
     *
     *  *  When projectId or query parameters are provided, the response includes matchedFilters metadata showing which filters were applied.
     *  *  When no filters are applied, matchedFilters is omitted from individual scheme objects
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.projectId - (optional) List of project IDs to filter schemes by. If not provided, schemes from all projects are returned.
     * @param params.query - (optional) Text filter for scheme name or description matching (case-insensitive). If not provided, no text filtering is applied.
     * @param params.startAt - Zero-based index of the first item to return (default: 0)
     * @param params.maxResults - Maximum number of items to return per page (default: 50, max: 100)
     * @returns Pagianted list of field association schemes
     */
    getFieldAssociationSchemes(
      params?: {
        /** (optional) List of project IDs to filter schemes by. If not provided, schemes from all projects are returned. */
        projectId?: number[];
        /** (optional) Text filter for scheme name or description matching (case-insensitive). If not provided, no text filtering is applied. */
        query?: string;
        /**
         * Zero-based index of the first item to return (default: 0)
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * Maximum number of items to return per page (default: 50, max: 100)
         *
         * @default 50
         * @format int32
         */
        maxResults?: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBean2GetFieldAssociationSchemeResponse> {
      return getFieldAssociationSchemes(ctx, params, options);
    },

    /**
     * Create field scheme
     *
     * Endpoint for creating a new field association scheme.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @returns Returned if the creation was successful.
     */
    createFieldAssociationScheme(
      params: CreateFieldAssociationSchemeRequest,
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<CreateFieldAssociationSchemeResponse> {
      return createFieldAssociationScheme(ctx, params, options);
    },

    /**
     * Update fields associated with field schemes
     *
     * Update fields associated with field association schemes.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @returns Returned if the field association update was successful.
     */
    updateFieldsAssociatedWithSchemes(
      params: Record<string, UpdateFieldAssociationsRequestItem[]>,
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<FieldSchemeToFieldsResponse> {
      return updateFieldsAssociatedWithSchemes(ctx, params, options);
    },

    /**
     * Remove fields associated with field schemes
     *
     * Remove fields associated with field association schemes.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @returns Returned if the field association update was successful.
     */
    removeFieldsAssociatedWithSchemes(
      params: Record<string, RemoveFieldAssociationsRequestItem>,
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<MinimalFieldSchemeToFieldsResponse> {
      return removeFieldsAssociatedWithSchemes(ctx, params, options);
    },

    /**
     * Update field parameters
     *
     * Update field association item parameters in field association schemes.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @returns Returned if the field parameter update was successful.
     */
    updateFieldAssociationSchemeItemParameters(
      params: Record<string, UpdateFieldSchemeParametersRequest[]>,
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<UpdateFieldSchemeParametersResponse> {
      return updateFieldAssociationSchemeItemParameters(ctx, params, options);
    },

    /**
     * Remove field parameters
     *
     * Remove field association parameters overrides for work types.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @returns Returned if the removal was successful.
     */
    removeFieldAssociationSchemeItemParameters(
      params: Record<string, ParameterRemovalDetails[]>,
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<RemoveFieldParametersResult> {
      return removeFieldAssociationSchemeItemParameters(ctx, params, options);
    },

    /**
     * Get projects with field schemes
     *
     * Get projects with field association schemes. This will be a temporary API but useful when transitioning from the legacy field configuration APIs to the new ones.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.startAt - The starting index of the returned projects. Base index: 0.
     * @param params.maxResults - The maximum number of projects to return per page, maximum allowed value is 100.
     * @param params.projectId - List of project ids to filter the results by.
     * @returns Returns the list of project with field association schemes.
     */
    getProjectsWithFieldSchemes(
      params: {
        /**
         * The starting index of the returned projects. Base index: 0.
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of projects to return per page, maximum allowed value is 100.
         *
         * @default 50
         * @format int32
         */
        maxResults?: number;
        /** List of project ids to filter the results by. */
        projectId: number[];
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBean2GetProjectsWithFieldSchemesResponse> {
      return getProjectsWithFieldSchemes(ctx, params, options);
    },

    /**
     * Associate projects to field schemes
     *
     * Associate projects to field association schemes.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @returns Returned if the association was successful.
     */
    associateProjectsToFieldAssociationSchemes(
      params: Record<string, FieldSchemeToProjectsRequest>,
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<FieldSchemeToProjectsResponse> {
      return associateProjectsToFieldAssociationSchemes(ctx, params, options);
    },

    /**
     * Get field scheme
     *
     * Endpoint for fetching a field association scheme by its ID
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.id - The scheme id to fetch
     * @returns Returned if a field association scheme matches the given scheme ID
     */
    getFieldAssociationSchemeById(
      params: {
        /**
         * The scheme id to fetch
         *
         * @format int64
         */
        id: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<GetFieldAssociationSchemeByIdResponse> {
      return getFieldAssociationSchemeById(ctx, params, options);
    },

    /**
     * Update field scheme
     *
     * Endpoint for updating an existing field association scheme.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @returns Returned if the update was successful.
     */
    updateFieldAssociationScheme(
      params: UpdateFieldAssociationSchemeRequest & {
        /** @format int64 */
        id: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<UpdateFieldAssociationSchemeResponse> {
      return updateFieldAssociationScheme(ctx, params, options);
    },

    /**
     * Delete a field scheme
     *
     * Delete a specified field association scheme
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.id - The ID of the field association scheme to delete.
     * @returns Returned if the field association scheme deletion was successful.
     */
    deleteFieldAssociationScheme(
      params: {
        /**
         * The ID of the field association scheme to delete.
         *
         * @format int64
         */
        id: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<DeleteFieldAssociationSchemeResponse> {
      return deleteFieldAssociationScheme(ctx, params, options);
    },

    /**
     * Clone field scheme
     *
     * Endpoint for cloning an existing field association scheme into a new one.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.id - The ID of the source field association scheme to clone from
     * @returns Returned if the clone was successful.
     */
    cloneFieldAssociationScheme(
      params: CreateFieldAssociationSchemeRequest & {
        /**
         * The ID of the source field association scheme to clone from
         *
         * @format int64
         */
        id: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<CreateFieldAssociationSchemeResponse> {
      return cloneFieldAssociationScheme(ctx, params, options);
    },

    /**
     * Search field scheme fields
     *
     * Search for fields belonging to a given field association scheme.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.id - The scheme ID to search for child fields
     * @param params.startAt - The starting index of the returned fields. Base index: 0.
     * @param params.maxResults - The maximum number of fields to return per page, maximum allowed value is 100.
     * @param params.fieldId - The field IDs to filter by, if empty then all fields belonging to a field association scheme will be returned
     * @returns Returns the matching fields, at the specified page of the results.
     */
    searchFieldAssociationSchemeFields(
      params: {
        /**
         * The scheme ID to search for child fields
         *
         * @format int64
         */
        id: number;
        /**
         * The starting index of the returned fields. Base index: 0.
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of fields to return per page, maximum allowed value is 100.
         *
         * @default 50
         * @format int32
         */
        maxResults?: number;
        /** The field IDs to filter by, if empty then all fields belonging to a field association scheme will be returned */
        fieldId?: string[];
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBean2FieldAssociationSchemeFieldSearchResult> {
      return searchFieldAssociationSchemeFields(ctx, params, options);
    },

    /**
     * Get field parameters
     *
     * Retrieve field association parameters on a field association scheme
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.id - the ID of the field association scheme to retrieve parameters for
     * @param params.fieldId - the ID of the field
     * @returns Returned if the parameters fetched were successful.
     */
    getFieldAssociationSchemeItemParameters(
      params: {
        /**
         * the ID of the field association scheme to retrieve parameters for
         *
         * @format int64
         */
        id: number;
        /** the ID of the field */
        fieldId: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<GetFieldAssociationParametersResponse> {
      return getFieldAssociationSchemeItemParameters(ctx, params, options);
    },

    /**
     * Search field scheme projects
     *
     * REST Endpoint for searching for projects belonging to a given field association scheme
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.id - The scheme id to search for associated projects
     * @param params.startAt - The starting index of the returned projects. Base index: 0.
     * @param params.maxResults - The maximum number of projects to return per page, maximum allowed value is 100.
     * @param params.projectId - The project Ids to filter by, if empty then all projects belonging to a field association scheme will be returned
     * @returns Returns a paginated list of projects associated with the field association scheme, matching the specified filter criteria.
     */
    searchFieldAssociationSchemeProjects(
      params: {
        /**
         * The scheme id to search for associated projects
         *
         * @format int64
         */
        id: number;
        /**
         * The starting index of the returned projects. Base index: 0.
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of projects to return per page, maximum allowed value is 100.
         *
         * @default 50
         * @format int32
         */
        maxResults?: number;
        /** The project Ids to filter by, if empty then all projects belonging to a field association scheme will be returned */
        projectId?: number[];
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBean2FieldAssociationSchemeProjectSearchResult> {
      return searchFieldAssociationSchemeProjects(ctx, params, options);
    },
  };
}
