// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

import type { ClientContext } from "../../client/index.ts";
import type {
  Comment,
  IssueCommentListRequestBean,
  PageBeanComment,
  PageOfComments,
} from "../types/index.ts";

/**
 * Get comments by IDs
 *
 * Returns a [paginated](#pagination) list of comments specified by a list of comment IDs.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** Comments are returned where the user:
 *
 *  *  has *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the comment.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *  *  If the comment has visibility restrictions, belongs to the group or has the role visibility is restricted to.
 *
 * @param params.expand - Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts a comma-separated list. Expand options include: *  `renderedBody` Returns the comment body rendered in HTML. *  `properties` Returns the comment's properties.
 * @returns Returned if the request is successful.
 */
export function getCommentsByIds(
  ctx: ClientContext,
  params: IssueCommentListRequestBean & {
    /**
     * Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts a comma-separated list. Expand options include:
     *
     *  *  `renderedBody` Returns the comment body rendered in HTML.
     *  *  `properties` Returns the comment's properties.
     */
    expand?: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBeanComment> {
  const { expand, ...body } = params;
  return ctx.request({
    method: "post",
    path: "/rest/api/2/comment/list",
    query: { expand },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get comments
 *
 * Returns all comments for an issue.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** Comments are included in the response where the user has:
 *
 *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the comment.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *  *  If the comment has visibility restrictions, belongs to the group or has the role visibility is role visibility is restricted to.
 *
 * @param params.issueIdOrKey - The ID or key of the issue.
 * @param params.startAt - The index of the first item to return in a page of results (page offset).
 * @param params.maxResults - The maximum number of items to return per page.
 * @param params.orderBy - [Order](#ordering) the results by a field. Accepts *created* to sort comments by their created date.
 * @param params.expand - Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML.
 * @returns Returned if the request is successful.
 */
export function getComments(
  ctx: ClientContext,
  params: {
    /** The ID or key of the issue. */
    issueIdOrKey: string;
    /**
     * The index of the first item to return in a page of results (page offset).
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of items to return per page.
     *
     * @default 100
     * @format int32
     */
    maxResults?: number;
    /** [Order](#ordering) the results by a field. Accepts *created* to sort comments by their created date. */
    orderBy?: "created" | "-created" | "+created";
    /** Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML. */
    expand?: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageOfComments> {
  const { issueIdOrKey, startAt, maxResults, orderBy, expand } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/issue/{issueIdOrKey}/comment",
    pathParams: { issueIdOrKey },
    query: { startAt, maxResults, orderBy, expand },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Add comment
 *
 * Adds a comment to an issue.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  *Browse projects* and *Add comments* [ project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue containing the comment is in.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *
 * @param params.issueIdOrKey - The ID or key of the issue.
 * @param params.expand - Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML.
 * @returns Returned if the request is successful.
 */
export function addComment(
  ctx: ClientContext,
  params: Comment & {
    /** The ID or key of the issue. */
    issueIdOrKey: string;
    /** Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML. */
    expand?: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<Comment> {
  const { issueIdOrKey, expand, ...body } = params;
  return ctx.request({
    method: "post",
    path: "/rest/api/2/issue/{issueIdOrKey}/comment",
    pathParams: { issueIdOrKey },
    query: { expand },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get comment
 *
 * Returns a comment.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the comment.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *  *  If the comment has visibility restrictions, the user belongs to the group or has the role visibility is restricted to.
 *
 * @param params.issueIdOrKey - The ID or key of the issue.
 * @param params.id - The ID of the comment.
 * @param params.expand - Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML.
 * @returns Returned if the request is successful.
 */
export function getComment(
  ctx: ClientContext,
  params: {
    /** The ID or key of the issue. */
    issueIdOrKey: string;
    /** The ID of the comment. */
    id: string;
    /** Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML. */
    expand?: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<Comment> {
  const { issueIdOrKey, id, expand } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/issue/{issueIdOrKey}/comment/{id}",
    pathParams: { issueIdOrKey, id },
    query: { expand },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Update comment
 *
 * Updates a comment.
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue containing the comment is in.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *  *  *Edit all comments*[ project permission](https://confluence.atlassian.com/x/yodKLg) to update any comment or *Edit own comments* to update comment created by the user.
 *  *  If the comment has visibility restrictions, the user belongs to the group or has the role visibility is restricted to.
 *
 * **WARNING:** Child comments inherit visibility from their parent comment. Attempting to update a child comment's visibility will result in a 400 (Bad Request) error.
 *
 * @param params.issueIdOrKey - The ID or key of the issue.
 * @param params.id_path - The ID of the comment.
 * @param params.notifyUsers - Whether users are notified when a comment is updated.
 * @param params.overrideEditableFlag - Whether screen security is overridden to enable uneditable fields to be edited. Available to Connect app users with the *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 * @param params.expand - Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML.
 * @returns Returned if the request is successful.
 */
export function updateComment(
  ctx: ClientContext,
  params: Comment & {
    /** The ID or key of the issue. */
    issueIdOrKey: string;
    /** The ID of the comment. */
    id_path: string;
    /**
     * Whether users are notified when a comment is updated.
     *
     * @default true
     */
    notifyUsers?: boolean;
    /**
     * Whether screen security is overridden to enable uneditable fields to be edited. Available to Connect app users with the *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @default false
     */
    overrideEditableFlag?: boolean;
    /** Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML. */
    expand?: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<Comment> {
  const { issueIdOrKey, id_path, notifyUsers, overrideEditableFlag, expand, ...body } = params;
  return ctx.request({
    method: "put",
    path: "/rest/api/2/issue/{issueIdOrKey}/comment/{id}",
    pathParams: { issueIdOrKey, id: id_path },
    query: { notifyUsers, overrideEditableFlag, expand },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Delete comment
 *
 * Deletes a comment.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue containing the comment is in.
 *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
 *  *  *Delete all comments*[ project permission](https://confluence.atlassian.com/x/yodKLg) to delete any comment or *Delete own comments* to delete comment created by the user,
 *  *  If the comment has visibility restrictions, the user belongs to the group or has the role visibility is restricted to.
 *
 * @param params.issueIdOrKey - The ID or key of the issue.
 * @param params.id - The ID of the comment.
 * @returns Returned if the request is successful.
 */
export function deleteComment(
  ctx: ClientContext,
  params: {
    /** The ID or key of the issue. */
    issueIdOrKey: string;
    /** The ID of the comment. */
    id: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<void> {
  const { issueIdOrKey, id } = params;
  return ctx.request({
    method: "delete",
    path: "/rest/api/2/issue/{issueIdOrKey}/comment/{id}",
    pathParams: { issueIdOrKey, id },
    headers: options?.headers,
    responseType: "void",
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * This resource represents issue comments. Use it to:
 *
 *  *  get, create, update, and delete a comment from an issue.
 *  *  get all comments from issue.
 *  *  get a list of comments by comment ID.
 */
export function createIssueCommentsService(ctx: ClientContext) {
  return {
    /**
     * Get comments by IDs
     *
     * Returns a [paginated](#pagination) list of comments specified by a list of comment IDs.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** Comments are returned where the user:
     *
     *  *  has *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the comment.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *  *  If the comment has visibility restrictions, belongs to the group or has the role visibility is restricted to.
     *
     * @param params.expand - Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts a comma-separated list. Expand options include: *  `renderedBody` Returns the comment body rendered in HTML. *  `properties` Returns the comment's properties.
     * @returns Returned if the request is successful.
     */
    getCommentsByIds(
      params: IssueCommentListRequestBean & {
        /**
         * Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts a comma-separated list. Expand options include:
         *
         *  *  `renderedBody` Returns the comment body rendered in HTML.
         *  *  `properties` Returns the comment's properties.
         */
        expand?: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBeanComment> {
      return getCommentsByIds(ctx, params, options);
    },

    /**
     * Get comments
     *
     * Returns all comments for an issue.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** Comments are included in the response where the user has:
     *
     *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the comment.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *  *  If the comment has visibility restrictions, belongs to the group or has the role visibility is role visibility is restricted to.
     *
     * @param params.issueIdOrKey - The ID or key of the issue.
     * @param params.startAt - The index of the first item to return in a page of results (page offset).
     * @param params.maxResults - The maximum number of items to return per page.
     * @param params.orderBy - [Order](#ordering) the results by a field. Accepts *created* to sort comments by their created date.
     * @param params.expand - Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML.
     * @returns Returned if the request is successful.
     */
    getComments(
      params: {
        /** The ID or key of the issue. */
        issueIdOrKey: string;
        /**
         * The index of the first item to return in a page of results (page offset).
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of items to return per page.
         *
         * @default 100
         * @format int32
         */
        maxResults?: number;
        /** [Order](#ordering) the results by a field. Accepts *created* to sort comments by their created date. */
        orderBy?: "created" | "-created" | "+created";
        /** Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML. */
        expand?: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageOfComments> {
      return getComments(ctx, params, options);
    },

    /**
     * Add comment
     *
     * Adds a comment to an issue.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  *Browse projects* and *Add comments* [ project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue containing the comment is in.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *
     * @param params.issueIdOrKey - The ID or key of the issue.
     * @param params.expand - Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML.
     * @returns Returned if the request is successful.
     */
    addComment(
      params: Comment & {
        /** The ID or key of the issue. */
        issueIdOrKey: string;
        /** Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML. */
        expand?: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<Comment> {
      return addComment(ctx, params, options);
    },

    /**
     * Get comment
     *
     * Returns a comment.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the comment.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *  *  If the comment has visibility restrictions, the user belongs to the group or has the role visibility is restricted to.
     *
     * @param params.issueIdOrKey - The ID or key of the issue.
     * @param params.id - The ID of the comment.
     * @param params.expand - Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML.
     * @returns Returned if the request is successful.
     */
    getComment(
      params: {
        /** The ID or key of the issue. */
        issueIdOrKey: string;
        /** The ID of the comment. */
        id: string;
        /** Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML. */
        expand?: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<Comment> {
      return getComment(ctx, params, options);
    },

    /**
     * Update comment
     *
     * Updates a comment.
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue containing the comment is in.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *  *  *Edit all comments*[ project permission](https://confluence.atlassian.com/x/yodKLg) to update any comment or *Edit own comments* to update comment created by the user.
     *  *  If the comment has visibility restrictions, the user belongs to the group or has the role visibility is restricted to.
     *
     * **WARNING:** Child comments inherit visibility from their parent comment. Attempting to update a child comment's visibility will result in a 400 (Bad Request) error.
     *
     * @param params.issueIdOrKey - The ID or key of the issue.
     * @param params.id_path - The ID of the comment.
     * @param params.notifyUsers - Whether users are notified when a comment is updated.
     * @param params.overrideEditableFlag - Whether screen security is overridden to enable uneditable fields to be edited. Available to Connect app users with the *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * @param params.expand - Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML.
     * @returns Returned if the request is successful.
     */
    updateComment(
      params: Comment & {
        /** The ID or key of the issue. */
        issueIdOrKey: string;
        /** The ID of the comment. */
        id_path: string;
        /**
         * Whether users are notified when a comment is updated.
         *
         * @default true
         */
        notifyUsers?: boolean;
        /**
         * Whether screen security is overridden to enable uneditable fields to be edited. Available to Connect app users with the *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
         *
         * @default false
         */
        overrideEditableFlag?: boolean;
        /** Use [expand](#expansion) to include additional information about comments in the response. This parameter accepts `renderedBody`, which returns the comment body rendered in HTML. */
        expand?: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<Comment> {
      return updateComment(ctx, params, options);
    },

    /**
     * Delete comment
     *
     * Deletes a comment.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue containing the comment is in.
     *  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     *  *  *Delete all comments*[ project permission](https://confluence.atlassian.com/x/yodKLg) to delete any comment or *Delete own comments* to delete comment created by the user,
     *  *  If the comment has visibility restrictions, the user belongs to the group or has the role visibility is restricted to.
     *
     * @param params.issueIdOrKey - The ID or key of the issue.
     * @param params.id - The ID of the comment.
     * @returns Returned if the request is successful.
     */
    deleteComment(
      params: {
        /** The ID or key of the issue. */
        issueIdOrKey: string;
        /** The ID of the comment. */
        id: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<void> {
      return deleteComment(ctx, params, options);
    },
  };
}
