// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

import type { ClientContext } from "../../client/index.ts";
import type {
  CreateCustomFieldContext,
  CustomFieldContextDefaultValueUpdate,
  CustomFieldContextUpdateDetails,
  IssueTypeIds,
  PageBeanContextDefaultValues,
  PageBeanContextForProjectAndIssueType,
  PageBeanCustomFieldContext,
  PageBeanCustomFieldContextDefaultValue,
  PageBeanCustomFieldContextProjectMapping,
  PageBeanIssueTypeToContextMapping,
  ProjectIds,
  ProjectIssueTypeMappings,
} from "../types/index.ts";

/**
 * Get custom field contexts
 *
 * Returns a [paginated](#pagination) list of [ contexts](https://confluence.atlassian.com/adminjiracloud/what-are-custom-field-contexts-991923859.html) for a custom field. Contexts can be returned as follows:
 *
 *  *  With no other parameters set, all contexts.
 *  *  By defining `id` only, all contexts from the list of IDs.
 *  *  By defining `isAnyIssueType`, limit the list of contexts returned to either those that apply to all issue types (true) or those that apply to only a subset of issue types (false)
 *  *  By defining `isGlobalContext`, limit the list of contexts return to either those that apply to all projects (global contexts) (true) or those that apply to only a subset of projects (false).
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg). *Edit Workflow* [edit workflow permission](https://support.atlassian.com/jira-cloud-administration/docs/permissions-for-company-managed-projects/#Edit-Workflows)
 *
 * @param params.fieldId - The ID of the custom field.
 * @param params.isAnyIssueType - Whether to return contexts that apply to all issue types.
 * @param params.isGlobalContext - Whether to return contexts that apply to all projects.
 * @param params.contextId - The list of context IDs. To include multiple contexts, separate IDs with ampersand: `contextId=10000&contextId=10001`.
 * @param params.startAt - The index of the first item to return in a page of results (page offset).
 * @param params.maxResults - The maximum number of items to return per page.
 * @returns Returned if the request is successful.
 */
export function getContextsForField(
  ctx: ClientContext,
  params: {
    /** The ID of the custom field. */
    fieldId: string;
    /** Whether to return contexts that apply to all issue types. */
    isAnyIssueType?: boolean;
    /** Whether to return contexts that apply to all projects. */
    isGlobalContext?: boolean;
    /** The list of context IDs. To include multiple contexts, separate IDs with ampersand: `contextId=10000&contextId=10001`. */
    contextId?: number[];
    /**
     * The index of the first item to return in a page of results (page offset).
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of items to return per page.
     *
     * @default 50
     * @format int32
     */
    maxResults?: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBeanCustomFieldContext> {
  const { fieldId, isAnyIssueType, isGlobalContext, contextId, startAt, maxResults } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/field/{fieldId}/context",
    pathParams: { fieldId },
    query: { isAnyIssueType, isGlobalContext, contextId, startAt, maxResults },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Create custom field context
 *
 * Creates a custom field context.
 *
 * If `projectIds` is empty, a global context is created. A global context is one that applies to all project. If `issueTypeIds` is empty, the context applies to all issue types.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the custom field.
 * @returns Returned if the custom field context is created.
 */
export function createCustomFieldContext(
  ctx: ClientContext,
  params: CreateCustomFieldContext & {
    /** The ID of the custom field. */
    fieldId: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<CreateCustomFieldContext> {
  const { fieldId, ...body } = params;
  return ctx.request({
    method: "post",
    path: "/rest/api/2/field/{fieldId}/context",
    pathParams: { fieldId },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get custom field contexts default values
 *
 * Returns a [paginated](#pagination) list of defaults for a custom field. The results can be filtered by `contextId`, otherwise all values are returned. If no defaults are set for a context, nothing is returned.
 * The returned object depends on type of the custom field:
 *
 *  *  `CustomFieldContextDefaultValueDate` (type `datepicker`) for date fields.
 *  *  `CustomFieldContextDefaultValueDateTime` (type `datetimepicker`) for date-time fields.
 *  *  `CustomFieldContextDefaultValueSingleOption` (type `option.single`) for single choice select lists and radio buttons.
 *  *  `CustomFieldContextDefaultValueMultipleOption` (type `option.multiple`) for multiple choice select lists and checkboxes.
 *  *  `CustomFieldContextDefaultValueCascadingOption` (type `option.cascading`) for cascading select lists.
 *  *  `CustomFieldContextSingleUserPickerDefaults` (type `single.user.select`) for single users.
 *  *  `CustomFieldContextDefaultValueMultiUserPicker` (type `multi.user.select`) for user lists.
 *  *  `CustomFieldContextDefaultValueSingleGroupPicker` (type `grouppicker.single`) for single choice group pickers.
 *  *  `CustomFieldContextDefaultValueMultipleGroupPicker` (type `grouppicker.multiple`) for multiple choice group pickers.
 *  *  `CustomFieldContextDefaultValueURL` (type `url`) for URLs.
 *  *  `CustomFieldContextDefaultValueProject` (type `project`) for project pickers.
 *  *  `CustomFieldContextDefaultValueFloat` (type `float`) for floats (floating-point numbers).
 *  *  `CustomFieldContextDefaultValueLabels` (type `labels`) for labels.
 *  *  `CustomFieldContextDefaultValueTextField` (type `textfield`) for text fields.
 *  *  `CustomFieldContextDefaultValueTextArea` (type `textarea`) for text area fields.
 *  *  `CustomFieldContextDefaultValueReadOnly` (type `readonly`) for read only (text) fields.
 *  *  `CustomFieldContextDefaultValueMultipleVersion` (type `version.multiple`) for single choice version pickers.
 *  *  `CustomFieldContextDefaultValueSingleVersion` (type `version.single`) for multiple choice version pickers.
 *
 * Forge custom fields [types](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field-type/#data-types) are also supported, returning:
 *
 *  *  `CustomFieldContextDefaultValueForgeStringFieldBean` (type `forge.string`) for Forge string fields.
 *  *  `CustomFieldContextDefaultValueForgeMultiStringFieldBean` (type `forge.string.list`) for Forge string collection fields.
 *  *  `CustomFieldContextDefaultValueForgeObjectFieldBean` (type `forge.object`) for Forge object fields.
 *  *  `CustomFieldContextDefaultValueForgeDateTimeFieldBean` (type `forge.datetime`) for Forge date-time fields.
 *  *  `CustomFieldContextDefaultValueForgeGroupFieldBean` (type `forge.group`) for Forge group fields.
 *  *  `CustomFieldContextDefaultValueForgeMultiGroupFieldBean` (type `forge.group.list`) for Forge group collection fields.
 *  *  `CustomFieldContextDefaultValueForgeNumberFieldBean` (type `forge.number`) for Forge number fields.
 *  *  `CustomFieldContextDefaultValueForgeUserFieldBean` (type `forge.user`) for Forge user fields.
 *  *  `CustomFieldContextDefaultValueForgeMultiUserFieldBean` (type `forge.user.list`) for Forge user collection fields.
 *
 * **Deprecated:** This API is deprecated and will be removed in October 2026. A replacement API that supports multiple default values per issue type within a context is coming soon. See the deprecation notice [CHANGE-3082](https://developer.atlassian.com/cloud/jira/platform/changelog/#CHANGE-3082) for more details.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the custom field, for example `customfield\_10000`.
 * @param params.contextId - The IDs of the contexts.
 * @param params.startAt - The index of the first item to return in a page of results (page offset).
 * @param params.maxResults - The maximum number of items to return per page.
 * @returns Returned if the request is successful.
 * @deprecated
 */
export function getDefaultValues(
  ctx: ClientContext,
  params: {
    /** The ID of the custom field, for example `customfield\_10000`. */
    fieldId: string;
    /** The IDs of the contexts. */
    contextId?: number[];
    /**
     * The index of the first item to return in a page of results (page offset).
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of items to return per page.
     *
     * @default 50
     * @format int32
     */
    maxResults?: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBeanCustomFieldContextDefaultValue> {
  const { fieldId, contextId, startAt, maxResults } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/field/{fieldId}/context/defaultValue",
    pathParams: { fieldId },
    query: { contextId, startAt, maxResults },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Set custom field contexts default values
 *
 * Sets default for contexts of a custom field. Default are defined using these objects:
 *
 *  *  `CustomFieldContextDefaultValueDate` (type `datepicker`) for date fields.
 *  *  `CustomFieldContextDefaultValueDateTime` (type `datetimepicker`) for date-time fields.
 *  *  `CustomFieldContextDefaultValueSingleOption` (type `option.single`) for single choice select lists and radio buttons.
 *  *  `CustomFieldContextDefaultValueMultipleOption` (type `option.multiple`) for multiple choice select lists and checkboxes.
 *  *  `CustomFieldContextDefaultValueCascadingOption` (type `option.cascading`) for cascading select lists.
 *  *  `CustomFieldContextSingleUserPickerDefaults` (type `single.user.select`) for single users.
 *  *  `CustomFieldContextDefaultValueMultiUserPicker` (type `multi.user.select`) for user lists.
 *  *  `CustomFieldContextDefaultValueSingleGroupPicker` (type `grouppicker.single`) for single choice group pickers.
 *  *  `CustomFieldContextDefaultValueMultipleGroupPicker` (type `grouppicker.multiple`) for multiple choice group pickers.
 *  *  `CustomFieldContextDefaultValueURL` (type `url`) for URLs.
 *  *  `CustomFieldContextDefaultValueProject` (type `project`) for project pickers.
 *  *  `CustomFieldContextDefaultValueFloat` (type `float`) for floats (floating-point numbers).
 *  *  `CustomFieldContextDefaultValueLabels` (type `labels`) for labels.
 *  *  `CustomFieldContextDefaultValueTextField` (type `textfield`) for text fields.
 *  *  `CustomFieldContextDefaultValueTextArea` (type `textarea`) for text area fields.
 *  *  `CustomFieldContextDefaultValueReadOnly` (type `readonly`) for read only (text) fields.
 *  *  `CustomFieldContextDefaultValueMultipleVersion` (type `version.multiple`) for single choice version pickers.
 *  *  `CustomFieldContextDefaultValueSingleVersion` (type `version.single`) for multiple choice version pickers.
 *
 * Forge custom fields [types](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field-type/#data-types) are also supported, returning:
 *
 *  *  `CustomFieldContextDefaultValueForgeStringFieldBean` (type `forge.string`) for Forge string fields.
 *  *  `CustomFieldContextDefaultValueForgeMultiStringFieldBean` (type `forge.string.list`) for Forge string collection fields.
 *  *  `CustomFieldContextDefaultValueForgeObjectFieldBean` (type `forge.object`) for Forge object fields.
 *  *  `CustomFieldContextDefaultValueForgeDateTimeFieldBean` (type `forge.datetime`) for Forge date-time fields.
 *  *  `CustomFieldContextDefaultValueForgeGroupFieldBean` (type `forge.group`) for Forge group fields.
 *  *  `CustomFieldContextDefaultValueForgeMultiGroupFieldBean` (type `forge.group.list`) for Forge group collection fields.
 *  *  `CustomFieldContextDefaultValueForgeNumberFieldBean` (type `forge.number`) for Forge number fields.
 *  *  `CustomFieldContextDefaultValueForgeUserFieldBean` (type `forge.user`) for Forge user fields.
 *  *  `CustomFieldContextDefaultValueForgeMultiUserFieldBean` (type `forge.user.list`) for Forge user collection fields.
 *
 * Only one type of default object can be included in a request. To remove a default for a context, set the default parameter to `null`.
 *
 * **Deprecated:** This API is deprecated and will be removed in October 2026. A replacement API that supports multiple default values per issue type within a context is coming soon. See the deprecation notice [CHANGE-3082](https://developer.atlassian.com/cloud/jira/platform/changelog/#CHANGE-3082) for more details.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the custom field.
 * @returns Returned if operation is successful.
 * @deprecated
 */
export function setDefaultValues(
  ctx: ClientContext,
  params: CustomFieldContextDefaultValueUpdate & {
    /** The ID of the custom field. */
    fieldId: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { fieldId, ...body } = params;
  return ctx.request({
    method: "put",
    path: "/rest/api/2/field/{fieldId}/context/defaultValue",
    pathParams: { fieldId },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get default values for a custom field grouped by context and issue type
 *
 * Returns a paginated list of default values grouped by custom field context.
 *
 * Each returned `ContextDefaultValuesBean` has a `contextId` and a `defaultValues` list of `IssueTypeDefaultValueBean` entries - one per issue-type-scoped default value configured for the context. An entry with `"isAnyIssueType": true` represents the catch-all default that applies to every issue type covered by the context that is not covered by a more specific entry; a non-null `issueTypeId` represents a default that only applies to that issue type.
 *
 * For contexts that have not been converted to the multiple-contexts data model, exactly one entry is returned per context with `isAnyIssueType=true`. For converted contexts, one entry is returned per configured per-issue-type default.
 *
 * The value object on each entry is the same polymorphic `CustomFieldContextDefaultValueBean` exposed by the deprecated `GET /defaultValue` endpoint - its concrete subtype depends on the custom field's type (see the list of supported types on that endpoint).
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the custom field, for example `customfield\_10000`.
 * @param params.contextId - The IDs of the contexts to return default values for. If omitted, default values for every context the custom field has are returned.
 * @param params.issueTypeId - The IDs of the issue types to restrict the returned per-issue-type default values to. If omitted, default values for every issue type are returned. This filter never removes the catch-all `isAnyIssueType` entry of a context.
 * @param params.startAt - The index of the first item to return in a page of results (page offset).
 * @param params.maxResults - The maximum number of items to return per page.
 * @returns Returned if the request is successful.
 */
export function getContextDefaultValues(
  ctx: ClientContext,
  params: {
    /** The ID of the custom field, for example `customfield\_10000`. */
    fieldId: string;
    /** The IDs of the contexts to return default values for. If omitted, default values for every context the custom field has are returned. */
    contextId?: number[];
    /** The IDs of the issue types to restrict the returned per-issue-type default values to. If omitted, default values for every issue type are returned. This filter never removes the catch-all `isAnyIssueType` entry of a context. */
    issueTypeId?: string[];
    /**
     * The index of the first item to return in a page of results (page offset).
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of items to return per page.
     *
     * @default 50
     * @format int32
     */
    maxResults?: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBeanContextDefaultValues> {
  const { fieldId, contextId, issueTypeId, startAt, maxResults } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/field/{fieldId}/context/defaultValues",
    pathParams: { fieldId },
    query: { contextId, issueTypeId, startAt, maxResults },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get issue types for custom field context
 *
 * Returns a [paginated](#pagination) list of context to issue type mappings for a custom field. Mappings are returned for all contexts or a list of contexts. Mappings are ordered first by context ID and then by issue type ID.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the custom field.
 * @param params.contextId - The ID of the context. To include multiple contexts, provide an ampersand-separated list. For example, `contextId=10001&contextId=10002`.
 * @param params.startAt - The index of the first item to return in a page of results (page offset).
 * @param params.maxResults - The maximum number of items to return per page.
 * @returns Returned if operation is successful.
 */
export function getIssueTypeMappingsForContexts(
  ctx: ClientContext,
  params: {
    /** The ID of the custom field. */
    fieldId: string;
    /** The ID of the context. To include multiple contexts, provide an ampersand-separated list. For example, `contextId=10001&contextId=10002`. */
    contextId?: number[];
    /**
     * The index of the first item to return in a page of results (page offset).
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of items to return per page.
     *
     * @default 50
     * @format int32
     */
    maxResults?: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBeanIssueTypeToContextMapping> {
  const { fieldId, contextId, startAt, maxResults } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/field/{fieldId}/context/issuetypemapping",
    pathParams: { fieldId },
    query: { contextId, startAt, maxResults },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get custom field contexts for projects and issue types
 *
 * Returns a [paginated](#pagination) list of project and issue type mappings and, for each mapping, the ID of a [custom field context](https://confluence.atlassian.com/x/k44fOw) that applies to the project and issue type.
 *
 * If there is no custom field context assigned to the project then, if present, the custom field context that applies to all projects is returned if it also applies to the issue type or all issue types. If a custom field context is not found, the returned custom field context ID is `null`.
 *
 * Duplicate project and issue type mappings cannot be provided in the request.
 *
 * The order of the returned values is the same as provided in the request.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the custom field.
 * @param params.startAt - The index of the first item to return in a page of results (page offset).
 * @param params.maxResults - The maximum number of items to return per page.
 * @returns Returned if the request is successful.
 */
export function getCustomFieldContextsForProjectsAndIssueTypes(
  ctx: ClientContext,
  params: ProjectIssueTypeMappings & {
    /** The ID of the custom field. */
    fieldId: string;
    /**
     * The index of the first item to return in a page of results (page offset).
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of items to return per page.
     *
     * @default 50
     * @format int32
     */
    maxResults?: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBeanContextForProjectAndIssueType> {
  const { fieldId, startAt, maxResults, ...body } = params;
  return ctx.request({
    method: "post",
    path: "/rest/api/2/field/{fieldId}/context/mapping",
    pathParams: { fieldId },
    query: { startAt, maxResults },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get project mappings for custom field context
 *
 * Returns a [paginated](#pagination) list of context to project mappings for a custom field. The result can be filtered by `contextId`. Otherwise, all mappings are returned. Invalid IDs are ignored.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the custom field, for example `customfield\_10000`.
 * @param params.contextId - The list of context IDs. To include multiple context, separate IDs with ampersand: `contextId=10000&contextId=10001`.
 * @param params.startAt - The index of the first item to return in a page of results (page offset).
 * @param params.maxResults - The maximum number of items to return per page.
 * @returns Returned if the request is successful.
 */
export function getProjectContextMapping(
  ctx: ClientContext,
  params: {
    /** The ID of the custom field, for example `customfield\_10000`. */
    fieldId: string;
    /** The list of context IDs. To include multiple context, separate IDs with ampersand: `contextId=10000&contextId=10001`. */
    contextId?: number[];
    /**
     * The index of the first item to return in a page of results (page offset).
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of items to return per page.
     *
     * @default 50
     * @format int32
     */
    maxResults?: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBeanCustomFieldContextProjectMapping> {
  const { fieldId, contextId, startAt, maxResults } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/field/{fieldId}/context/projectmapping",
    pathParams: { fieldId },
    query: { contextId, startAt, maxResults },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Update custom field context
 *
 * Updates a [ custom field context](https://confluence.atlassian.com/adminjiracloud/what-are-custom-field-contexts-991923859.html).
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the custom field.
 * @param params.contextId - The ID of the context.
 * @returns Returned if the context is updated.
 */
export function updateCustomFieldContext(
  ctx: ClientContext,
  params: CustomFieldContextUpdateDetails & {
    /** The ID of the custom field. */
    fieldId: string;
    /**
     * The ID of the context.
     *
     * @format int64
     */
    contextId: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { fieldId, contextId, ...body } = params;
  return ctx.request({
    method: "put",
    path: "/rest/api/2/field/{fieldId}/context/{contextId}",
    pathParams: { fieldId, contextId },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Delete custom field context
 *
 * Deletes a [ custom field context](https://confluence.atlassian.com/adminjiracloud/what-are-custom-field-contexts-991923859.html).
 *
 * This API will not allow removing the global context from April 2026. Instead, an HTTP 400 response will be returned. See [CHANGE-3019](https://developer.atlassian.com/changelog/#CHANGE-3019)
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the custom field.
 * @param params.contextId - The ID of the context.
 * @returns Returned if the context is deleted.
 */
export function deleteCustomFieldContext(
  ctx: ClientContext,
  params: {
    /** The ID of the custom field. */
    fieldId: string;
    /**
     * The ID of the context.
     *
     * @format int64
     */
    contextId: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { fieldId, contextId } = params;
  return ctx.request({
    method: "delete",
    path: "/rest/api/2/field/{fieldId}/context/{contextId}",
    pathParams: { fieldId, contextId },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Add issue types to context
 *
 * Adds issue types to a custom field context, appending the issue types to the issue types list.
 *
 * A custom field context without any issue types applies to all issue types. Adding issue types to such a custom field context would result in it applying to only the listed issue types.
 *
 * If any of the issue types exists in the custom field context, the operation fails and no issue types are added.
 *
 * This API will not allow adding issue types to the global context from April 2026. Instead, an HTTP 400 response will be returned. See [CHANGE-3019](https://developer.atlassian.com/changelog/#CHANGE-3019)
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the custom field.
 * @param params.contextId - The ID of the context.
 * @returns Returned if operation is successful.
 */
export function addIssueTypesToContext(
  ctx: ClientContext,
  params: IssueTypeIds & {
    /** The ID of the custom field. */
    fieldId: string;
    /**
     * The ID of the context.
     *
     * @format int64
     */
    contextId: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { fieldId, contextId, ...body } = params;
  return ctx.request({
    method: "put",
    path: "/rest/api/2/field/{fieldId}/context/{contextId}/issuetype",
    pathParams: { fieldId, contextId },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Remove issue types from context
 *
 * Removes issue types from a custom field context.
 *
 * A custom field context without any issue types applies to all issue types.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the custom field.
 * @param params.contextId - The ID of the context.
 * @returns Returned if operation is successful.
 */
export function removeIssueTypesFromContext(
  ctx: ClientContext,
  params: IssueTypeIds & {
    /** The ID of the custom field. */
    fieldId: string;
    /**
     * The ID of the context.
     *
     * @format int64
     */
    contextId: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { fieldId, contextId, ...body } = params;
  return ctx.request({
    method: "post",
    path: "/rest/api/2/field/{fieldId}/context/{contextId}/issuetype/remove",
    pathParams: { fieldId, contextId },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Assign custom field context to projects
 *
 * Assigns a custom field context to projects.
 *
 * If any project in the request is assigned to any context of the custom field, the operation fails.
 *
 * This API will not allow adding projects to the global context from April 2026. Instead, an HTTP 400 response will be returned. See [CHANGE-3019](https://developer.atlassian.com/changelog/#CHANGE-3019)
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the custom field.
 * @param params.contextId - The ID of the context.
 * @returns Returned if operation is successful.
 */
export function assignProjectsToCustomFieldContext(
  ctx: ClientContext,
  params: ProjectIds & {
    /** The ID of the custom field. */
    fieldId: string;
    /**
     * The ID of the context.
     *
     * @format int64
     */
    contextId: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { fieldId, contextId, ...body } = params;
  return ctx.request({
    method: "put",
    path: "/rest/api/2/field/{fieldId}/context/{contextId}/project",
    pathParams: { fieldId, contextId },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Remove custom field context from projects
 *
 * Removes a custom field context from projects.
 *
 * A custom field context without any projects applies to all projects. Removing all projects from a custom field context would result in it applying to all projects.
 *
 * If any project in the request is not assigned to the context, or the operation would result in two global contexts for the field, the operation fails.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the custom field.
 * @param params.contextId - The ID of the context.
 * @returns Returned if the custom field context is removed from the projects.
 */
export function removeCustomFieldContextFromProjects(
  ctx: ClientContext,
  params: ProjectIds & {
    /** The ID of the custom field. */
    fieldId: string;
    /**
     * The ID of the context.
     *
     * @format int64
     */
    contextId: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { fieldId, contextId, ...body } = params;
  return ctx.request({
    method: "post",
    path: "/rest/api/2/field/{fieldId}/context/{contextId}/project/remove",
    pathParams: { fieldId, contextId },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * This resource represents issue custom field contexts. Use it to:
 *
 *  *  get, create, update, and delete custom field contexts.
 *  *  get context to issue types and projects mappings.
 *  *  get custom field contexts for projects and issue types.
 *  *  assign custom field contexts to projects.
 *  *  remove custom field contexts from projects.
 *  *  add issue types to custom field contexts.
 */
export function createIssueCustomFieldContextsService(ctx: ClientContext) {
  return {
    /**
     * Get custom field contexts
     *
     * Returns a [paginated](#pagination) list of [ contexts](https://confluence.atlassian.com/adminjiracloud/what-are-custom-field-contexts-991923859.html) for a custom field. Contexts can be returned as follows:
     *
     *  *  With no other parameters set, all contexts.
     *  *  By defining `id` only, all contexts from the list of IDs.
     *  *  By defining `isAnyIssueType`, limit the list of contexts returned to either those that apply to all issue types (true) or those that apply to only a subset of issue types (false)
     *  *  By defining `isGlobalContext`, limit the list of contexts return to either those that apply to all projects (global contexts) (true) or those that apply to only a subset of projects (false).
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg). *Edit Workflow* [edit workflow permission](https://support.atlassian.com/jira-cloud-administration/docs/permissions-for-company-managed-projects/#Edit-Workflows)
     *
     * @param params.fieldId - The ID of the custom field.
     * @param params.isAnyIssueType - Whether to return contexts that apply to all issue types.
     * @param params.isGlobalContext - Whether to return contexts that apply to all projects.
     * @param params.contextId - The list of context IDs. To include multiple contexts, separate IDs with ampersand: `contextId=10000&contextId=10001`.
     * @param params.startAt - The index of the first item to return in a page of results (page offset).
     * @param params.maxResults - The maximum number of items to return per page.
     * @returns Returned if the request is successful.
     */
    getContextsForField(
      params: {
        /** The ID of the custom field. */
        fieldId: string;
        /** Whether to return contexts that apply to all issue types. */
        isAnyIssueType?: boolean;
        /** Whether to return contexts that apply to all projects. */
        isGlobalContext?: boolean;
        /** The list of context IDs. To include multiple contexts, separate IDs with ampersand: `contextId=10000&contextId=10001`. */
        contextId?: number[];
        /**
         * The index of the first item to return in a page of results (page offset).
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of items to return per page.
         *
         * @default 50
         * @format int32
         */
        maxResults?: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBeanCustomFieldContext> {
      return getContextsForField(ctx, params, options);
    },

    /**
     * Create custom field context
     *
     * Creates a custom field context.
     *
     * If `projectIds` is empty, a global context is created. A global context is one that applies to all project. If `issueTypeIds` is empty, the context applies to all issue types.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the custom field.
     * @returns Returned if the custom field context is created.
     */
    createCustomFieldContext(
      params: CreateCustomFieldContext & {
        /** The ID of the custom field. */
        fieldId: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<CreateCustomFieldContext> {
      return createCustomFieldContext(ctx, params, options);
    },

    /**
     * Get custom field contexts default values
     *
     * Returns a [paginated](#pagination) list of defaults for a custom field. The results can be filtered by `contextId`, otherwise all values are returned. If no defaults are set for a context, nothing is returned.
     * The returned object depends on type of the custom field:
     *
     *  *  `CustomFieldContextDefaultValueDate` (type `datepicker`) for date fields.
     *  *  `CustomFieldContextDefaultValueDateTime` (type `datetimepicker`) for date-time fields.
     *  *  `CustomFieldContextDefaultValueSingleOption` (type `option.single`) for single choice select lists and radio buttons.
     *  *  `CustomFieldContextDefaultValueMultipleOption` (type `option.multiple`) for multiple choice select lists and checkboxes.
     *  *  `CustomFieldContextDefaultValueCascadingOption` (type `option.cascading`) for cascading select lists.
     *  *  `CustomFieldContextSingleUserPickerDefaults` (type `single.user.select`) for single users.
     *  *  `CustomFieldContextDefaultValueMultiUserPicker` (type `multi.user.select`) for user lists.
     *  *  `CustomFieldContextDefaultValueSingleGroupPicker` (type `grouppicker.single`) for single choice group pickers.
     *  *  `CustomFieldContextDefaultValueMultipleGroupPicker` (type `grouppicker.multiple`) for multiple choice group pickers.
     *  *  `CustomFieldContextDefaultValueURL` (type `url`) for URLs.
     *  *  `CustomFieldContextDefaultValueProject` (type `project`) for project pickers.
     *  *  `CustomFieldContextDefaultValueFloat` (type `float`) for floats (floating-point numbers).
     *  *  `CustomFieldContextDefaultValueLabels` (type `labels`) for labels.
     *  *  `CustomFieldContextDefaultValueTextField` (type `textfield`) for text fields.
     *  *  `CustomFieldContextDefaultValueTextArea` (type `textarea`) for text area fields.
     *  *  `CustomFieldContextDefaultValueReadOnly` (type `readonly`) for read only (text) fields.
     *  *  `CustomFieldContextDefaultValueMultipleVersion` (type `version.multiple`) for single choice version pickers.
     *  *  `CustomFieldContextDefaultValueSingleVersion` (type `version.single`) for multiple choice version pickers.
     *
     * Forge custom fields [types](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field-type/#data-types) are also supported, returning:
     *
     *  *  `CustomFieldContextDefaultValueForgeStringFieldBean` (type `forge.string`) for Forge string fields.
     *  *  `CustomFieldContextDefaultValueForgeMultiStringFieldBean` (type `forge.string.list`) for Forge string collection fields.
     *  *  `CustomFieldContextDefaultValueForgeObjectFieldBean` (type `forge.object`) for Forge object fields.
     *  *  `CustomFieldContextDefaultValueForgeDateTimeFieldBean` (type `forge.datetime`) for Forge date-time fields.
     *  *  `CustomFieldContextDefaultValueForgeGroupFieldBean` (type `forge.group`) for Forge group fields.
     *  *  `CustomFieldContextDefaultValueForgeMultiGroupFieldBean` (type `forge.group.list`) for Forge group collection fields.
     *  *  `CustomFieldContextDefaultValueForgeNumberFieldBean` (type `forge.number`) for Forge number fields.
     *  *  `CustomFieldContextDefaultValueForgeUserFieldBean` (type `forge.user`) for Forge user fields.
     *  *  `CustomFieldContextDefaultValueForgeMultiUserFieldBean` (type `forge.user.list`) for Forge user collection fields.
     *
     * **Deprecated:** This API is deprecated and will be removed in October 2026. A replacement API that supports multiple default values per issue type within a context is coming soon. See the deprecation notice [CHANGE-3082](https://developer.atlassian.com/cloud/jira/platform/changelog/#CHANGE-3082) for more details.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the custom field, for example `customfield\_10000`.
     * @param params.contextId - The IDs of the contexts.
     * @param params.startAt - The index of the first item to return in a page of results (page offset).
     * @param params.maxResults - The maximum number of items to return per page.
     * @returns Returned if the request is successful.
     * @deprecated
     */
    getDefaultValues(
      params: {
        /** The ID of the custom field, for example `customfield\_10000`. */
        fieldId: string;
        /** The IDs of the contexts. */
        contextId?: number[];
        /**
         * The index of the first item to return in a page of results (page offset).
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of items to return per page.
         *
         * @default 50
         * @format int32
         */
        maxResults?: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBeanCustomFieldContextDefaultValue> {
      return getDefaultValues(ctx, params, options);
    },

    /**
     * Set custom field contexts default values
     *
     * Sets default for contexts of a custom field. Default are defined using these objects:
     *
     *  *  `CustomFieldContextDefaultValueDate` (type `datepicker`) for date fields.
     *  *  `CustomFieldContextDefaultValueDateTime` (type `datetimepicker`) for date-time fields.
     *  *  `CustomFieldContextDefaultValueSingleOption` (type `option.single`) for single choice select lists and radio buttons.
     *  *  `CustomFieldContextDefaultValueMultipleOption` (type `option.multiple`) for multiple choice select lists and checkboxes.
     *  *  `CustomFieldContextDefaultValueCascadingOption` (type `option.cascading`) for cascading select lists.
     *  *  `CustomFieldContextSingleUserPickerDefaults` (type `single.user.select`) for single users.
     *  *  `CustomFieldContextDefaultValueMultiUserPicker` (type `multi.user.select`) for user lists.
     *  *  `CustomFieldContextDefaultValueSingleGroupPicker` (type `grouppicker.single`) for single choice group pickers.
     *  *  `CustomFieldContextDefaultValueMultipleGroupPicker` (type `grouppicker.multiple`) for multiple choice group pickers.
     *  *  `CustomFieldContextDefaultValueURL` (type `url`) for URLs.
     *  *  `CustomFieldContextDefaultValueProject` (type `project`) for project pickers.
     *  *  `CustomFieldContextDefaultValueFloat` (type `float`) for floats (floating-point numbers).
     *  *  `CustomFieldContextDefaultValueLabels` (type `labels`) for labels.
     *  *  `CustomFieldContextDefaultValueTextField` (type `textfield`) for text fields.
     *  *  `CustomFieldContextDefaultValueTextArea` (type `textarea`) for text area fields.
     *  *  `CustomFieldContextDefaultValueReadOnly` (type `readonly`) for read only (text) fields.
     *  *  `CustomFieldContextDefaultValueMultipleVersion` (type `version.multiple`) for single choice version pickers.
     *  *  `CustomFieldContextDefaultValueSingleVersion` (type `version.single`) for multiple choice version pickers.
     *
     * Forge custom fields [types](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field-type/#data-types) are also supported, returning:
     *
     *  *  `CustomFieldContextDefaultValueForgeStringFieldBean` (type `forge.string`) for Forge string fields.
     *  *  `CustomFieldContextDefaultValueForgeMultiStringFieldBean` (type `forge.string.list`) for Forge string collection fields.
     *  *  `CustomFieldContextDefaultValueForgeObjectFieldBean` (type `forge.object`) for Forge object fields.
     *  *  `CustomFieldContextDefaultValueForgeDateTimeFieldBean` (type `forge.datetime`) for Forge date-time fields.
     *  *  `CustomFieldContextDefaultValueForgeGroupFieldBean` (type `forge.group`) for Forge group fields.
     *  *  `CustomFieldContextDefaultValueForgeMultiGroupFieldBean` (type `forge.group.list`) for Forge group collection fields.
     *  *  `CustomFieldContextDefaultValueForgeNumberFieldBean` (type `forge.number`) for Forge number fields.
     *  *  `CustomFieldContextDefaultValueForgeUserFieldBean` (type `forge.user`) for Forge user fields.
     *  *  `CustomFieldContextDefaultValueForgeMultiUserFieldBean` (type `forge.user.list`) for Forge user collection fields.
     *
     * Only one type of default object can be included in a request. To remove a default for a context, set the default parameter to `null`.
     *
     * **Deprecated:** This API is deprecated and will be removed in October 2026. A replacement API that supports multiple default values per issue type within a context is coming soon. See the deprecation notice [CHANGE-3082](https://developer.atlassian.com/cloud/jira/platform/changelog/#CHANGE-3082) for more details.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the custom field.
     * @returns Returned if operation is successful.
     * @deprecated
     */
    setDefaultValues(
      params: CustomFieldContextDefaultValueUpdate & {
        /** The ID of the custom field. */
        fieldId: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return setDefaultValues(ctx, params, options);
    },

    /**
     * Get default values for a custom field grouped by context and issue type
     *
     * Returns a paginated list of default values grouped by custom field context.
     *
     * Each returned `ContextDefaultValuesBean` has a `contextId` and a `defaultValues` list of `IssueTypeDefaultValueBean` entries - one per issue-type-scoped default value configured for the context. An entry with `"isAnyIssueType": true` represents the catch-all default that applies to every issue type covered by the context that is not covered by a more specific entry; a non-null `issueTypeId` represents a default that only applies to that issue type.
     *
     * For contexts that have not been converted to the multiple-contexts data model, exactly one entry is returned per context with `isAnyIssueType=true`. For converted contexts, one entry is returned per configured per-issue-type default.
     *
     * The value object on each entry is the same polymorphic `CustomFieldContextDefaultValueBean` exposed by the deprecated `GET /defaultValue` endpoint - its concrete subtype depends on the custom field's type (see the list of supported types on that endpoint).
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the custom field, for example `customfield\_10000`.
     * @param params.contextId - The IDs of the contexts to return default values for. If omitted, default values for every context the custom field has are returned.
     * @param params.issueTypeId - The IDs of the issue types to restrict the returned per-issue-type default values to. If omitted, default values for every issue type are returned. This filter never removes the catch-all `isAnyIssueType` entry of a context.
     * @param params.startAt - The index of the first item to return in a page of results (page offset).
     * @param params.maxResults - The maximum number of items to return per page.
     * @returns Returned if the request is successful.
     */
    getContextDefaultValues(
      params: {
        /** The ID of the custom field, for example `customfield\_10000`. */
        fieldId: string;
        /** The IDs of the contexts to return default values for. If omitted, default values for every context the custom field has are returned. */
        contextId?: number[];
        /** The IDs of the issue types to restrict the returned per-issue-type default values to. If omitted, default values for every issue type are returned. This filter never removes the catch-all `isAnyIssueType` entry of a context. */
        issueTypeId?: string[];
        /**
         * The index of the first item to return in a page of results (page offset).
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of items to return per page.
         *
         * @default 50
         * @format int32
         */
        maxResults?: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBeanContextDefaultValues> {
      return getContextDefaultValues(ctx, params, options);
    },

    /**
     * Get issue types for custom field context
     *
     * Returns a [paginated](#pagination) list of context to issue type mappings for a custom field. Mappings are returned for all contexts or a list of contexts. Mappings are ordered first by context ID and then by issue type ID.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the custom field.
     * @param params.contextId - The ID of the context. To include multiple contexts, provide an ampersand-separated list. For example, `contextId=10001&contextId=10002`.
     * @param params.startAt - The index of the first item to return in a page of results (page offset).
     * @param params.maxResults - The maximum number of items to return per page.
     * @returns Returned if operation is successful.
     */
    getIssueTypeMappingsForContexts(
      params: {
        /** The ID of the custom field. */
        fieldId: string;
        /** The ID of the context. To include multiple contexts, provide an ampersand-separated list. For example, `contextId=10001&contextId=10002`. */
        contextId?: number[];
        /**
         * The index of the first item to return in a page of results (page offset).
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of items to return per page.
         *
         * @default 50
         * @format int32
         */
        maxResults?: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBeanIssueTypeToContextMapping> {
      return getIssueTypeMappingsForContexts(ctx, params, options);
    },

    /**
     * Get custom field contexts for projects and issue types
     *
     * Returns a [paginated](#pagination) list of project and issue type mappings and, for each mapping, the ID of a [custom field context](https://confluence.atlassian.com/x/k44fOw) that applies to the project and issue type.
     *
     * If there is no custom field context assigned to the project then, if present, the custom field context that applies to all projects is returned if it also applies to the issue type or all issue types. If a custom field context is not found, the returned custom field context ID is `null`.
     *
     * Duplicate project and issue type mappings cannot be provided in the request.
     *
     * The order of the returned values is the same as provided in the request.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the custom field.
     * @param params.startAt - The index of the first item to return in a page of results (page offset).
     * @param params.maxResults - The maximum number of items to return per page.
     * @returns Returned if the request is successful.
     */
    getCustomFieldContextsForProjectsAndIssueTypes(
      params: ProjectIssueTypeMappings & {
        /** The ID of the custom field. */
        fieldId: string;
        /**
         * The index of the first item to return in a page of results (page offset).
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of items to return per page.
         *
         * @default 50
         * @format int32
         */
        maxResults?: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBeanContextForProjectAndIssueType> {
      return getCustomFieldContextsForProjectsAndIssueTypes(ctx, params, options);
    },

    /**
     * Get project mappings for custom field context
     *
     * Returns a [paginated](#pagination) list of context to project mappings for a custom field. The result can be filtered by `contextId`. Otherwise, all mappings are returned. Invalid IDs are ignored.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the custom field, for example `customfield\_10000`.
     * @param params.contextId - The list of context IDs. To include multiple context, separate IDs with ampersand: `contextId=10000&contextId=10001`.
     * @param params.startAt - The index of the first item to return in a page of results (page offset).
     * @param params.maxResults - The maximum number of items to return per page.
     * @returns Returned if the request is successful.
     */
    getProjectContextMapping(
      params: {
        /** The ID of the custom field, for example `customfield\_10000`. */
        fieldId: string;
        /** The list of context IDs. To include multiple context, separate IDs with ampersand: `contextId=10000&contextId=10001`. */
        contextId?: number[];
        /**
         * The index of the first item to return in a page of results (page offset).
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of items to return per page.
         *
         * @default 50
         * @format int32
         */
        maxResults?: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBeanCustomFieldContextProjectMapping> {
      return getProjectContextMapping(ctx, params, options);
    },

    /**
     * Update custom field context
     *
     * Updates a [ custom field context](https://confluence.atlassian.com/adminjiracloud/what-are-custom-field-contexts-991923859.html).
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the custom field.
     * @param params.contextId - The ID of the context.
     * @returns Returned if the context is updated.
     */
    updateCustomFieldContext(
      params: CustomFieldContextUpdateDetails & {
        /** The ID of the custom field. */
        fieldId: string;
        /**
         * The ID of the context.
         *
         * @format int64
         */
        contextId: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return updateCustomFieldContext(ctx, params, options);
    },

    /**
     * Delete custom field context
     *
     * Deletes a [ custom field context](https://confluence.atlassian.com/adminjiracloud/what-are-custom-field-contexts-991923859.html).
     *
     * This API will not allow removing the global context from April 2026. Instead, an HTTP 400 response will be returned. See [CHANGE-3019](https://developer.atlassian.com/changelog/#CHANGE-3019)
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the custom field.
     * @param params.contextId - The ID of the context.
     * @returns Returned if the context is deleted.
     */
    deleteCustomFieldContext(
      params: {
        /** The ID of the custom field. */
        fieldId: string;
        /**
         * The ID of the context.
         *
         * @format int64
         */
        contextId: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return deleteCustomFieldContext(ctx, params, options);
    },

    /**
     * Add issue types to context
     *
     * Adds issue types to a custom field context, appending the issue types to the issue types list.
     *
     * A custom field context without any issue types applies to all issue types. Adding issue types to such a custom field context would result in it applying to only the listed issue types.
     *
     * If any of the issue types exists in the custom field context, the operation fails and no issue types are added.
     *
     * This API will not allow adding issue types to the global context from April 2026. Instead, an HTTP 400 response will be returned. See [CHANGE-3019](https://developer.atlassian.com/changelog/#CHANGE-3019)
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the custom field.
     * @param params.contextId - The ID of the context.
     * @returns Returned if operation is successful.
     */
    addIssueTypesToContext(
      params: IssueTypeIds & {
        /** The ID of the custom field. */
        fieldId: string;
        /**
         * The ID of the context.
         *
         * @format int64
         */
        contextId: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return addIssueTypesToContext(ctx, params, options);
    },

    /**
     * Remove issue types from context
     *
     * Removes issue types from a custom field context.
     *
     * A custom field context without any issue types applies to all issue types.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the custom field.
     * @param params.contextId - The ID of the context.
     * @returns Returned if operation is successful.
     */
    removeIssueTypesFromContext(
      params: IssueTypeIds & {
        /** The ID of the custom field. */
        fieldId: string;
        /**
         * The ID of the context.
         *
         * @format int64
         */
        contextId: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return removeIssueTypesFromContext(ctx, params, options);
    },

    /**
     * Assign custom field context to projects
     *
     * Assigns a custom field context to projects.
     *
     * If any project in the request is assigned to any context of the custom field, the operation fails.
     *
     * This API will not allow adding projects to the global context from April 2026. Instead, an HTTP 400 response will be returned. See [CHANGE-3019](https://developer.atlassian.com/changelog/#CHANGE-3019)
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the custom field.
     * @param params.contextId - The ID of the context.
     * @returns Returned if operation is successful.
     */
    assignProjectsToCustomFieldContext(
      params: ProjectIds & {
        /** The ID of the custom field. */
        fieldId: string;
        /**
         * The ID of the context.
         *
         * @format int64
         */
        contextId: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return assignProjectsToCustomFieldContext(ctx, params, options);
    },

    /**
     * Remove custom field context from projects
     *
     * Removes a custom field context from projects.
     *
     * A custom field context without any projects applies to all projects. Removing all projects from a custom field context would result in it applying to all projects.
     *
     * If any project in the request is not assigned to the context, or the operation would result in two global contexts for the field, the operation fails.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the custom field.
     * @param params.contextId - The ID of the context.
     * @returns Returned if the custom field context is removed from the projects.
     */
    removeCustomFieldContextFromProjects(
      params: ProjectIds & {
        /** The ID of the custom field. */
        fieldId: string;
        /**
         * The ID of the context.
         *
         * @format int64
         */
        contextId: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return removeCustomFieldContextFromProjects(ctx, params, options);
    },
  };
}
