// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

import type { ClientContext } from "../../client/index.ts";
import type {
  CustomFieldDefinitionJsonBean,
  FieldDetails,
  PageBean2ProjectFieldBean,
  PageBeanContext,
  PageBeanField,
  PageBeanFieldProjectAssociation,
  UpdateCustomFieldDetails,
} from "../types/index.ts";

/**
 * Get fields
 *
 * Returns system and custom issue fields according to the following rules:
 *
 *  *  Fields that cannot be added to the issue navigator are always returned.
 *  *  Fields that cannot be placed on an issue screen are always returned.
 *  *  Fields that depend on global Jira settings are only returned if the setting is enabled. That is, timetracking fields, subtasks, votes, and watches.
 *  *  Fields that are not associated to any used field configurations or screens are not returned.
 *  *  For all other fields, this operation only returns the fields that the user has permission to view (that is, the field is used in at least one project that the user has *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for.)
 *
 * This operation can be accessed anonymously.
 *
 * **[Permissions](#permissions) required:** None.
 *
 * @returns Returned if the request is successful.
 */
export function getFields(
  ctx: ClientContext,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<FieldDetails[]> {
  return ctx.request({
    method: "get",
    path: "/rest/api/2/field",
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Create custom field
 *
 * Creates a custom field.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @returns Returned if the custom field is created.
 */
export function createCustomField(
  ctx: ClientContext,
  params: CustomFieldDefinitionJsonBean,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<FieldDetails> {
  return ctx.request({
    method: "post",
    path: "/rest/api/2/field",
    headers: options?.headers,
    body: params,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get fields paginated
 *
 * Returns a [paginated](#pagination) list of fields for Classic Jira projects. The list can include:
 *
 *  *  all fields
 *  *  specific fields, by defining `id`
 *  *  fields that contain a string in the field name or description, by defining `query`
 *  *  specific fields that contain a string in the field name or description, by defining `id` and `query`
 *
 * Use `type` must be set to `custom` to show custom fields only.
 *
 * **[Permissions](#permissions) required:** Permission to access Jira.
 *
 * @param params.startAt - The index of the first item to return in a page of results (page offset).
 * @param params.maxResults - The maximum number of items to return per page.
 * @param params.type - The type of fields to search.
 * @param params.id - The IDs of the custom fields to return or, where `query` is specified, filter.
 * @param params.query - String used to perform a case-insensitive partial match with field names or descriptions.
 * @param params.orderBy - [Order](#ordering) the results by: *  `contextsCount` sorts by the number of contexts related to a field *  `lastUsed` sorts by the date when the value of the field last changed *  `name` sorts by the field name *  `screensCount` sorts by the number of screens related to a field
 * @param params.expand - Use [expand](#expansion) to include additional information in the response. This parameter accepts a comma-separated list. Expand options include: *  `key` returns the key for each field *  `stableId` returns the stableId for each field *  `lastUsed` returns the date when the value of the field last changed *  `screensCount` returns the number of screens related to a field *  `contextsCount` returns the number of contexts related to a field *  `isLocked` returns information about whether the field is locked *  `searcherKey` returns the searcher key for each custom field
 * @param params.projectIds - The IDs of the projects to filter the fields by. Fields belonging to project Ids that the user does not have access to will not be returned
 * @returns Returned if the request is successful.
 */
export function getFieldsPaginated(
  ctx: ClientContext,
  params?: {
    /**
     * The index of the first item to return in a page of results (page offset).
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of items to return per page.
     *
     * @default 50
     * @format int32
     */
    maxResults?: number;
    /** The type of fields to search. */
    type?: ("custom" | "system")[];
    /** The IDs of the custom fields to return or, where `query` is specified, filter. */
    id?: string[];
    /** String used to perform a case-insensitive partial match with field names or descriptions. */
    query?: string;
    /**
     * [Order](#ordering) the results by:
     *
     *  *  `contextsCount` sorts by the number of contexts related to a field
     *  *  `lastUsed` sorts by the date when the value of the field last changed
     *  *  `name` sorts by the field name
     *  *  `screensCount` sorts by the number of screens related to a field
     */
    orderBy?:
      | "contextsCount"
      | "-contextsCount"
      | "+contextsCount"
      | "lastUsed"
      | "-lastUsed"
      | "+lastUsed"
      | "name"
      | "-name"
      | "+name"
      | "screensCount"
      | "-screensCount"
      | "+screensCount"
      | "projectsCount"
      | "-projectsCount"
      | "+projectsCount";
    /**
     * Use [expand](#expansion) to include additional information in the response. This parameter accepts a comma-separated list. Expand options include:
     *
     *  *  `key` returns the key for each field
     *  *  `stableId` returns the stableId for each field
     *  *  `lastUsed` returns the date when the value of the field last changed
     *  *  `screensCount` returns the number of screens related to a field
     *  *  `contextsCount` returns the number of contexts related to a field
     *  *  `isLocked` returns information about whether the field is locked
     *  *  `searcherKey` returns the searcher key for each custom field
     */
    expand?: string;
    /** The IDs of the projects to filter the fields by. Fields belonging to project Ids that the user does not have access to will not be returned */
    projectIds?: number[];
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBeanField> {
  const { startAt, maxResults, type, id, query, orderBy, expand, projectIds } = params ?? {};
  return ctx.request({
    method: "get",
    path: "/rest/api/2/field/search",
    query: { startAt, maxResults, type, id, query, orderBy, expand, projectIds },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get fields in trash paginated
 *
 * Returns a [paginated](#pagination) list of fields in the trash. The list may be restricted to fields whose field name or description partially match a string.
 *
 * Only custom fields can be queried, `type` must be set to `custom`.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.startAt - The index of the first item to return in a page of results (page offset).
 * @param params.maxResults - The maximum number of items to return per page.
 * @param params.query - String used to perform a case-insensitive partial match with field names or descriptions.
 * @param params.orderBy - [Order](#ordering) the results by a field: *  `name` sorts by the field name *  `trashDate` sorts by the date the field was moved to the trash *  `plannedDeletionDate` sorts by the planned deletion date
 * @returns Returned if the request is successful.
 */
export function getTrashedFieldsPaginated(
  ctx: ClientContext,
  params?: {
    /**
     * The index of the first item to return in a page of results (page offset).
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of items to return per page.
     *
     * @default 50
     * @format int32
     */
    maxResults?: number;
    id?: string[];
    /** String used to perform a case-insensitive partial match with field names or descriptions. */
    query?: string;
    expand?:
      | "name"
      | "-name"
      | "+name"
      | "trashDate"
      | "-trashDate"
      | "+trashDate"
      | "plannedDeletionDate"
      | "-plannedDeletionDate"
      | "+plannedDeletionDate"
      | "projectsCount"
      | "-projectsCount"
      | "+projectsCount";
    /**
     * [Order](#ordering) the results by a field:
     *
     *  *  `name` sorts by the field name
     *  *  `trashDate` sorts by the date the field was moved to the trash
     *  *  `plannedDeletionDate` sorts by the planned deletion date
     */
    orderBy?: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBeanField> {
  const { startAt, maxResults, id, query, expand, orderBy } = params ?? {};
  return ctx.request({
    method: "get",
    path: "/rest/api/2/field/search/trashed",
    query: { startAt, maxResults, id, query, expand, orderBy },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Update custom field
 *
 * Updates a custom field.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the custom field.
 * @returns Returned if the request is successful.
 */
export function updateCustomField(
  ctx: ClientContext,
  params: UpdateCustomFieldDetails & {
    /** The ID of the custom field. */
    fieldId: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { fieldId, ...body } = params;
  return ctx.request({
    method: "put",
    path: "/rest/api/2/field/{fieldId}",
    pathParams: { fieldId },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get field project associations
 *
 * Returns a [paginated](#pagination) list of project associations for the given custom field. Each association contains the ID of a project the field is associated with.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the field, for example `customfield_10000`.
 * @param params.startAt - The index of the first item to return in a page of results (page offset).
 * @param params.maxResults - The maximum number of items to return per page.
 * @returns Returned if the request is successful.
 */
export function getFieldProjectAssociations(
  ctx: ClientContext,
  params: {
    /** The ID of the field, for example `customfield_10000`. */
    fieldId: string;
    /**
     * The index of the first item to return in a page of results (page offset).
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of items to return per page.
     *
     * @default 50
     * @format int32
     */
    maxResults?: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBeanFieldProjectAssociation> {
  const { fieldId, startAt, maxResults } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/field/{fieldId}/association/project",
    pathParams: { fieldId },
    query: { startAt, maxResults },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get contexts for a field
 *
 * Returns a [paginated](#pagination) list of the contexts a field is used in. Deprecated, use [ Get custom field contexts](#api-rest-api-2-field-fieldId-context-get).
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.fieldId - The ID of the field to return contexts for.
 * @param params.startAt - The index of the first item to return in a page of results (page offset).
 * @param params.maxResults - The maximum number of items to return per page.
 * @returns Returned if the request is successful.
 * @deprecated
 */
export function getContextsForFieldDeprecated(
  ctx: ClientContext,
  params: {
    /** The ID of the field to return contexts for. */
    fieldId: string;
    /**
     * The index of the first item to return in a page of results (page offset).
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of items to return per page.
     *
     * @default 20
     * @format int32
     */
    maxResults?: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBeanContext> {
  const { fieldId, startAt, maxResults } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/field/{fieldId}/contexts",
    pathParams: { fieldId },
    query: { startAt, maxResults },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Delete custom field
 *
 * Deletes a custom field. The custom field is deleted whether it is in the trash or not. See [Edit or delete a custom field](https://confluence.atlassian.com/x/Z44fOw) for more information on trashing and deleting custom fields.
 *
 * This operation is [asynchronous](#async). Follow the `location` link in the response to determine the status of the task and use [Get task](#api-rest-api-2-task-taskId-get) to obtain subsequent updates.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.id - The ID of a custom field.
 */
export function deleteCustomField(
  ctx: ClientContext,
  params: {
    /** The ID of a custom field. */
    id: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<void> {
  const { id } = params;
  return ctx.request({
    method: "delete",
    path: "/rest/api/2/field/{id}",
    pathParams: { id },
    headers: options?.headers,
    responseType: "void",
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Restore custom field from trash
 *
 * Restores a custom field from trash. See [Edit or delete a custom field](https://confluence.atlassian.com/x/Z44fOw) for more information on trashing and deleting custom fields.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.id - The ID of a custom field.
 * @returns Returned if the request is successful.
 */
export function restoreCustomField(
  ctx: ClientContext,
  params: {
    /** The ID of a custom field. */
    id: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { id } = params;
  return ctx.request({
    method: "post",
    path: "/rest/api/2/field/{id}/restore",
    pathParams: { id },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Move custom field to trash
 *
 * Moves a custom field to trash. See [Edit or delete a custom field](https://confluence.atlassian.com/x/Z44fOw) for more information on trashing and deleting custom fields.
 *
 * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.id - The ID of a custom field.
 * @returns Returned if the request is successful.
 */
export function trashCustomField(
  ctx: ClientContext,
  params: {
    /** The ID of a custom field. */
    id: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { id } = params;
  return ctx.request({
    method: "post",
    path: "/rest/api/2/field/{id}/trash",
    pathParams: { id },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get fields for projects
 *
 * Returns a [paginated](#pagination) list of fields for the requested projects and work types.
 *
 * Only fields that are available for the specified combination of projects and work types are returned. This endpoint allows filtering to specific fields if field IDs are provided.
 *
 * **[Permissions](#permissions) required:** Permission to access Jira.
 *
 * @param params.startAt - The index of the first item to return in a page of results (page offset).
 * @param params.maxResults - The maximum number of items to return per page.
 * @param params.projectId - The IDs of projects to return fields for.
 * @param params.workTypeId - The IDs of work types (issue types) to return fields for.
 * @param params.fieldId - The IDs of fields to return. If not provided, all fields are returned.
 * @returns Returned if the request is successful.
 */
export function getProjectFields(
  ctx: ClientContext,
  params: {
    /**
     * The index of the first item to return in a page of results (page offset).
     *
     * @default 0
     * @format int64
     */
    startAt?: number;
    /**
     * The maximum number of items to return per page.
     *
     * @default 50
     * @format int32
     */
    maxResults?: number;
    /**
     * The IDs of projects to return fields for.
     *
     * @example
     * ```json
     * [
     *   10000,
     *   10001
     * ]
     * ```
     */
    projectId: number[];
    /**
     * The IDs of work types (issue types) to return fields for.
     *
     * @example
     * ```json
     * [
     *   10000,
     *   10001
     * ]
     * ```
     */
    workTypeId: number[];
    /**
     * The IDs of fields to return. If not provided, all fields are returned.
     *
     * @example
     * ```json
     * [
     *   "summary",
     *   "description"
     * ]
     * ```
     */
    fieldId?: string[];
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<PageBean2ProjectFieldBean> {
  const { startAt, maxResults, projectId, workTypeId, fieldId } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/projects/fields",
    query: { startAt, maxResults, projectId, workTypeId, fieldId },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/** This resource represents issue fields, both system and custom fields. Use it to get fields, field configurations, and create custom fields. */
export function createIssueFieldsService(ctx: ClientContext) {
  return {
    /**
     * Get fields
     *
     * Returns system and custom issue fields according to the following rules:
     *
     *  *  Fields that cannot be added to the issue navigator are always returned.
     *  *  Fields that cannot be placed on an issue screen are always returned.
     *  *  Fields that depend on global Jira settings are only returned if the setting is enabled. That is, timetracking fields, subtasks, votes, and watches.
     *  *  Fields that are not associated to any used field configurations or screens are not returned.
     *  *  For all other fields, this operation only returns the fields that the user has permission to view (that is, the field is used in at least one project that the user has *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for.)
     *
     * This operation can be accessed anonymously.
     *
     * **[Permissions](#permissions) required:** None.
     *
     * @returns Returned if the request is successful.
     */
    getFields(options?: {
      headers?: Record<string, string | number | boolean>;
      signal?: AbortSignal;
      extensions?: Record<string, unknown>;
    }): Promise<FieldDetails[]> {
      return getFields(ctx, options);
    },

    /**
     * Create custom field
     *
     * Creates a custom field.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @returns Returned if the custom field is created.
     */
    createCustomField(
      params: CustomFieldDefinitionJsonBean,
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<FieldDetails> {
      return createCustomField(ctx, params, options);
    },

    /**
     * Get fields paginated
     *
     * Returns a [paginated](#pagination) list of fields for Classic Jira projects. The list can include:
     *
     *  *  all fields
     *  *  specific fields, by defining `id`
     *  *  fields that contain a string in the field name or description, by defining `query`
     *  *  specific fields that contain a string in the field name or description, by defining `id` and `query`
     *
     * Use `type` must be set to `custom` to show custom fields only.
     *
     * **[Permissions](#permissions) required:** Permission to access Jira.
     *
     * @param params.startAt - The index of the first item to return in a page of results (page offset).
     * @param params.maxResults - The maximum number of items to return per page.
     * @param params.type - The type of fields to search.
     * @param params.id - The IDs of the custom fields to return or, where `query` is specified, filter.
     * @param params.query - String used to perform a case-insensitive partial match with field names or descriptions.
     * @param params.orderBy - [Order](#ordering) the results by: *  `contextsCount` sorts by the number of contexts related to a field *  `lastUsed` sorts by the date when the value of the field last changed *  `name` sorts by the field name *  `screensCount` sorts by the number of screens related to a field
     * @param params.expand - Use [expand](#expansion) to include additional information in the response. This parameter accepts a comma-separated list. Expand options include: *  `key` returns the key for each field *  `stableId` returns the stableId for each field *  `lastUsed` returns the date when the value of the field last changed *  `screensCount` returns the number of screens related to a field *  `contextsCount` returns the number of contexts related to a field *  `isLocked` returns information about whether the field is locked *  `searcherKey` returns the searcher key for each custom field
     * @param params.projectIds - The IDs of the projects to filter the fields by. Fields belonging to project Ids that the user does not have access to will not be returned
     * @returns Returned if the request is successful.
     */
    getFieldsPaginated(
      params?: {
        /**
         * The index of the first item to return in a page of results (page offset).
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of items to return per page.
         *
         * @default 50
         * @format int32
         */
        maxResults?: number;
        /** The type of fields to search. */
        type?: ("custom" | "system")[];
        /** The IDs of the custom fields to return or, where `query` is specified, filter. */
        id?: string[];
        /** String used to perform a case-insensitive partial match with field names or descriptions. */
        query?: string;
        /**
         * [Order](#ordering) the results by:
         *
         *  *  `contextsCount` sorts by the number of contexts related to a field
         *  *  `lastUsed` sorts by the date when the value of the field last changed
         *  *  `name` sorts by the field name
         *  *  `screensCount` sorts by the number of screens related to a field
         */
        orderBy?:
          | "contextsCount"
          | "-contextsCount"
          | "+contextsCount"
          | "lastUsed"
          | "-lastUsed"
          | "+lastUsed"
          | "name"
          | "-name"
          | "+name"
          | "screensCount"
          | "-screensCount"
          | "+screensCount"
          | "projectsCount"
          | "-projectsCount"
          | "+projectsCount";
        /**
         * Use [expand](#expansion) to include additional information in the response. This parameter accepts a comma-separated list. Expand options include:
         *
         *  *  `key` returns the key for each field
         *  *  `stableId` returns the stableId for each field
         *  *  `lastUsed` returns the date when the value of the field last changed
         *  *  `screensCount` returns the number of screens related to a field
         *  *  `contextsCount` returns the number of contexts related to a field
         *  *  `isLocked` returns information about whether the field is locked
         *  *  `searcherKey` returns the searcher key for each custom field
         */
        expand?: string;
        /** The IDs of the projects to filter the fields by. Fields belonging to project Ids that the user does not have access to will not be returned */
        projectIds?: number[];
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBeanField> {
      return getFieldsPaginated(ctx, params, options);
    },

    /**
     * Get fields in trash paginated
     *
     * Returns a [paginated](#pagination) list of fields in the trash. The list may be restricted to fields whose field name or description partially match a string.
     *
     * Only custom fields can be queried, `type` must be set to `custom`.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.startAt - The index of the first item to return in a page of results (page offset).
     * @param params.maxResults - The maximum number of items to return per page.
     * @param params.query - String used to perform a case-insensitive partial match with field names or descriptions.
     * @param params.orderBy - [Order](#ordering) the results by a field: *  `name` sorts by the field name *  `trashDate` sorts by the date the field was moved to the trash *  `plannedDeletionDate` sorts by the planned deletion date
     * @returns Returned if the request is successful.
     */
    getTrashedFieldsPaginated(
      params?: {
        /**
         * The index of the first item to return in a page of results (page offset).
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of items to return per page.
         *
         * @default 50
         * @format int32
         */
        maxResults?: number;
        id?: string[];
        /** String used to perform a case-insensitive partial match with field names or descriptions. */
        query?: string;
        expand?:
          | "name"
          | "-name"
          | "+name"
          | "trashDate"
          | "-trashDate"
          | "+trashDate"
          | "plannedDeletionDate"
          | "-plannedDeletionDate"
          | "+plannedDeletionDate"
          | "projectsCount"
          | "-projectsCount"
          | "+projectsCount";
        /**
         * [Order](#ordering) the results by a field:
         *
         *  *  `name` sorts by the field name
         *  *  `trashDate` sorts by the date the field was moved to the trash
         *  *  `plannedDeletionDate` sorts by the planned deletion date
         */
        orderBy?: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBeanField> {
      return getTrashedFieldsPaginated(ctx, params, options);
    },

    /**
     * Update custom field
     *
     * Updates a custom field.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the custom field.
     * @returns Returned if the request is successful.
     */
    updateCustomField(
      params: UpdateCustomFieldDetails & {
        /** The ID of the custom field. */
        fieldId: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return updateCustomField(ctx, params, options);
    },

    /**
     * Get field project associations
     *
     * Returns a [paginated](#pagination) list of project associations for the given custom field. Each association contains the ID of a project the field is associated with.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the field, for example `customfield_10000`.
     * @param params.startAt - The index of the first item to return in a page of results (page offset).
     * @param params.maxResults - The maximum number of items to return per page.
     * @returns Returned if the request is successful.
     */
    getFieldProjectAssociations(
      params: {
        /** The ID of the field, for example `customfield_10000`. */
        fieldId: string;
        /**
         * The index of the first item to return in a page of results (page offset).
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of items to return per page.
         *
         * @default 50
         * @format int32
         */
        maxResults?: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBeanFieldProjectAssociation> {
      return getFieldProjectAssociations(ctx, params, options);
    },

    /**
     * Get contexts for a field
     *
     * Returns a [paginated](#pagination) list of the contexts a field is used in. Deprecated, use [ Get custom field contexts](#api-rest-api-2-field-fieldId-context-get).
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.fieldId - The ID of the field to return contexts for.
     * @param params.startAt - The index of the first item to return in a page of results (page offset).
     * @param params.maxResults - The maximum number of items to return per page.
     * @returns Returned if the request is successful.
     * @deprecated
     */
    getContextsForFieldDeprecated(
      params: {
        /** The ID of the field to return contexts for. */
        fieldId: string;
        /**
         * The index of the first item to return in a page of results (page offset).
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of items to return per page.
         *
         * @default 20
         * @format int32
         */
        maxResults?: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBeanContext> {
      return getContextsForFieldDeprecated(ctx, params, options);
    },

    /**
     * Delete custom field
     *
     * Deletes a custom field. The custom field is deleted whether it is in the trash or not. See [Edit or delete a custom field](https://confluence.atlassian.com/x/Z44fOw) for more information on trashing and deleting custom fields.
     *
     * This operation is [asynchronous](#async). Follow the `location` link in the response to determine the status of the task and use [Get task](#api-rest-api-2-task-taskId-get) to obtain subsequent updates.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.id - The ID of a custom field.
     */
    deleteCustomField(
      params: {
        /** The ID of a custom field. */
        id: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<void> {
      return deleteCustomField(ctx, params, options);
    },

    /**
     * Restore custom field from trash
     *
     * Restores a custom field from trash. See [Edit or delete a custom field](https://confluence.atlassian.com/x/Z44fOw) for more information on trashing and deleting custom fields.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.id - The ID of a custom field.
     * @returns Returned if the request is successful.
     */
    restoreCustomField(
      params: {
        /** The ID of a custom field. */
        id: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return restoreCustomField(ctx, params, options);
    },

    /**
     * Move custom field to trash
     *
     * Moves a custom field to trash. See [Edit or delete a custom field](https://confluence.atlassian.com/x/Z44fOw) for more information on trashing and deleting custom fields.
     *
     * **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.id - The ID of a custom field.
     * @returns Returned if the request is successful.
     */
    trashCustomField(
      params: {
        /** The ID of a custom field. */
        id: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return trashCustomField(ctx, params, options);
    },

    /**
     * Get fields for projects
     *
     * Returns a [paginated](#pagination) list of fields for the requested projects and work types.
     *
     * Only fields that are available for the specified combination of projects and work types are returned. This endpoint allows filtering to specific fields if field IDs are provided.
     *
     * **[Permissions](#permissions) required:** Permission to access Jira.
     *
     * @param params.startAt - The index of the first item to return in a page of results (page offset).
     * @param params.maxResults - The maximum number of items to return per page.
     * @param params.projectId - The IDs of projects to return fields for.
     * @param params.workTypeId - The IDs of work types (issue types) to return fields for.
     * @param params.fieldId - The IDs of fields to return. If not provided, all fields are returned.
     * @returns Returned if the request is successful.
     */
    getProjectFields(
      params: {
        /**
         * The index of the first item to return in a page of results (page offset).
         *
         * @default 0
         * @format int64
         */
        startAt?: number;
        /**
         * The maximum number of items to return per page.
         *
         * @default 50
         * @format int32
         */
        maxResults?: number;
        /**
         * The IDs of projects to return fields for.
         *
         * @example
         * ```json
         * [
         *   10000,
         *   10001
         * ]
         * ```
         */
        projectId: number[];
        /**
         * The IDs of work types (issue types) to return fields for.
         *
         * @example
         * ```json
         * [
         *   10000,
         *   10001
         * ]
         * ```
         */
        workTypeId: number[];
        /**
         * The IDs of fields to return. If not provided, all fields are returned.
         *
         * @example
         * ```json
         * [
         *   "summary",
         *   "description"
         * ]
         * ```
         */
        fieldId?: string[];
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<PageBean2ProjectFieldBean> {
      return getProjectFields(ctx, params, options);
    },
  };
}
