// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

import type { ClientContext } from "../../client/index.ts";
import type { UpdateDefaultProjectClassificationBean } from "../types/index.ts";

/**
 * Get the classification configuration for a project
 *
 * Returns the consolidated classification configuration for a project's admin settings page.
 *
 * This includes permitted classification levels (with status), the project's default classification level, the organization's default classification level, and the container override setting.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
 *  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
 *  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.projectIdOrKey - The project ID or project key (case-sensitive).
 * @returns Returned if the request is successful.
 */
export function getProjectClassificationConfig(
  ctx: ClientContext,
  params: {
    /** The project ID or project key (case-sensitive). */
    projectIdOrKey: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { projectIdOrKey } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/project/{projectIdOrKey}/classification-config",
    pathParams: { projectIdOrKey },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Get the default data classification level of a project
 *
 * Returns the default data classification for a project.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
 *  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
 *  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.projectIdOrKey - The project ID or project key (case-sensitive).
 * @returns Returned if the request is successful.
 */
export function getDefaultProjectClassification(
  ctx: ClientContext,
  params: {
    /** The project ID or project key (case-sensitive). */
    projectIdOrKey: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { projectIdOrKey } = params;
  return ctx.request({
    method: "get",
    path: "/rest/api/2/project/{projectIdOrKey}/classification-level/default",
    pathParams: { projectIdOrKey },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Update the default data classification level of a project
 *
 * Updates the default data classification level for a project.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
 *  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.projectIdOrKey - The project ID or project key (case-sensitive).
 * @returns Returned if the request is successful.
 */
export function updateDefaultProjectClassification(
  ctx: ClientContext,
  params: UpdateDefaultProjectClassificationBean & {
    /** The project ID or project key (case-sensitive). */
    projectIdOrKey: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { projectIdOrKey, ...body } = params;
  return ctx.request({
    method: "put",
    path: "/rest/api/2/project/{projectIdOrKey}/classification-level/default",
    pathParams: { projectIdOrKey },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Remove the default data classification level from a project
 *
 * Remove the default data classification level for a project.
 *
 * **[Permissions](#permissions) required:**
 *
 *  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
 *  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *
 * @param params.projectIdOrKey - The project ID or project key (case-sensitive).
 * @returns Returned if the request is successful.
 */
export function removeDefaultProjectClassification(
  ctx: ClientContext,
  params: {
    /** The project ID or project key (case-sensitive). */
    projectIdOrKey: string;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { projectIdOrKey } = params;
  return ctx.request({
    method: "delete",
    path: "/rest/api/2/project/{projectIdOrKey}/classification-level/default",
    pathParams: { projectIdOrKey },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/** This resource represents classification levels used in a project. Use it to view and manage classification levels in your projects. */
export function createProjectClassificationLevelsService(ctx: ClientContext) {
  return {
    /**
     * Get the classification configuration for a project
     *
     * Returns the consolidated classification configuration for a project's admin settings page.
     *
     * This includes permitted classification levels (with status), the project's default classification level, the organization's default classification level, and the container override setting.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
     *  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
     *  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.projectIdOrKey - The project ID or project key (case-sensitive).
     * @returns Returned if the request is successful.
     */
    getProjectClassificationConfig(
      params: {
        /** The project ID or project key (case-sensitive). */
        projectIdOrKey: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return getProjectClassificationConfig(ctx, params, options);
    },

    /**
     * Get the default data classification level of a project
     *
     * Returns the default data classification for a project.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
     *  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
     *  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.projectIdOrKey - The project ID or project key (case-sensitive).
     * @returns Returned if the request is successful.
     */
    getDefaultProjectClassification(
      params: {
        /** The project ID or project key (case-sensitive). */
        projectIdOrKey: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return getDefaultProjectClassification(ctx, params, options);
    },

    /**
     * Update the default data classification level of a project
     *
     * Updates the default data classification level for a project.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
     *  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.projectIdOrKey - The project ID or project key (case-sensitive).
     * @returns Returned if the request is successful.
     */
    updateDefaultProjectClassification(
      params: UpdateDefaultProjectClassificationBean & {
        /** The project ID or project key (case-sensitive). */
        projectIdOrKey: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return updateDefaultProjectClassification(ctx, params, options);
    },

    /**
     * Remove the default data classification level from a project
     *
     * Remove the default data classification level for a project.
     *
     * **[Permissions](#permissions) required:**
     *
     *  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
     *  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @param params.projectIdOrKey - The project ID or project key (case-sensitive).
     * @returns Returned if the request is successful.
     */
    removeDefaultProjectClassification(
      params: {
        /** The project ID or project key (case-sensitive). */
        projectIdOrKey: string;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return removeDefaultProjectClassification(ctx, params, options);
    },
  };
}
