// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

import type { ClientContext } from "../../client/index.ts";
import type { ServiceRegistry } from "../types/index.ts";

/**
 * Retrieve the attributes of service registries
 *
 * Retrieve the attributes of given service registries.
 *
 * **[Permissions](#permissions) required:** Only Connect apps can make this request and the servicesIds belong to the tenant you are requesting
 *
 * @param params.serviceIds - The ID of the services (the strings starting with "b:" need to be decoded in Base64).
 * @returns Returned if the request is successful.
 */
export function serviceRegistryResourceServicesGet(
  ctx: ClientContext,
  params: {
    /** The ID of the services (the strings starting with "b:" need to be decoded in Base64). */
    serviceIds: string[];
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<ServiceRegistry[]> {
  const { serviceIds } = params;
  return ctx.request({
    method: "get",
    path: "/rest/atlassian-connect/1/service-registry",
    query: { serviceIds },
    headers: options?.headers,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/** This resource represents a service registry. Use it to retrieve attributes related to a [service registry](https://support.atlassian.com/jira-service-management-cloud/docs/what-is-services/) in JSM. */
export function createServiceRegistryService(ctx: ClientContext) {
  return {
    /**
     * Retrieve the attributes of service registries
     *
     * Retrieve the attributes of given service registries.
     *
     * **[Permissions](#permissions) required:** Only Connect apps can make this request and the servicesIds belong to the tenant you are requesting
     *
     * @param params.serviceIds - The ID of the services (the strings starting with "b:" need to be decoded in Base64).
     * @returns Returned if the request is successful.
     */
    serviceRegistryResourceServicesGet(
      params: {
        /** The ID of the services (the strings starting with "b:" need to be decoded in Base64). */
        serviceIds: string[];
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<ServiceRegistry[]> {
      return serviceRegistryResourceServicesGet(ctx, params, options);
    },
  };
}
