// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

import type { ClientContext } from "../../client/index.ts";
import type { MoveIssuesToBacklogBody, MoveIssuesToBacklogForBoardBody } from "../types/index.ts";

/**
 * Move issues to backlog
 *
 * Move issues to the backlog.
 * This operation is equivalent to remove future and active sprints from a given set of issues. At most 50 issues may be moved at once.
 *
 * @returns Empty response is returned if operation was successful.
 */
export function moveIssuesToBacklog(
  ctx: ClientContext,
  params: MoveIssuesToBacklogBody,
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<void> {
  return ctx.request({
    method: "post",
    path: "/rest/agile/1.0/backlog/issue",
    headers: options?.headers,
    body: params,
    responseType: "void",
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/**
 * Move issues to backlog for board
 *
 * Move issues to the backlog of a particular board (if they are already on that board).
 * This operation is equivalent to remove future and active sprints from a given set of issues if the board has sprints If the board does not have sprints this will put the issues back into the backlog from the board. At most 50 issues may be moved at once.
 *
 * @returns Empty response is returned if operation was successful.
 */
export function moveIssuesToBacklogForBoard(
  ctx: ClientContext,
  params: MoveIssuesToBacklogForBoardBody & {
    /** @format int64 */
    boardId: number;
  },
  options?: {
    headers?: Record<string, string | number | boolean>;
    signal?: AbortSignal;
    extensions?: Record<string, unknown>;
  }
): Promise<unknown> {
  const { boardId, ...body } = params;
  return ctx.request({
    method: "post",
    path: "/rest/agile/1.0/backlog/{boardId}/issue",
    pathParams: { boardId },
    headers: options?.headers,
    body: body,
    signal: options?.signal,
    extensions: options?.extensions,
  });
}

/** Apis related to the backlog */
export function createBacklogService(ctx: ClientContext) {
  return {
    /**
     * Move issues to backlog
     *
     * Move issues to the backlog.
     * This operation is equivalent to remove future and active sprints from a given set of issues. At most 50 issues may be moved at once.
     *
     * @returns Empty response is returned if operation was successful.
     */
    moveIssuesToBacklog(
      params: MoveIssuesToBacklogBody,
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<void> {
      return moveIssuesToBacklog(ctx, params, options);
    },

    /**
     * Move issues to backlog for board
     *
     * Move issues to the backlog of a particular board (if they are already on that board).
     * This operation is equivalent to remove future and active sprints from a given set of issues if the board has sprints If the board does not have sprints this will put the issues back into the backlog from the board. At most 50 issues may be moved at once.
     *
     * @returns Empty response is returned if operation was successful.
     */
    moveIssuesToBacklogForBoard(
      params: MoveIssuesToBacklogForBoardBody & {
        /** @format int64 */
        boardId: number;
      },
      options?: {
        headers?: Record<string, string | number | boolean>;
        signal?: AbortSignal;
        extensions?: Record<string, unknown>;
      }
    ): Promise<unknown> {
      return moveIssuesToBacklogForBoard(ctx, params, options);
    },
  };
}
