// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

/** Details about a task. */
export interface TaskProgress {
  /** The description of the task. */
  description?: string;
  /**
   * The execution time of the task, in milliseconds.
   *
   * @format int64
   */
  elapsedRuntime: number;
  /**
   * A timestamp recording when the task was finished.
   *
   * @format date-time
   */
  finished?: string;
  /** The ID of the task. */
  id: string;
  /**
   * A timestamp recording when the task progress was last updated.
   *
   * @format date-time
   */
  lastUpdate: string;
  /** Information about the progress of the task. */
  message?: string;
  /**
   * The progress of the task, as a percentage complete.
   *
   * @format int64
   */
  progress: number;
  /** The result of the task execution. */
  result?: unknown;
  /**
   * The URL of the task.
   *
   * @format uri
   */
  self: string;
  /**
   * A timestamp recording when the task was started.
   *
   * @format date-time
   */
  started?: string;
  /** The status of the task. */
  status:
    | "ENQUEUED"
    | "RUNNING"
    | "COMPLETE"
    | "FAILED"
    | "CANCEL_REQUESTED"
    | "CANCELLED"
    | "DEAD";
  /**
   * A timestamp recording when the task was submitted.
   *
   * @format date-time
   */
  submitted?: string;
  /**
   * The ID of the user who submitted the task.
   *
   * @format int64
   */
  submittedBy: number;
}
