// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

import type { EntityProperty, Worklog } from "./common.ts";

/** Details of a changed worklog. */
export interface ChangedWorklog {
  /** Details of properties associated with the change. */
  properties?: EntityProperty[];
  /**
   * The datetime of the change.
   *
   * @format int64
   */
  updatedTime?: number;
  /**
   * The ID of the worklog.
   *
   * @format int64
   */
  worklogId?: number;
}

/** List of changed worklogs. */
export interface ChangedWorklogs {
  lastPage?: boolean;
  /**
   * The URL of the next list of changed worklogs.
   *
   * @format uri
   */
  nextPage?: string;
  /**
   * The URL of this changed worklogs list.
   *
   * @format uri
   */
  self?: string;
  /**
   * The datetime of the first worklog item in the list.
   *
   * @format int64
   */
  since?: number;
  /**
   * The datetime of the last worklog item in the list.
   *
   * @format int64
   */
  until?: number;
  /** Changed worklog list. */
  values?: ChangedWorklog[];
}

/** Paginated list of worklog details */
export interface PageOfWorklogs {
  /**
   * The maximum number of results that could be on the page.
   *
   * @format int32
   */
  maxResults?: number;
  /**
   * The index of the first item returned on the page.
   *
   * @format int32
   */
  startAt?: number;
  /**
   * The number of results on the page.
   *
   * @format int32
   */
  total?: number;
  /** List of worklogs. */
  worklogs?: Worklog[];
  [key: string]: unknown;
}

export interface WorklogIdsRequestBean {
  /** A list of worklog IDs. */
  ids: number[];
}

export interface WorklogsMoveRequestBean {
  /** A list of worklog IDs. */
  ids?: number[];
  /** The issue id or key of the destination issue */
  issueIdOrKey?: string;
}
