// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

export interface ArticleDto {
  content?: ContentDto;
  /** Excerpt of the article which matches the given query string. */
  excerpt?: string;
  /** Source of the article. */
  source?: SourceDto;
  /** Title of the article. */
  title?: string;
}

export interface AttachmentLinkDto {
  /**
   * URL for the attachment.
   *
   * @format uri
   */
  content?: string;
  /**
   * REST API URL for the attachment
   *
   * @format uri
   */
  jiraRest?: string;
  /** @format uri */
  self?: string;
  /**
   * URL for the attachment's thumbnail image.
   *
   * @format uri
   */
  thumbnail?: string;
}

export interface ContentDto {
  /** Url containing the body of the article (without title), suitable for rendering in an iframe */
  iframeSrc?: string;
}

export interface CustomerCreateDto {
  /** Customer's name for display in the UI. */
  displayName?: string;
  /** Customer's email address. */
  email?: string;
  /** Deprecated, please use 'displayName'. */
  fullName?: string;
}

export interface CustomerRequestCreateMetaDto {
  /** Flag indicating if participants can be added to a request (true) or not. */
  canAddRequestParticipants?: boolean;
  /** Flag indicating if a request can be raised on behalf of another user (true) or not. */
  canRaiseOnBehalfOf?: boolean;
  /** List of the fields included in this request. */
  requestTypeFields?: RequestTypeFieldDto[];
}

export interface CustomerRequestLinkDto {
  /**
   * Jira agent view URL for the request.
   *
   * @format uri
   */
  agent?: string;
  /**
   * REST API URL for the request.
   *
   * @format uri
   */
  jiraRest?: string;
  /** @format uri */
  self?: string;
  /**
   * Web URL for the request.
   *
   * @format uri
   */
  web?: string;
}

export interface DateDto {
  /**
   * Date as the number of milliseconds that have elapsed since 00:00:00 Coordinated Universal Time (UTC), 1 January 1970.
   *
   * @format int64
   */
  epochMillis?: number;
  /** Date in a user-friendly text format. */
  friendly?: string;
  /** Date in ISO8601 format. */
  iso8601?: string;
  /** Date in the format used in the Jira REST APIs, which is ISO8601 format but extended with milliseconds. For example, 2016-09-28T23:08:32.097+1000. */
  jira?: string;
}

/** An entity property, for more information see [Entity properties](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/). */
export interface EntityProperty {
  /** The key of the property. Required on create and update. */
  key?: string;
  /** The value of the property. Required on create and update. */
  value?: unknown;
}

export interface ErrorResponse {
  errorMessage?: string;
  i18nErrorMessage?: I18nErrorMessage;
}

export interface Expandable {
  _expands?: string[];
}

export interface FormValidationErrorContextDto {
  /** ID of the form entity related to the validation error. */
  id?: string;
  /** Type of form entity related to the validation error. */
  type?: string;
}

export interface FormValidationErrorDto {
  /** Machine-readable validation error code. */
  code?: string;
  /** Identifies the form entity that caused the validation error. */
  context?: FormValidationErrorContextDto[];
  /** Detailed validation error message. */
  detail?: string;
  /**
   * The HTTP status code.
   *
   * @format int32
   */
  status?: number;
  /** Short summary of the validation error. */
  title?: string;
}

export interface FormValidationErrorResponseDto {
  /** Description of the error. */
  errorMessage?: string;
  /** A list of validation errors. */
  errors?: FormValidationErrorDto[];
  /** Internationalized error message details. */
  i18nErrorMessage?: I18nErrorMessageDto;
}

export interface I18nErrorMessage {
  i18nKey?: string;
  parameters?: string[];
}

export interface I18nErrorMessageDto {
  /** Internationalization key for the error message. */
  i18nKey?: string;
  /** Parameters used to render the internationalized error message. */
  parameters?: string[];
}

export interface InputStreamSource {
  inputStream?: Record<string, unknown>;
}

/** The schema of a field. */
export interface JsonTypeBean {
  /** If the field is a custom field, the configuration of the field. */
  configuration?: Record<string, unknown>;
  /** If the field is a custom field, the URI of the field. */
  custom?: string;
  /**
   * If the field is a custom field, the custom ID of the field.
   *
   * @format int64
   */
  customId?: number;
  /** When the data type is an array, the name of the field items within the array. */
  items?: string;
  /** If the field is a system field, the name of the field. */
  system?: string;
  /** The data type of the field. */
  type: string;
}

export interface Linkable {
  _links?: SelfLinkDto;
}

export interface LinkableAttachmentLinkDto {
  _links?: AttachmentLinkDto;
}

export interface LinkableCustomerRequestLinkDto {
  _links?: CustomerRequestLinkDto;
}

export interface LinkableUserLinkDto {
  _links?: UserLinkDto;
}

export interface PagedDtoArticleDto {
  _expands?: string[];
  /** List of the links relating to the page. */
  _links?: PagedLinkDto;
  /** Indicates if this is the last page of records (true) or not (false). */
  isLastPage?: boolean;
  /**
   * Number of items to be returned per page, up to the maximum set for these objects in the current implementation.
   *
   * @format int32
   */
  limit?: number;
  /**
   * Number of items returned in the page.
   *
   * @format int32
   */
  size?: number;
  /**
   * Index of the first item returned in the page.
   *
   * @format int32
   */
  start?: number;
  /** Details of the items included in the page. */
  values?: ArticleDto[];
}

export interface PagedDtoRequestTypeDto {
  _expands?: string[];
  /** List of the links relating to the page. */
  _links?: PagedLinkDto;
  /** Indicates if this is the last page of records (true) or not (false). */
  isLastPage?: boolean;
  /**
   * Number of items to be returned per page, up to the maximum set for these objects in the current implementation.
   *
   * @format int32
   */
  limit?: number;
  /**
   * Number of items returned in the page.
   *
   * @format int32
   */
  size?: number;
  /**
   * Index of the first item returned in the page.
   *
   * @format int32
   */
  start?: number;
  /** Details of the items included in the page. */
  values?: RequestTypeDto[];
}

export interface PagedDtoUserDto {
  _expands?: string[];
  /** List of the links relating to the page. */
  _links?: PagedLinkDto;
  /** Indicates if this is the last page of records (true) or not (false). */
  isLastPage?: boolean;
  /**
   * Number of items to be returned per page, up to the maximum set for these objects in the current implementation.
   *
   * @format int32
   */
  limit?: number;
  /**
   * Number of items returned in the page.
   *
   * @format int32
   */
  size?: number;
  /**
   * Index of the first item returned in the page.
   *
   * @format int32
   */
  start?: number;
  /** Details of the items included in the page. */
  values?: UserDto[];
}

export interface PagedLinkDto {
  /**
   * Base URL for the REST API calls.
   *
   * @format uri
   */
  base?: string;
  context?: string;
  /**
   * REST API URL for the next page, if there is one.
   *
   * @format uri
   */
  next?: string;
  /**
   * REST API URL for the previous page, if there is one.
   *
   * @format uri
   */
  prev?: string;
  /**
   * REST API URL for the current page.
   *
   * @format uri
   */
  self?: string;
}

/** Property key details. */
export interface PropertyKey {
  /** The key of the property. */
  key?: string;
  /** The URL of the property. */
  self?: string;
}

/** List of property keys. */
export interface PropertyKeys {
  /** Property key details. */
  keys?: PropertyKey[];
}

export interface RequestTypeDto {
  /** List of items that can be expanded in the response by specifying the expand query parameter. */
  _expands?: string[];
  /** REST API URL for the request type. */
  _links?: SelfLinkDto;
  /** Whether the user has permission to create a request with this request type. */
  canCreateRequest?: boolean;
  /** Description of the request type. */
  description?: string;
  /** Fields and additional metadata for creating a request that uses the request type */
  fields?: CustomerRequestCreateMetaDto;
  /** List of the request type groups the request type belongs to. */
  groupIds?: string[];
  /** Help text for the request type. */
  helpText?: string;
  /** Links to the request type's icons. */
  icon?: RequestTypeIconDto;
  /** ID for the request type. */
  id?: string;
  /** ID of the issue type the request type is based upon. */
  issueTypeId?: string;
  /** Short name for the request type. */
  name?: string;
  /** ID of the customer portal associated with the service desk project. */
  portalId?: string;
  /** The request type's practice */
  practice?: string;
  /** Whether request type is restricted or not. */
  restrictionStatus?: "OPEN" | "RESTRICTED";
  /** ID of the service desk the request type belongs to. */
  serviceDeskId?: string;
}

export interface RequestTypeFieldDto {
  /** List of default values for the field. */
  defaultValues?: RequestTypeFieldValueDto[];
  /** Description of the field. */
  description?: string;
  /** ID of the field. */
  fieldId?: string;
  /** Jira specific implementation details for the field in the UI. */
  jiraSchema?: JsonTypeBean;
  /** Name of the field. */
  name?: string;
  /** List of preset values for the field. */
  presetValues?: string[];
  /** Indicates if the field is required (true) or not (false). */
  required?: boolean;
  /** List of valid values for the field. */
  validValues?: RequestTypeFieldValueDto[];
  visible?: boolean;
}

export interface RequestTypeFieldValueDto {
  /** List of child fields. */
  children?: RequestTypeFieldValueDto[];
  /** Label for the field. */
  label?: string;
  /** Value of the field. */
  value?: string;
}

export interface RequestTypeIconDto {
  /** Map of the URLs for the request type icons. */
  _links?: RequestTypeIconLinkDto;
  /** ID of the request type icon. */
  id?: string;
}

export interface RequestTypeIconLinkDto {
  /** URLs for the request type icons. */
  iconUrls?: Record<string, string>;
}

export interface SelfLinkDto {
  /** @format uri */
  self?: string;
}

export interface ServiceDeskCustomerDto {
  /** List of users, specified by account IDs, to add to or remove from a service desk. */
  accountIds?: string[];
  /** This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. Use `accountIds` instead. */
  usernames?: string[];
}

export interface ServiceDeskDto {
  /** REST API URL to the service desk. */
  _links?: SelfLinkDto;
  /** ID of the service desk. */
  id?: string;
  /** ID of the peer project for the service desk. */
  projectId?: string;
  /** Key of the peer project of the service desk. */
  projectKey?: string;
  /** Name of the project and service desk. */
  projectName?: string;
  /** Key of the project type. */
  projectTypeKey?: string;
}

export interface SourceDto {
  /** Type of the knowledge base source */
  type?: "confluence";
  [key: string]: unknown;
}

export interface UserDto {
  /** URLs for the customer record and related items. */
  _links?: UserLinkDto;
  /** The accountId of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*. */
  accountId?: string;
  /** Indicates if the customer is active (true) or inactive (false) */
  active?: boolean;
  /** Customer's name for display in a UI. Depending on the customer’s privacy settings, this may return an alternative value. */
  displayName?: string;
  /** Customer's email address. Depending on the customer’s privacy settings, this may be returned as null. */
  emailAddress?: string;
  /** This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. */
  key?: string;
  /** This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. */
  name?: string;
  /** Customer time zone. Depending on the customer’s privacy settings, this may be returned as null. */
  timeZone?: string;
}

export interface UserLinkDto {
  /** Links to the various sizes of the customer's avatar. Note that this property is deprecated, and will be removed in future versions. */
  avatarUrls?: Record<string, string>;
  /**
   * REST API URL for the customer.
   *
   * @format uri
   */
  jiraRest?: string;
  /** @format uri */
  self?: string;
}
