// Generated by @narthia/openapi-sdk-generator. Do not edit manually.

import type { JsonTypeBean, PagedLinkDto, SelfLinkDto, ServiceDeskDto } from "./common.ts";

export interface AvatarUrlsBean {
  /**
   * The URL of the item's 16x16 pixel avatar.
   *
   * @format uri
   */
  "16x16"?: string;
  /**
   * The URL of the item's 24x24 pixel avatar.
   *
   * @format uri
   */
  "24x24"?: string;
  /**
   * The URL of the item's 32x32 pixel avatar.
   *
   * @format uri
   */
  "32x32"?: string;
  /**
   * The URL of the item's 48x48 pixel avatar.
   *
   * @format uri
   */
  "48x48"?: string;
}

/** A change item. */
export interface ChangeDetails {
  /** The name of the field changed. */
  field?: string;
  /** The ID of the field changed. */
  fieldId?: string;
  /** The type of the field changed. */
  fieldtype?: string;
  /** The details of the original value. */
  from?: string;
  /** The details of the original value as a string. */
  fromString?: string;
  /** The details of the new value. */
  to?: string;
  /** The details of the new value as a string. */
  toString?: string;
}

/** A log of changes made to issue fields. Changelogs related to workflow associations are currently being deprecated. */
export interface Changelog {
  /** The user who made the change. */
  author?: UserDetails;
  /**
   * The date on which the change took place.
   *
   * @format date-time
   */
  created?: string;
  /** The history metadata associated with the changed. */
  historyMetadata?: HistoryMetadata;
  /** The ID of the changelog. */
  id?: string;
  /** The list of items changed. */
  items?: ChangeDetails[];
}

/** The metadata describing an issue field. */
export interface FieldMetadata {
  /** The list of values allowed in the field. */
  allowedValues?: unknown[];
  /** The URL that can be used to automatically complete the field. */
  autoCompleteUrl?: string;
  /** The configuration properties. */
  configuration?: Record<string, unknown>;
  /** The default value of the field. */
  defaultValue?: unknown;
  /** Whether the field has a default value. */
  hasDefaultValue?: boolean;
  /** The key of the field. */
  key: string;
  /** The name of the field. */
  name: string;
  /** The list of operations that can be performed on the field. */
  operations: string[];
  /** Whether the field is required. */
  required: boolean;
  /** The data type of the field. */
  schema: JsonTypeBean;
}

/** Details of issue history metadata. */
export interface HistoryMetadata {
  /** The activity described in the history record. */
  activityDescription?: string;
  /** The key of the activity described in the history record. */
  activityDescriptionKey?: string;
  /** Details of the user whose action created the history record. */
  actor?: HistoryMetadataParticipant;
  /** Details of the cause that triggered the creation the history record. */
  cause?: HistoryMetadataParticipant;
  /** The description of the history record. */
  description?: string;
  /** The description key of the history record. */
  descriptionKey?: string;
  /** The description of the email address associated the history record. */
  emailDescription?: string;
  /** The description key of the email address associated the history record. */
  emailDescriptionKey?: string;
  /** Additional arbitrary information about the history record. */
  extraData?: Record<string, string>;
  /** Details of the system that generated the history record. */
  generator?: HistoryMetadataParticipant;
  /** The type of the history record. */
  type?: string;
  [key: string]: unknown;
}

/** Details of user or system associated with a issue history metadata item. */
export interface HistoryMetadataParticipant {
  /** The URL to an avatar for the user or system associated with a history record. */
  avatarUrl?: string;
  /** The display name of the user or system associated with a history record. */
  displayName?: string;
  /** The key of the display name of the user or system associated with a history record. */
  displayNameKey?: string;
  /** The ID of the user or system associated with a history record. */
  id?: string;
  /** The type of the user or system associated with a history record. */
  type?: string;
  /** The URL of the user or system associated with a history record. */
  url?: string;
  [key: string]: unknown;
}

export interface IncludedFields {
  actuallyIncluded?: string[];
  excluded?: string[];
  included?: string[];
}

/** Details about an issue. */
export interface IssueBean {
  /** Details of changelogs associated with the issue. */
  changelog?: PageOfChangelogs;
  /** The metadata for the fields on the issue that can be amended. */
  editmeta?: IssueUpdateMetadata;
  /** Expand options that include additional issue details in the response. */
  expand?: string;
  fields?: Record<string, unknown>;
  fieldsToInclude?: IncludedFields;
  /** The ID of the issue. */
  id?: string;
  /** The key of the issue. */
  key?: string;
  /** The ID and name of each field present on the issue. */
  names?: Record<string, string>;
  /** The operations that can be performed on the issue. */
  operations?: Operations;
  /** Details of the issue properties identified in the request. */
  properties?: Record<string, unknown>;
  /** The rendered value of each field present on the issue. */
  renderedFields?: Record<string, unknown>;
  /** The schema describing each field present on the issue. */
  schema?: Record<string, JsonTypeBean>;
  /**
   * The URL of the issue details.
   *
   * @format uri
   */
  self?: string;
  /** The transitions that can be performed on the issue. */
  transitions?: IssueTransition[];
  /** The versions of each field on the issue. */
  versionedRepresentations?: Record<string, Record<string, unknown>>;
}

/** Details of an issue transition. */
export interface IssueTransition {
  /** Expand options that include additional transition details in the response. */
  expand?: string;
  /** Details of the fields associated with the issue transition screen. Use this information to populate `fields` and `update` in a transition request. */
  fields?: Record<string, FieldMetadata>;
  /** Whether there is a screen associated with the issue transition. */
  hasScreen?: boolean;
  /** The ID of the issue transition. Required when specifying a transition to undertake. */
  id?: string;
  /** Whether the transition is available to be performed. */
  isAvailable?: boolean;
  /** Whether the issue has to meet criteria before the issue transition is applied. */
  isConditional?: boolean;
  /** Whether the issue transition is global, that is, the transition is applied to issues regardless of their status. */
  isGlobal?: boolean;
  /** Whether this is the initial issue transition for the workflow. */
  isInitial?: boolean;
  looped?: boolean;
  /** The name of the issue transition. */
  name?: string;
  /** Details of the issue status after the transition. */
  to?: StatusDetails;
  [key: string]: unknown;
}

/** A list of editable field details. */
export interface IssueUpdateMetadata {
  fields?: Record<string, FieldMetadata>;
}

/** Details a link group, which defines issue operations. */
export interface LinkGroup {
  groups?: LinkGroup[];
  header?: SimpleLink;
  id?: string;
  links?: SimpleLink[];
  styleClass?: string;
  /** @format int32 */
  weight?: number;
}

export interface MultipartFile {
  bytes?: string[];
  contentType?: string;
  empty?: boolean;
  inputStream?: Record<string, unknown>;
  name?: string;
  originalFilename?: string;
  resource?: Resource;
  /** @format int64 */
  size?: number;
}

/** Details of the operations that can be performed on the issue. */
export interface Operations {
  /** Details of the link groups defining issue operations. */
  linkGroups?: LinkGroup[];
  [key: string]: unknown;
}

/** A page of changelogs. */
export interface PageOfChangelogs {
  /** The list of changelogs. */
  histories?: Changelog[];
  /**
   * The maximum number of results that could be on the page.
   *
   * @format int32
   */
  maxResults?: number;
  /**
   * The index of the first item returned on the page.
   *
   * @format int32
   */
  startAt?: number;
  /**
   * The number of results on the page.
   *
   * @format int32
   */
  total?: number;
}

export interface PagedDtoIssueBean {
  _expands?: string[];
  /** List of the links relating to the page. */
  _links?: PagedLinkDto;
  /** Indicates if this is the last page of records (true) or not (false). */
  isLastPage?: boolean;
  /**
   * Number of items to be returned per page, up to the maximum set for these objects in the current implementation.
   *
   * @format int32
   */
  limit?: number;
  /**
   * Number of items returned in the page.
   *
   * @format int32
   */
  size?: number;
  /**
   * Index of the first item returned in the page.
   *
   * @format int32
   */
  start?: number;
  /** Details of the items included in the page. */
  values?: IssueBean[];
}

export interface PagedDtoQueueDto {
  _expands?: string[];
  /** List of the links relating to the page. */
  _links?: PagedLinkDto;
  /** Indicates if this is the last page of records (true) or not (false). */
  isLastPage?: boolean;
  /**
   * Number of items to be returned per page, up to the maximum set for these objects in the current implementation.
   *
   * @format int32
   */
  limit?: number;
  /**
   * Number of items returned in the page.
   *
   * @format int32
   */
  size?: number;
  /**
   * Index of the first item returned in the page.
   *
   * @format int32
   */
  start?: number;
  /** Details of the items included in the page. */
  values?: QueueDto[];
}

export interface PagedDtoRequestTypeGroupDto {
  _expands?: string[];
  /** List of the links relating to the page. */
  _links?: PagedLinkDto;
  /** Indicates if this is the last page of records (true) or not (false). */
  isLastPage?: boolean;
  /**
   * Number of items to be returned per page, up to the maximum set for these objects in the current implementation.
   *
   * @format int32
   */
  limit?: number;
  /**
   * Number of items returned in the page.
   *
   * @format int32
   */
  size?: number;
  /**
   * Index of the first item returned in the page.
   *
   * @format int32
   */
  start?: number;
  /** Details of the items included in the page. */
  values?: RequestTypeGroupDto[];
}

export interface PagedDtoServiceDeskDto {
  _expands?: string[];
  /** List of the links relating to the page. */
  _links?: PagedLinkDto;
  /** Indicates if this is the last page of records (true) or not (false). */
  isLastPage?: boolean;
  /**
   * Number of items to be returned per page, up to the maximum set for these objects in the current implementation.
   *
   * @format int32
   */
  limit?: number;
  /**
   * Number of items returned in the page.
   *
   * @format int32
   */
  size?: number;
  /**
   * Index of the first item returned in the page.
   *
   * @format int32
   */
  start?: number;
  /** Details of the items included in the page. */
  values?: ServiceDeskDto[];
}

/** Details about a project. */
export interface ProjectDetails {
  /** The URLs of the project's avatars. */
  avatarUrls?: AvatarUrlsBean;
  /** The ID of the project. */
  id?: string;
  /** The key of the project. */
  key?: string;
  /** The name of the project. */
  name?: string;
  /** The category the project belongs to. */
  projectCategory?: UpdatedProjectCategory;
  /** The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project. */
  projectTypeKey?: "software" | "service_desk" | "business";
  /** The URL of the project details. */
  self?: string;
  /** Whether or not the project is simplified. */
  simplified?: boolean;
}

export interface QueueDto {
  /** REST API URL to the queue. */
  _links?: SelfLinkDto;
  /** Fields returned for each request in the queue. */
  fields?: string[];
  /** ID for the queue. */
  id?: string;
  /**
   * The count of customer requests in the queue.
   *
   * @format int64
   */
  issueCount?: number;
  /** JQL query that filters reqeusts for the queue. */
  jql?: string;
  /** Short name for the queue. */
  name?: string;
}

export interface RequestTypeCreateDto {
  /** Description of the request type on the service desk. */
  description?: string;
  /** Help text for the request type on the service desk. */
  helpText?: string;
  /** ID of the request type to add to the service desk. */
  issueTypeId?: string;
  /** Name of the request type on the service desk. */
  name?: string;
}

export interface RequestTypeGroupDto {
  /** ID of the request type group */
  id?: string;
  /** Name of the request type group. */
  name?: string;
}

export interface RequestTypePermissionCheckRequestDto {
  /** The account ID of a user. */
  accountId?: string;
  /** List of requested permissions. */
  permissions?: ("canCreateRequest" | "canAdminister")[];
  /** List of request type IDs. */
  requestTypeIds?: number[];
}

export interface RequestTypePermissionCheckResponse {
  /** List of request type IDs for which the user has permission to administer. */
  canAdminister?: number[];
  /** List of request type IDs for which the user can create requests. */
  canCreateRequest?: number[];
}

export interface Resource {
  contentAsByteArray?: string[];
  description?: string;
  file?: Blob;
  filename?: string;
  inputStream?: Record<string, unknown>;
  open?: boolean;
  readable?: boolean;
  /** @format uri */
  uri?: string;
  /** @format url */
  url?: string;
}

/** The projects the item is associated with. Indicated for items associated with [next-gen projects](https://confluence.atlassian.com/x/loMyO). */
export interface Scope {
  /** The project the item has scope in. */
  project?: ProjectDetails;
  /** The type of scope. */
  type?: "PROJECT" | "TEMPLATE";
  [key: string]: unknown;
}

export interface ServiceDeskCustomerInviteDto {
  /** Customer's name for display in the UI. */
  displayName?: string;
  /** Customer's email address. */
  email?: string;
}

/** Details about the operations available in this version. */
export interface SimpleLink {
  href?: string;
  iconClass?: string;
  id?: string;
  label?: string;
  styleClass?: string;
  title?: string;
  /** @format int32 */
  weight?: number;
}

/** A status category. */
export interface StatusCategory {
  /** The name of the color used to represent the status category. */
  colorName?: string;
  /**
   * The ID of the status category.
   *
   * @format int64
   */
  id?: number;
  /** The key of the status category. */
  key?: string;
  /** The name of the status category. */
  name?: string;
  /** The URL of the status category. */
  self?: string;
  [key: string]: unknown;
}

/** A status. */
export interface StatusDetails {
  /** The description of the status. */
  description?: string;
  /** The URL of the icon used to represent the status. */
  iconUrl?: string;
  /** The ID of the status. */
  id?: string;
  /** The name of the status. */
  name?: string;
  /** The scope of the field. */
  scope?: Scope;
  /** The URL of the status. */
  self?: string;
  /** The category assigned to the status. */
  statusCategory?: StatusCategory;
  [key: string]: unknown;
}

/** A project category. */
export interface UpdatedProjectCategory {
  /** The name of the project category. */
  description?: string;
  /** The ID of the project category. */
  id?: string;
  /** The description of the project category. */
  name?: string;
  /** The URL of the project category. */
  self?: string;
}

/**
 * User details permitted by the user's Atlassian Account privacy settings. However, be aware of these exceptions:
 *
 *  *  User record deleted from Atlassian: This occurs as the result of a right to be forgotten request. In this case, `displayName` provides an indication and other parameters have default values or are blank (for example, email is blank).
 *  *  User record corrupted: This occurs as a results of events such as a server import and can only happen to deleted users. In this case, `accountId` returns *unknown* and all other parameters have fallback values.
 *  *  User record unavailable: This usually occurs due to an internal service outage. In this case, all parameters have fallback values.
 */
export interface UserDetails {
  /** The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*. */
  accountId?: string;
  /** The type of account represented by this user. This will be one of 'atlassian' (normal users), 'app' (application user) or 'customer' (Jira Service Desk customer user) */
  accountType?: string;
  /** Whether the user is active. */
  active?: boolean;
  /** The avatars of the user. */
  avatarUrls?: AvatarUrlsBean;
  /** The display name of the user. Depending on the user’s privacy settings, this may return an alternative value. */
  displayName?: string;
  /** The email address of the user. Depending on the user’s privacy settings, this may be returned as null. */
  emailAddress?: string;
  /** This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. */
  key?: string;
  /** This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. */
  name?: string;
  /** The URL of the user. */
  self?: string;
  /** The time zone specified in the user's profile. Depending on the user’s privacy settings, this may be returned as null. */
  timeZone?: string;
}
